[address]
other = "address"
[channel]
other = "channel"
[command_ban]
other = "ban"
[command_ban_desc]
other = "ban the selected user"
[command_ban_message]
other = "{{.Target}} has been banned"
[command_ban_option_desc_reason]
other = "reason for ban"
[command_ban_option_desc_target]
other = "user to ban"
[command_ban_option_reason]
other = "reason"
[command_ban_option_target]
other = "target"
[command_ban_reason]
one = "Reason: {{.Reason}}"
other = "Reasons: {{.Reason}}"
[command_kick]
other = "kick"
[command_kick_desc]
other = "kick the selected user"
[command_kick_message]
other = "{{.Target}} has been kicked"
[command_kick_option_desc_target]
other = "user to kick"
[command_kick_option_target]
other = "target"
[command_panel]
other = "panel"
[command_panel_desc]
other = "manage or create panel"
[command_panel_option_desc_role]
other = "manage role panel"
[command_panel_option_minecraft]
other = "minecraft"
[command_panel_option_minecraft_desc]
other = "manage minecraft panel"
[command_panel_option_minecraft_message]
other = "To add a server right click or long press on the message and press \"Apps\" then \"modify\""
[command_panel_option_minecraft_option_create]
other = "create"
[command_panel_option_minecraft_option_create_desc]
other = "create minecraft panel"
[command_panel_option_minecraft_option_create_option_address]
other = "address"
[command_panel_option_minecraft_option_create_option_address_desc]
other = "address of server"
[command_panel_option_minecraft_option_create_option_description]
other = "description"
[command_panel_option_minecraft_option_create_option_description_desc]
other = "description of panel"
[command_panel_option_minecraft_option_create_option_name]
other = "name"
[command_panel_option_minecraft_option_create_option_name_desc]
other = "name of panel"
[command_panel_option_minecraft_option_create_option_port]
other = "port"
[command_panel_option_minecraft_option_create_option_port_desc]
other = "port of server"
[command_panel_option_minecraft_option_create_option_servername]
other = "servername"
[command_panel_option_minecraft_option_create_option_servername_desc]
other = "name of server"
[command_panel_option_minecraft_option_create_option_showip]
other = "showip"
[command_panel_option_minecraft_option_create_option_showip_desc]
other = "show ip or not"
[command_panel_option_minecraft_placeholder]
other = "Select server"
[command_panel_option_role]
other = "role"
[command_panel_option_role_message]
other = "To add a role right click or press and hold on the message and press \"Apps\" then \"modify\""
[command_panel_option_role_option_create]
other = "create"
[command_panel_option_role_option_create_option_desc]
other = "desc"
[command_panel_option_role_option_create_option_desc_desc]
other = "desc of panel"
[command_panel_option_role_option_create_option_desc_name]
other = "name of panel"
[command_panel_option_role_option_create_option_desc_role]
other = "role that add to the panel"
[command_panel_option_role_option_create_option_name]
other = "name"
[command_panel_option_role_option_create_option_role]
other = "role"
[command_panel_option_role_option_desc_create]
other = "create role panel"
[command_role]
other = "role"
[command_role_desc]
other = "manage role"
[command_role_option_color]
other = "color"
[command_role_option_color_desc]
other = "create color role"
[command_role_option_color_option_name]
other = "name"
[command_role_option_color_option_name_desc]
other = "name of role"
[command_role_option_color_option_rgb]
other = "rgb"
[command_role_option_color_option_rgb_desc]
other = "rgb color code"
[command_tracker]
other = "tracker"
[command_tracker_desc]
other = "manage or create tracker"
[command_tracker_option_minecraft]
other = "minecraft"
[command_tracker_option_minecraft_desc]
other = "manage minecraft server tracker"
[command_tracker_option_minecraft_option_create]
other = "create"
[command_tracker_option_minecraft_option_create_desc]
other = "minecraft server tracker"
[command_tracker_option_minecraft_option_create_option_address]
other = "address"
[command_tracker_option_minecraft_option_create_option_address_desc]
other = "address of server"
[command_tracker_option_minecraft_option_create_option_name]
other = "name"
[command_tracker_option_minecraft_option_create_option_name_desc]
other = "name of server"
[command_tracker_option_minecraft_option_create_option_port]
other = "port"
[command_tracker_option_minecraft_option_create_option_port_desc]
other = "port of server"
[command_tracker_option_minecraft_option_create_option_role]
other = "role"
[command_tracker_option_minecraft_option_create_option_role_desc]
other = "role to mention"
[command_tracker_option_minecraft_option_get]
other = "get"
[command_tracker_option_minecraft_option_get_desc]
other = "get minecraft trackers"
[command_tracker_option_minecraft_option_remove]
other = "remove"
[command_tracker_option_minecraft_option_remove_desc]
other = "remove minecraft trackers"
[command_tracker_option_minecraft_option_remove_option_name]
other = "name"
[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "name of tracker"
[command_unban]
other = "unban"
[command_unban_desc]
other = "unban the selected user"
[command_unban_message]
other = "{{.Target}} has been unbanned"
[command_unban_option_desc_target]
other = "user to unban"
[command_unban_option_target]
other = "target"
[error]
other = "{{.Error}}"
[error_0]
other = "An error has occurred {{.Error}}"
[error_TargetIsBot]
other = "Cannot select this bot as target!"
[error_failed_to_connect_api]
other = "failed to connect api server error"
[error_failed_to_ping_server]
other = "failed to ping server"
[error_invalid_port_value]
other = "invalid port value"
[error_message]
other = "An error has occurred"
[feed_minecraft_webhook_name]
other = "server notifier"
[latency]
other = "latency"
[message_command_modify]
other = "modify"
[message_command_user_info]
other = "info"
[message_command_user_info_color_code]
other = "Color Code"
[message_command_user_info_id]
other = "ID"
[message_command_user_info_joined_at]
other = "Joined at"
[message_command_user_info_nick]
other = "Nick"
[message_command_user_info_none]
other = "none"
[message_command_user_info_roles]
other = "Roles"
[panel_minecraft_message_boot]
other = "booted {{.Name}} server"
[panel_minecraft_message_stop]
other = "stopped {{.Name}} server"
[panel_role_message_added]
other = "added"
[panel_role_message_removed]
other = "removed"
[players]
other = "players"
[port]
other = "port"
[version]
other = "version"
[message_modify_cant_use_this_message_error]
other="not available for that message"
[message_modify_role_add_message]
other="Choose a role to add"
[message_modify_role_create_message]
other="Coose a role to create panel"
[message_command_select_message]
other="selected"
[message_command_select]
other="select"
[command_panel_option_config]
other="config"
[command_panel_option_config_desc]
other="configure proprties"
[command_panel_option_config_option_emoji]
other="emoji"
[command_panel_option_config_option_emoji_desc]
other="Set custom emoji in select menu"
[command_panel_option_config_option_emoji_message]
other="Please send emoji in this channel"