[command.ban.description]
other = "zakázat vybraného uživatele"

[command.ban.option.target]
other = "target"

[command.ban.option.description.target]
other = "zabanovat uživatele"

[command.ban.option.description.reason]
other = "důvod zákazu"

[command.ban.option.reason]
other = "důvod"

[command.ban.message]
other = "{{.Target}} byl zabanován"

[command.ban.reason]
one = "Důvod: {{.Reason}}"
other = "Důvody: {{.Reason}}"

[command.kick.description]
other = "vyhodit vybraného uživatele"

[command.kick.option.target]
other = "target"

[command.kick.option.description.target]
other = "vykopnout uživatele"

[command.kick.message]
other = "{{.Target}} byl vyhozen"

[command.unban.description]
other = "pardon the selected user"

[command.unban.option.target]
other = "target"

[command.unban.option.description.target]
other = "odblokovat uživatele"

[command.unban.message]
other = "{{.Target}} byl odblokován"

[error.0]
other = "Došlo k chybě {{.Error}}"

[error.TargetIsBot]
other = "Tohoto bota nelze vybrat jako cíl!"

[error.message]
other = "Došlo k chybě"
