command = { }
command_ban = { }
command_ban_option = { }
command_ban_option_desc = { }
command_kick = { }
command_kick_option = { }
command_kick_option_desc = { }
command_panel = { }
command_panel_option = { }
command_panel_option_desc = { }
command_panel_option_role_option_create_option = { }
command_panel_option_role_option_desc = { }
command_unban = { }
command_unban_option = { }
command_unban_option_desc = { }
error = { }

[command_ban_desc]
other = "zakázat vybraného uživatele"

[command_ban_message]
other = "{{.Target}} byl zabanován"

[command_ban_option_desc_reason]
other = "důvod zákazu"

[command_ban_option_desc_target]
other = "zabanovat uživatele"

[command_ban_option_reason]
other = "důvod"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Důvod: {{.Reason}}"
other = "Důvody: {{.Reason}}"

[command_kick_desc]
other = "vyhodit vybraného uživatele"

[command_kick_message]
other = "{{.Target}} byl vyhozen"

[command_kick_option_desc_target]
other = "vykopnout uživatele"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "spravovat nebo vytvářet panel"

[command_panel_option_desc_role]
other = "spravovat panel rolí"

[command_panel_option_role]
other = "role"

[command_panel_option_role_option_create]
other = "vytvořit"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "sesta dílce"

[command_panel_option_role_option_create_option_desc_name]
other = "název dílce"

[command_panel_option_role_option_create_option_desc_role]
other = "role, která přidává do panelu"

[command_panel_option_role_option_create_option_name]
other = "jméno"

[command_panel_option_role_option_create_option_role]
other = "role"

[command_panel_option_role_option_desc_create]
other = "vytvořit panel role"

[command_unban_desc]
other = "odblokovat vybraného uživatele"

[command_unban_message]
other = "{{.Target}} byl odblokován"

[command_unban_option_desc_target]
other = "odblokovat uživatele"

[command_unban_option_target]
other = "target"

[error_0]
other = "Došlo k chybě {{.Error}}"

[error_TargetIsBot]
other = "Tohoto bota nelze vybrat jako cíl!"

[error_message]
other = "Došlo k chybě"
