[command.ban.description]
other = "zakázat vybraného uživatele"

[command.ban.message]
other = "{{.Target}} byl zabanován"

[command.ban.option.description.reason]
other = "důvod zákazu"

[command.ban.option.description.target]
other = "zabanovat uživatele"

[command.ban.option.reason]
other = "důvod"

[command.ban.option.target]
other = "target"

[command.ban.reason]
one = "Důvod: {{.Reason}}"
other = "Důvody: {{.Reason}}"

[command.kick.description]
other = "vyhodit vybraného uživatele"

[command.kick.message]
other = "{{.Target}} byl vyhozen"

[command.kick.option.description.target]
other = "vykopnout uživatele"

[command.kick.option.target]
other = "target"

[command.panel.description]
other = "manage or create panel"

[command.panel.option.description.role]
other = "manage role panel"

[command.panel.option.role]
other = "role"

[command.panel.option.role.option.crate.option.desc]
other = "description"

[command.panel.option.role.option.create]
other = "create"

[command.panel.option.role.option.create.option.description.desc]
other = "description of panel"

[command.panel.option.role.option.create.option.description.name]
other = "name of panel"

[command.panel.option.role.option.create.option.description.role]
other = "role that add to the panel"

[command.panel.option.role.option.create.option.name]
other = "name"

[command.panel.option.role.option.create.option.role]
other = "role"

[command.panel.option.role.option.description.create]
other = "create role panel"

[command.unban.description]
other = "pardon the selected user"

[command.unban.message]
other = "{{.Target}} byl odblokován"

[command.unban.option.description.target]
other = "odblokovat uživatele"

[command.unban.option.target]
other = "target"

[error.0]
other = "Došlo k chybě {{.Error}}"

[error.TargetIsBot]
other = "Tohoto bota nelze vybrat jako cíl!"

[error.message]
other = "Došlo k chybě"
