[command.ban.description]
other = "bandlyse den valgte bruger"

[command.ban.option.target]
other = "target"

[command.ban.option.description.target]
other = "bruger til at bandlyse"

[command.ban.option.description.reason]
other = "grund til forbud"

[command.ban.option.reason]
other = "årsag"

[command.ban.message]
other = "{{.Target}} er blevet udelukket"

[command.ban.reason]
one = "Årsag: {{.Reason}}"
other = "Årsager: {{.Reason}}"

[command.kick.description]
other = "kick den valgte bruger"

[command.kick.option.target]
other = "target"

[command.kick.option.description.target]
other = "bruger der skal sparke"

[command.kick.message]
other = "{{.Target}} er blevet smidt ud"

[command.unban.description]
other = "pardon the selected user"

[command.unban.option.target]
other = "target"

[command.unban.option.description.target]
other = "bruger til at fjerne udelukkelse"

[command.unban.message]
other = "{{.Target}} er blevet fjernet"

[error.0]
other = "Der opstod en fejl {{.Error}}"

[error.TargetIsBot]
other = "Kan ikke vælge denne bot som mål!"

[error.message]
other = "Der opstod en fejl"
