[command.ban.description]
other = "bandlyse den valgte bruger"

[command.ban.message]
other = "{{.Target}} er blevet udelukket"

[command.ban.option.description.reason]
other = "grund til forbud"

[command.ban.option.description.target]
other = "bruger til at bandlyse"

[command.ban.option.reason]
other = "årsag"

[command.ban.option.target]
other = "target"

[command.ban.reason]
one = "Årsag: {{.Reason}}"
other = "Årsager: {{.Reason}}"

[command.kick.description]
other = "kick den valgte bruger"

[command.kick.message]
other = "{{.Target}} er blevet smidt ud"

[command.kick.option.description.target]
other = "bruger der skal sparke"

[command.kick.option.target]
other = "target"

[command.panel.description]
other = "manage or create panel"

[command.panel.option.description.role]
other = "manage role panel"

[command.panel.option.role]
other = "role"

[command.panel.option.role.option.crate.option.desc]
other = "description"

[command.panel.option.role.option.create]
other = "create"

[command.panel.option.role.option.create.option.description.desc]
other = "description of panel"

[command.panel.option.role.option.create.option.description.name]
other = "name of panel"

[command.panel.option.role.option.create.option.description.role]
other = "role that add to the panel"

[command.panel.option.role.option.create.option.name]
other = "name"

[command.panel.option.role.option.create.option.role]
other = "role"

[command.panel.option.role.option.description.create]
other = "create role panel"

[command.unban.description]
other = "pardon the selected user"

[command.unban.message]
other = "{{.Target}} er blevet fjernet"

[command.unban.option.description.target]
other = "bruger til at fjerne udelukkelse"

[command.unban.option.target]
other = "target"

[error.0]
other = "Der opstod en fejl {{.Error}}"

[error.TargetIsBot]
other = "Kan ikke vælge denne bot som mål!"

[error.message]
other = "Der opstod en fejl"
