[address]
other = "address"

[command_ban_desc]
other = "den ausgewählten Benutzer bannen"

[command_ban_message]
other = "{{.Target}} wurde gebannt"

[command_ban_option_desc_reason]
other = "Grund für Bann"

[command_ban_option_desc_target]
other = "gebannter Benutzer"

[command_ban_option_reason]
other = "Grund"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Grund: {{.Reason}}"
other = "Gründe: {{.Reason}}"

[command_kick_desc]
other = "den ausgewählten Benutzer kicken"

[command_kick_message]
other = "{{.Target}} wurde gekickt"

[command_kick_option_desc_target]
other = "Benutzer zum kicken"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "verwalten oder Panel erstellen"

[command_panel_option_desc_role]
other = "verwalte Rollen"

[command_panel_option_minecraft]
other = "minecraft"

[command_panel_option_minecraft_desc]
other = "manage minecraft panel"

[command_panel_option_minecraft_option_create]
other = "create"

[command_panel_option_minecraft_option_create_desc]
other = "create minecraft panel"

[command_panel_option_minecraft_option_create_option_address]
other = "address"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "address of server"

[command_panel_option_minecraft_option_create_option_description]
other = "description"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "description of panel"

[command_panel_option_minecraft_option_create_option_name]
other = "name"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "name of panel"

[command_panel_option_minecraft_option_create_option_port]
other = "port"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "port of server"

[command_panel_option_minecraft_option_create_option_servername]
other = "servername"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "name of server"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "show ip or not"

[command_panel_option_role]
other = "rolle"

[command_panel_option_role_option_create]
other = "erstellen"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "desc des Panels"

[command_panel_option_role_option_create_option_desc_name]
other = "Name des Panels"

[command_panel_option_role_option_create_option_desc_role]
other = "Rolle, die dem Panel hinzugefügt wird"

[command_panel_option_role_option_create_option_name]
other = "name"

[command_panel_option_role_option_create_option_role]
other = "rolle"

[command_panel_option_role_option_desc_create]
other = "erstelle Rollen-Panel"

[command_tracker]
other = "tracker"

[command_tracker_desc]
other = "manage or create tracker"

[command_tracker_option_minecraft]
other = "minecraft"

[command_tracker_option_minecraft_desc]
other = "manage minecraft server tracker"

[command_tracker_option_minecraft_option_create]
other = "create"

[command_tracker_option_minecraft_option_create_desc]
other = "minecraft server tracker"

[command_tracker_option_minecraft_option_create_option_address]
other = "address"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "address of server"

[command_tracker_option_minecraft_option_create_option_name]
other = "name"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "name of server"

[command_tracker_option_minecraft_option_create_option_port]
other = "port"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "port of server"

[command_tracker_option_minecraft_option_create_option_role]
other = "role"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "role to mention"

[command_unban_desc]
other = "den ausgewählten Benutzer entbannen"

[command_unban_message]
other = "{{.Target}} wurde entbannt"

[command_unban_option_desc_target]
other = "entbannen"

[command_unban_option_target]
other = "target"

[error]
other = "{{.Error}}"

[error_0]
other = "Ein Fehler ist aufgetreten {{.Error}}"

[error_TargetIsBot]
other = "Dieser Bot kann nicht als Ziel ausgewählt werden!"

[error_failed_to_connect_api]
other = "failed to connect api server error"

[error_failed_to_ping_server]
other = "failed to ping server"

[error_invalid_port_value]
other = "invalid port value"

[error_message]
other = "Ein Fehler ist aufgetreten"

[feed_minecraft_webhook_name]
other = "server notifier"

[latency]
other = "latency"

[message_command_modify]
other = "modify"

[panel_minecraft_message_boot]
other = "booted {{.Name}} server"

[panel_minecraft_message_stop]
other = "stopped {{.Name}} server"

[panel_role_message_added]
other = "added"

[panel_role_message_removed]
other = "removed"

[players]
other = "players"

[port]
other = "port"

[version]
other = "version"
