command = { }
command_ban = { }
command_ban_option = { }
command_ban_option_desc = { }
command_kick = { }
command_kick_option = { }
command_kick_option_desc = { }
command_panel = { }
command_panel_option = { }
command_panel_option_desc = { }
command_panel_option_role_option_create_option = { }
command_panel_option_role_option_desc = { }
command_unban = { }
command_unban_option = { }
command_unban_option_desc = { }
error = { }

[command_ban_desc]
other = "den ausgewählten Benutzer bannen"

[command_ban_message]
other = "{{.Target}} wurde gebannt"

[command_ban_option_desc_reason]
other = "Grund für Bann"

[command_ban_option_desc_target]
other = "gebannter Benutzer"

[command_ban_option_reason]
other = "Grund"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Grund: {{.Reason}}"
other = "Gründe: {{.Reason}}"

[command_kick_desc]
other = "den ausgewählten Benutzer kicken"

[command_kick_message]
other = "{{.Target}} wurde gekickt"

[command_kick_option_desc_target]
other = "Benutzer zum kicken"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "verwalten oder Panel erstellen"

[command_panel_option_desc_role]
other = "verwalte Rollen"

[command_panel_option_role]
other = "rolle"

[command_panel_option_role_option_create]
other = "erstellen"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "desc des Panels"

[command_panel_option_role_option_create_option_desc_name]
other = "Name des Panels"

[command_panel_option_role_option_create_option_desc_role]
other = "Rolle, die dem Panel hinzugefügt wird"

[command_panel_option_role_option_create_option_name]
other = "name"

[command_panel_option_role_option_create_option_role]
other = "rolle"

[command_panel_option_role_option_desc_create]
other = "erstelle Rollen-Panel"

[command_unban_desc]
other = "den ausgewählten Benutzer entbannen"

[command_unban_message]
other = "{{.Target}} wurde entbannt"

[command_unban_option_desc_target]
other = "entbannen"

[command_unban_option_target]
other = "target"

[error_0]
other = "Ein Fehler ist aufgetreten {{.Error}}"

[error_TargetIsBot]
other = "Dieser Bot kann nicht als Ziel ausgewählt werden!"

[error_message]
other = "Ein Fehler ist aufgetreten"
