[command.ban.description]
other = "den ausgewählten Benutzer bannen"

[command.ban.option.target]
other = "target"

[command.ban.option.description.target]
other = "gebannter Benutzer"

[command.ban.option.description.reason]
other = "Grund für Bann"

[command.ban.option.reason]
other = "grund"

[command.ban.message]
other = "{{.Target}} wurde gebannt"

[command.ban.reason]
one = "Grund: {{.Reason}}"
other = "Gründe: {{.Reason}}"

[command.kick.description]
other = "den ausgewählten Benutzer kicken"

[command.kick.option.target]
other = "target"

[command.kick.option.description.target]
other = "Benutzer zum kicken"

[command.kick.message]
other = "{{.Target}} wurde gekickt"

[command.unban.description]
other = "pardon the selected user"

[command.unban.option.target]
other = "target"

[command.unban.option.description.target]
other = "entbannen"

[command.unban.message]
other = "{{.Target}} wurde entbannt"

[error.0]
other = "Ein Fehler ist aufgetreten {{.Error}}"

[error.TargetIsBot]
other = "Dieser Bot kann nicht als Ziel ausgewählt werden!"

[error.message]
other = "Ein Fehler ist aufgetreten"
