[command.ban.description]
other = "den ausgewählten Benutzer bannen"

[command.ban.message]
other = "{{.Target}} wurde gebannt"

[command.ban.option.description.reason]
other = "Grund für Bann"

[command.ban.option.description.target]
other = "gebannter Benutzer"

[command.ban.option.reason]
other = "grund"

[command.ban.option.target]
other = "target"

[command.ban.reason]
one = "Grund: {{.Reason}}"
other = "Gründe: {{.Reason}}"

[command.kick.description]
other = "den ausgewählten Benutzer kicken"

[command.kick.message]
other = "{{.Target}} wurde gekickt"

[command.kick.option.description.target]
other = "Benutzer zum kicken"

[command.kick.option.target]
other = "target"

[command.panel.description]
other = "manage or create panel"

[command.panel.option.description.role]
other = "manage role panel"

[command.panel.option.role]
other = "role"

[command.panel.option.role.option.crate.option.desc]
other = "description"

[command.panel.option.role.option.create]
other = "create"

[command.panel.option.role.option.create.option.description.desc]
other = "description of panel"

[command.panel.option.role.option.create.option.description.name]
other = "name of panel"

[command.panel.option.role.option.create.option.description.role]
other = "role that add to the panel"

[command.panel.option.role.option.create.option.name]
other = "name"

[command.panel.option.role.option.create.option.role]
other = "role"

[command.panel.option.role.option.description.create]
other = "create role panel"

[command.unban.description]
other = "pardon the selected user"

[command.unban.message]
other = "{{.Target}} wurde entbannt"

[command.unban.option.description.target]
other = "entbannen"

[command.unban.option.target]
other = "target"

[error.0]
other = "Ein Fehler ist aufgetreten {{.Error}}"

[error.TargetIsBot]
other = "Dieser Bot kann nicht als Ziel ausgewählt werden!"

[error.message]
other = "Ein Fehler ist aufgetreten"
