[command.ban.description]
other = "απαγόρευση του επιλεγμένου χρήστη"

[command.ban.message]
other = "{{.Target}} έχει αποκλειστεί"

[command.ban.option.description.reason]
other = "λόγος απαγόρευσης"

[command.ban.option.description.target]
other = "χρήστης να απαγορεύσει"

[command.ban.option.reason]
other = "λόγος"

[command.ban.option.target]
other = "target"

[command.ban.reason]
one = "Αιτία: {{.Reason}}"
other = "Λόγοι: {{.Reason}}"

[command.kick.description]
other = "κλώτσησε τον επιλεγμένο χρήστη"

[command.kick.message]
other = "{{.Target}} έχει διώξει"

[command.kick.option.description.target]
other = "χρήστης για να κλωτσήσει"

[command.kick.option.target]
other = "target"

[command.panel.description]
other = "manage or create panel"

[command.panel.option.description.role]
other = "manage role panel"

[command.panel.option.role]
other = "role"

[command.panel.option.role.option.crate.option.desc]
other = "description"

[command.panel.option.role.option.create]
other = "create"

[command.panel.option.role.option.create.option.description.desc]
other = "description of panel"

[command.panel.option.role.option.create.option.description.name]
other = "name of panel"

[command.panel.option.role.option.create.option.description.role]
other = "role that add to the panel"

[command.panel.option.role.option.create.option.name]
other = "name"

[command.panel.option.role.option.create.option.role]
other = "role"

[command.panel.option.role.option.description.create]
other = "create role panel"

[command.unban.description]
other = "pardon the selected user"

[command.unban.message]
other = "{{.Target}} έχει καταργηθεί"

[command.unban.option.description.target]
other = "χρήστης για κατάργηση αποκλεισμού"

[command.unban.option.target]
other = "target"

[error.0]
other = "Παρουσιάστηκε ένα σφάλμα {{.Error}}"

[error.TargetIsBot]
other = "Δεν μπορείτε να επιλέξετε αυτό το bot ως στόχο!"

[error.message]
other = "Παρουσιάστηκε ένα σφάλμα"
