[command]
[command.ban]
[command.ban.description]
other = "ban the selected user"
[command.ban.option.target]
other = "target"
[command.ban.option.description.target]
other = "user to ban"
[command.ban.option.reason]
other = "reason"
[command.ban.option.description.reason]
other = "reason for ban"
[command.ban.message]
other = "{{.Target}} has been banned"
[command.ban.reason]
one = "Reason: {{.Reason}}"
other = "Reasons: {{.Reason}}"
[command.kick]
[command.kick.description]
other = "kick the selected user"
[command.kick.option.target]
other = "target"
[command.kick.option.description.target]
other = "user to kick"
[command.kick.message]
other = "{{.Target}} has been kicked"
[command.unban]
[command.unban.description]
other = "unban the selected user"
[command.unban.option.target]
other = "target"
[command.unban.option.description.target]
other = "user to unban"
[command.unban.message]
other = "{{.Target}} has been unbanned"
[error]
[error.'0']
other = "An error has occurred {{.Error}}"
[error.TargetIsBot]
other = "Cannot select this bot as target!"
[error.message]
other = "An error has occurred"
