[command]
[command_ban]
[command_ban_desc]
other = "ban the selected user"
[command_ban_message]
other = "{{.Target}} has been banned"
[command_ban_option]
[command_ban_option_desc]
[command_ban_option_desc_reason]
other = "reason for ban"
[command_ban_option_desc_target]
other = "user to ban"
[command_ban_option_reason]
other = "reason"
[command_ban_option_target]
other = "target"
[command_ban_reason]
one = "Reason: {{.Reason}}"
other = "Reasons: {{.Reason}}"
[command_kick]
[command_kick_desc]
other = "kick the selected user"
[command_kick_message]
other = "{{.Target}} has been kicked"
[command_kick_option]
[command_kick_option_desc]
[command_kick_option_desc_target]
other = "user to kick"
[command_kick_option_target]
other = "target"
[command_panel]
[command_panel_desc]
other = "manage or create panel"
[command_panel_option]
[command_panel_option_desc]
[command_panel_option_desc_role]
other = "manage role panel"
[command_panel_option_role]
other = "role"
[command_panel_option_role_option_create]
other = "create"
[command_panel_option_role_option_create_option]
[command_panel_option_role_option_create_option_desc]
other = "desc"
[command_panel_option_role_option_create_option_desc_desc]
other = "desc of panel"
[command_panel_option_role_option_create_option_desc_name]
other = "name of panel"
[command_panel_option_role_option_create_option_desc_role]
other = "role that add to the panel"
[command_panel_option_role_option_create_option_name]
other = "name"
[command_panel_option_role_option_create_option_role]
other = "role"
[command_panel_option_role_option_desc]
[command_panel_option_role_option_desc_create]
other = "create role panel"
[command_unban]
[command_unban_desc]
other = "unban the selected user"
[command_unban_message]
other = "{{.Target}} has been unbanned"
[command_unban_option]
[command_unban_option_desc]
[command_unban_option_desc_target]
other = "user to unban"
[command_unban_option_target]
other = "target"
[error]
[error_0]
other = "An error has occurred {{.Error}}"
[error_TargetIsBot]
other = "Cannot select this bot as target!"
[error_message]
other = "An error has occurred"
