[command]
[command.ban]
[command.ban.description]
other = "ban the selected user"
[command.ban.message]
other = "{{.Target}} has been banned"
[command.ban.option]
[command.ban.option.description]
[command.ban.option.description.reason]
other = "reason for ban"
[command.ban.option.description.target]
other = "user to ban"
[command.ban.option.reason]
other = "reason"
[command.ban.option.target]
other = "target"
[command.ban.reason]
one = "Reason: {{.Reason}}"
other = "Reasons: {{.Reason}}"
[command.kick]
[command.kick.description]
other = "kick the selected user"
[command.kick.message]
other = "{{.Target}} has been kicked"
[command.kick.option]
[command.kick.option.description]
[command.kick.option.description.target]
other = "user to kick"
[command.kick.option.target]
other = "target"
[command.panel]
[command.panel.description]
other = "manage or create panel"
[command.panel.option]
[command.panel.option.description]
[command.panel.option.description.role]
other = "manage role panel"
[command.panel.option.role]
other = "role"
[command.panel.option.role.option]
[command.panel.option.role.option.crate]
[command.panel.option.role.option.crate.option]
[command.panel.option.role.option.crate.option.desc]
other = "description"
[command.panel.option.role.option.create]
other = "create"
[command.panel.option.role.option.create.option]
[command.panel.option.role.option.create.option.description]
[command.panel.option.role.option.create.option.description.desc]
other = "description of panel"
[command.panel.option.role.option.create.option.description.name]
other = "name of panel"
[command.panel.option.role.option.create.option.description.role]
other = "role that add to the panel"
[command.panel.option.role.option.create.option.name]
other = "name"
[command.panel.option.role.option.create.option.role]
other = "role"
[command.panel.option.role.option.description]
[command.panel.option.role.option.description.create]
other = "create role panel"
[command.unban]
[command.unban.description]
other = "unban the selected user"
[command.unban.message]
other = "{{.Target}} has been unbanned"
[command.unban.option]
[command.unban.option.description]
[command.unban.option.description.target]
other = "user to unban"
[command.unban.option.target]
other = "target"
[error]
[error.'0']
other = "An error has occurred {{.Error}}"
[error.TargetIsBot]
other = "Cannot select this bot as target!"
[error.message]
other = "An error has occurred"
