[command.ban.description]
other = "banear al usuario seleccionado"

[command.ban.message]
other = "{{.Target}} ha sido baneado"

[command.ban.option.description.reason]
other = "razón para banear"

[command.ban.option.description.target]
other = "usuario a banear"

[command.ban.option.reason]
other = "razón"

[command.ban.option.target]
other = "target"

[command.ban.reason]
one = "Razón: {{.Reason}}"
other = "Razones: {{.Reason}}"

[command.kick.description]
other = "expulsar al usuario seleccionado"

[command.kick.message]
other = "{{.Target}} ha sido expulsado"

[command.kick.option.description.target]
other = "usuario a expulsar"

[command.kick.option.target]
other = "target"

[command.panel.description]
other = "administrar o crear panel"

[command.panel.option.description.role]
other = "administrar panel de roles"

[command.panel.option.role]
other = "rol"

[command.panel.option.role.option.crate.option.desc]
other = "descripción"

[command.panel.option.role.option.create]
other = "crear"

[command.panel.option.role.option.create.option.description.desc]
other = "descripción del panel"

[command.panel.option.role.option.create.option.description.name]
other = "nombre del panel"

[command.panel.option.role.option.create.option.description.role]
other = "rol que añade al panel"

[command.panel.option.role.option.create.option.name]
other = "nombre"

[command.panel.option.role.option.create.option.role]
other = "rol"

[command.panel.option.role.option.description.create]
other = "crear panel de roles"

[command.unban.description]
other = "pardon the selected user"

[command.unban.message]
other = "{{.Target}} ha sido desbaneado"

[command.unban.option.description.target]
other = "usuario a desbanear"

[command.unban.option.target]
other = "target"

[error.0]
other = "Ha ocurrido un error {{.Error}}"

[error.TargetIsBot]
other = "¡No se puede seleccionar este bot como objetivo!"

[error.message]
other = "Ha ocurrido un error"
