command = { }
command_ban = { }
command_ban_option = { }
command_ban_option_desc = { }
command_kick = { }
command_kick_option = { }
command_kick_option_desc = { }
command_panel = { }
command_panel_option = { }
command_panel_option_desc = { }
command_panel_option_role_option_create_option = { }
command_panel_option_role_option_desc = { }
command_unban = { }
command_unban_option = { }
command_unban_option_desc = { }
error = { }

[command_ban_desc]
other = "banear al usuario seleccionado"

[command_ban_message]
other = "{{.Target}} ha sido baneado"

[command_ban_option_desc_reason]
other = "razón para banear"

[command_ban_option_desc_target]
other = "usuario a banear"

[command_ban_option_reason]
other = "razón"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Razón: {{.Reason}}"
other = "Razones: {{.Reason}}"

[command_kick_desc]
other = "expulsar al usuario seleccionado"

[command_kick_message]
other = "{{.Target}} ha sido expulsado"

[command_kick_option_desc_target]
other = "usuario a expulsar"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "administrar o crear panel"

[command_panel_option_desc_role]
other = "administrar panel de roles"

[command_panel_option_role]
other = "rol"

[command_panel_option_role_option_create]
other = "crear"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "desc del panel"

[command_panel_option_role_option_create_option_desc_name]
other = "nombre del panel"

[command_panel_option_role_option_create_option_desc_role]
other = "rol que añade al panel"

[command_panel_option_role_option_create_option_name]
other = "nombre"

[command_panel_option_role_option_create_option_role]
other = "rol"

[command_panel_option_role_option_desc_create]
other = "crear panel de roles"

[command_unban_desc]
other = "desbanear al usuario seleccionado"

[command_unban_message]
other = "{{.Target}} ha sido desbaneado"

[command_unban_option_desc_target]
other = "usuario a desbanear"

[command_unban_option_target]
other = "target"

[error_0]
other = "Ha ocurrido un error {{.Error}}"

[error_TargetIsBot]
other = "¡No se puede seleccionar este bot como objetivo!"

[error_message]
other = "Ha ocurrido un error"
