[command.ban.description]
other = "banear al usuario seleccionado"

[command.ban.option.target]
other = "target"

[command.ban.option.description.target]
other = "usuario a banear"

[command.ban.option.description.reason]
other = "razón para banear"

[command.ban.option.reason]
other = "razón"

[command.ban.message]
other = "{{.Target}} ha sido baneado"

[command.ban.reason]
one = "Razón: {{.Reason}}"
other = "Razones: {{.Reason}}"

[command.kick.description]
other = "expulsar al usuario seleccionado"

[command.kick.option.target]
other = "target"

[command.kick.option.description.target]
other = "usuario a expulsar"

[command.kick.message]
other = "{{.Target}} ha sido expulsado"

[command.unban.description]
other = "pardon the selected user"

[command.unban.option.target]
other = "target"

[command.unban.option.description.target]
other = "usuario a desbanear"

[command.unban.message]
other = "{{.Target}} ha sido desbaneado"

[error.0]
other = "Ha ocurrido un error {{.Error}}"

[error.TargetIsBot]
other = "¡No se puede seleccionar este bot como objetivo!"

[error.message]
other = "Ha ocurrido un error"
