command = { }
command_ban = { }
command_ban_option = { }
command_ban_option_desc = { }
command_kick = { }
command_kick_option = { }
command_kick_option_desc = { }
command_panel = { }
command_panel_option = { }
command_panel_option_desc = { }
command_panel_option_role_option_create_option = { }
command_panel_option_role_option_desc = { }
command_unban = { }
command_unban_option = { }
command_unban_option_desc = { }
error = { }

[command_ban_desc]
other = "porttikielto valitulle käyttäjälle"

[command_ban_message]
other = "{{.Target}} on estetty"

[command_ban_option_desc_reason]
other = "kiellon syy"

[command_ban_option_desc_target]
other = "käyttäjä jolle porttikielto"

[command_ban_option_reason]
other = "syy"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Syy: {{.Reason}}"
other = "Syyt: {{.Reason}}"

[command_kick_desc]
other = "potkia valittu käyttäjä"

[command_kick_message]
other = "{{.Target}} on potkittu"

[command_kick_option_desc_target]
other = "käyttäjä potkia"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "hallitse tai luo paneeli"

[command_panel_option_desc_role]
other = "hallitse roolipaneelia"

[command_panel_option_role]
other = "rooli"

[command_panel_option_role_option_create]
other = "luo"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "paneelin desc"

[command_panel_option_role_option_create_option_desc_name]
other = "paneelin nimi"

[command_panel_option_role_option_create_option_desc_role]
other = "rooli, joka lisää paneeliin"

[command_panel_option_role_option_create_option_name]
other = "nimi"

[command_panel_option_role_option_create_option_role]
other = "rooli"

[command_panel_option_role_option_desc_create]
other = "luo roolipaneeli"

[command_unban_desc]
other = "poista porttikielto valitulle käyttäjälle"

[command_unban_message]
other = "{{.Target}} on poistettu porttikielto"

[command_unban_option_desc_target]
other = "poista porttikielto"

[command_unban_option_target]
other = "target"

[error_0]
other = "Tapahtui virhe {{.Error}}"

[error_TargetIsBot]
other = "Botti ei voi valita kohteeksi!"

[error_message]
other = "Virhe on tapahtunut"
