[command.ban.description]
other = "porttikielto valitulle käyttäjälle"

[command.ban.message]
other = "{{.Target}} on estetty"

[command.ban.option.description.reason]
other = "kiellon syy"

[command.ban.option.description.target]
other = "käyttäjä jolle porttikielto"

[command.ban.option.reason]
other = "syy"

[command.ban.option.target]
other = "target"

[command.ban.reason]
one = "Syy: {{.Reason}}"
other = "Syyt: {{.Reason}}"

[command.kick.description]
other = "potkia valittu käyttäjä"

[command.kick.message]
other = "{{.Target}} on potkittu"

[command.kick.option.description.target]
other = "käyttäjä potkia"

[command.kick.option.target]
other = "target"

[command.panel.description]
other = "manage or create panel"

[command.panel.option.description.role]
other = "manage role panel"

[command.panel.option.role]
other = "role"

[command.panel.option.role.option.crate.option.desc]
other = "description"

[command.panel.option.role.option.create]
other = "create"

[command.panel.option.role.option.create.option.description.desc]
other = "description of panel"

[command.panel.option.role.option.create.option.description.name]
other = "name of panel"

[command.panel.option.role.option.create.option.description.role]
other = "role that add to the panel"

[command.panel.option.role.option.create.option.name]
other = "name"

[command.panel.option.role.option.create.option.role]
other = "role"

[command.panel.option.role.option.description.create]
other = "create role panel"

[command.unban.description]
other = "pardon the selected user"

[command.unban.message]
other = "{{.Target}} on poistettu porttikielto"

[command.unban.option.description.target]
other = "poista porttikielto"

[command.unban.option.target]
other = "target"

[error.0]
other = "Tapahtui virhe {{.Error}}"

[error.TargetIsBot]
other = "Botti ei voi valita kohteeksi!"

[error.message]
other = "Virhe on tapahtunut"
