[command.ban.description]
other = "porttikielto valitulle käyttäjälle"

[command.ban.option.target]
other = "target"

[command.ban.option.description.target]
other = "käyttäjä jolle porttikielto"

[command.ban.option.description.reason]
other = "kiellon syy"

[command.ban.option.reason]
other = "syy"

[command.ban.message]
other = "{{.Target}} on estetty"

[command.ban.reason]
one = "Syy: {{.Reason}}"
other = "Syyt: {{.Reason}}"

[command.kick.description]
other = "potkia valittu käyttäjä"

[command.kick.option.target]
other = "target"

[command.kick.option.description.target]
other = "käyttäjä potkia"

[command.kick.message]
other = "{{.Target}} on potkittu"

[command.unban.description]
other = "pardon the selected user"

[command.unban.option.target]
other = "target"

[command.unban.option.description.target]
other = "poista porttikielto"

[command.unban.message]
other = "{{.Target}} on poistettu porttikielto"

[error.0]
other = "Tapahtui virhe {{.Error}}"

[error.TargetIsBot]
other = "Botti ei voi valita kohteeksi!"

[error.message]
other = "Virhe on tapahtunut"
