[command.ban.description]
other = "bannir l'utilisateur sélectionné"

[command.ban.option.target]
other = "target"

[command.ban.option.description.target]
other = "utilisateur à bannir"

[command.ban.option.description.reason]
other = "raison du bannissement"

[command.ban.option.reason]
other = "Raison"

[command.ban.message]
other = "{{.Target}} a été banni"

[command.ban.reason]
one = "Raison : {{.Reason}}"
other = "Raisons : {{.Reason}}"

[command.kick.description]
other = "expulser l'utilisateur sélectionné"

[command.kick.option.target]
other = "target"

[command.kick.option.description.target]
other = "utilisateur à expulser"

[command.kick.message]
other = "{{.Target}} a été éjecté"

[command.unban.description]
other = "pardon the selected user"

[command.unban.option.target]
other = "target"

[command.unban.option.description.target]
other = "utilisateur à débannir"

[command.unban.message]
other = "{{.Target}} a été débanni"

[error.0]
other = "Une erreur s'est produite {{.Error}}"

[error.TargetIsBot]
other = "Impossible de sélectionner ce bot comme cible !"

[error.message]
other = "Une erreur est survenue"
