command = { }
command_ban = { }
command_ban_option = { }
command_ban_option_desc = { }
command_kick = { }
command_kick_option = { }
command_kick_option_desc = { }
command_panel = { }
command_panel_option = { }
command_panel_option_desc = { }
command_panel_option_role_option_create_option = { }
command_panel_option_role_option_desc = { }
command_unban = { }
command_unban_option = { }
command_unban_option_desc = { }
error = { }

[command_ban_desc]
other = "bannir l'utilisateur sélectionné"

[command_ban_message]
other = "{{.Target}} a été banni"

[command_ban_option_desc_reason]
other = "raison du bannissement"

[command_ban_option_desc_target]
other = "utilisateur à bannir"

[command_ban_option_reason]
other = "Raison"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Raison : {{.Reason}}"
other = "Raisons : {{.Reason}}"

[command_kick_desc]
other = "expulser l'utilisateur sélectionné"

[command_kick_message]
other = "{{.Target}} a été éjecté"

[command_kick_option_desc_target]
other = "utilisateur à expulser"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "gérer ou créer un panneau"

[command_panel_option_desc_role]
other = "gérer le panneau des rôles"

[command_panel_option_role]
other = "Rôle"

[command_panel_option_role_option_create]
other = "créer"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "desc du panneau"

[command_panel_option_role_option_create_option_desc_name]
other = "nom du panneau"

[command_panel_option_role_option_create_option_desc_role]
other = "rôle qui s'ajoute au panneau"

[command_panel_option_role_option_create_option_name]
other = "Nom"

[command_panel_option_role_option_create_option_role]
other = "Rôle"

[command_panel_option_role_option_desc_create]
other = "créer un panneau de rôle"

[command_unban_desc]
other = "dé-bannir l'utilisateur sélectionné"

[command_unban_message]
other = "{{.Target}} a été débanni"

[command_unban_option_desc_target]
other = "utilisateur à débannir"

[command_unban_option_target]
other = "target"

[error_0]
other = "Une erreur s'est produite {{.Error}}"

[error_TargetIsBot]
other = "Impossible de sélectionner ce bot comme cible !"

[error_message]
other = "Une erreur est survenue"
