[command.ban.description]
other = "bannir l'utilisateur sélectionné"

[command.ban.message]
other = "{{.Target}} a été banni"

[command.ban.option.description.reason]
other = "raison du bannissement"

[command.ban.option.description.target]
other = "utilisateur à bannir"

[command.ban.option.reason]
other = "Raison"

[command.ban.option.target]
other = "target"

[command.ban.reason]
one = "Raison : {{.Reason}}"
other = "Raisons : {{.Reason}}"

[command.kick.description]
other = "expulser l'utilisateur sélectionné"

[command.kick.message]
other = "{{.Target}} a été éjecté"

[command.kick.option.description.target]
other = "utilisateur à expulser"

[command.kick.option.target]
other = "target"

[command.panel.description]
other = "gérer ou créer un panneau"

[command.panel.option.description.role]
other = "gérer le panneau des rôles"

[command.panel.option.role]
other = "Rôle"

[command.panel.option.role.option.crate.option.desc]
other = "Libellé"

[command.panel.option.role.option.create]
other = "créer"

[command.panel.option.role.option.create.option.description.desc]
other = "description du panneau"

[command.panel.option.role.option.create.option.description.name]
other = "nom du panneau"

[command.panel.option.role.option.create.option.description.role]
other = "rôle qui s'ajoute au panneau"

[command.panel.option.role.option.create.option.name]
other = "Nom"

[command.panel.option.role.option.create.option.role]
other = "Rôle"

[command.panel.option.role.option.description.create]
other = "créer un panneau de rôle"

[command.unban.description]
other = "pardon the selected user"

[command.unban.message]
other = "{{.Target}} a été débanni"

[command.unban.option.description.target]
other = "utilisateur à débannir"

[command.unban.option.target]
other = "target"

[error.0]
other = "Une erreur s'est produite {{.Error}}"

[error.TargetIsBot]
other = "Impossible de sélectionner ce bot comme cible !"

[error.message]
other = "Une erreur est survenue"
