[command.ban.description]
other = "bandisce l'utente selezionato"

[command.ban.message]
other = "{{.Target}} è stato bannato"

[command.ban.option.description.reason]
other = "motivo del divieto"

[command.ban.option.description.target]
other = "utente da bandire"

[command.ban.option.reason]
other = "motivo"

[command.ban.option.target]
other = "target"

[command.ban.reason]
one = "Motivo: {{.Reason}}"
other = "Motivi: {{.Reason}}"

[command.kick.description]
other = "espulso l'utente selezionato"

[command.kick.message]
other = "{{.Target}} è stato espulso"

[command.kick.option.description.target]
other = "utente da espellere"

[command.kick.option.target]
other = "target"

[command.panel.description]
other = "gestire o creare un pannello"

[command.panel.option.description.role]
other = "gestire il pannello ruoli"

[command.panel.option.role]
other = "ruolo"

[command.panel.option.role.option.crate.option.desc]
other = "descrizione"

[command.panel.option.role.option.create]
other = "crea"

[command.panel.option.role.option.create.option.description.desc]
other = "descrizione del pannello"

[command.panel.option.role.option.create.option.description.name]
other = "nome del pannello"

[command.panel.option.role.option.create.option.description.role]
other = "ruolo che si aggiunge al pannello"

[command.panel.option.role.option.create.option.name]
other = "nome"

[command.panel.option.role.option.create.option.role]
other = "ruolo"

[command.panel.option.role.option.description.create]
other = "crea pannello ruolo"

[command.unban.description]
other = "pardon the selected user"

[command.unban.message]
other = "{{.Target}} è stato sbannato"

[command.unban.option.description.target]
other = "utente da sbloccare"

[command.unban.option.target]
other = "target"

[error.0]
other = "Si è verificato un errore {{.Error}}"

[error.TargetIsBot]
other = "Non è possibile selezionare questo bot come obiettivo!"

[error.message]
other = "Si è verificato un errore"
