[command.ban.description]
other = "bandisce l'utente selezionato"

[command.ban.option.target]
other = "target"

[command.ban.option.description.target]
other = "utente da bandire"

[command.ban.option.description.reason]
other = "motivo del divieto"

[command.ban.option.reason]
other = "motivo"

[command.ban.message]
other = "{{.Target}} è stato bannato"

[command.ban.reason]
one = "Motivo: {{.Reason}}"
other = "Motivi: {{.Reason}}"

[command.kick.description]
other = "espulso l'utente selezionato"

[command.kick.option.target]
other = "target"

[command.kick.option.description.target]
other = "utente da espellere"

[command.kick.message]
other = "{{.Target}} è stato espulso"

[command.unban.description]
other = "pardon the selected user"

[command.unban.option.target]
other = "target"

[command.unban.option.description.target]
other = "utente da sbloccare"

[command.unban.message]
other = "{{.Target}} è stato sbannato"

[error.0]
other = "Si è verificato un errore {{.Error}}"

[error.TargetIsBot]
other = "Non è possibile selezionare questo bot come obiettivo!"

[error.message]
other = "Si è verificato un errore"
