command = { }
command_ban = { }
command_ban_option = { }
command_ban_option_desc = { }
command_kick = { }
command_kick_option = { }
command_kick_option_desc = { }
command_panel = { }
command_panel_option = { }
command_panel_option_desc = { }
command_panel_option_role_option_create_option = { }
command_panel_option_role_option_desc = { }
command_unban = { }
command_unban_option = { }
command_unban_option_desc = { }
error = { }

[command_ban_desc]
other = "bandisce l'utente selezionato"

[command_ban_message]
other = "{{.Target}} è stato bannato"

[command_ban_option_desc_reason]
other = "motivo del divieto"

[command_ban_option_desc_target]
other = "utente da bandire"

[command_ban_option_reason]
other = "motivo"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Motivo: {{.Reason}}"
other = "Motivi: {{.Reason}}"

[command_kick_desc]
other = "espulso l'utente selezionato"

[command_kick_message]
other = "{{.Target}} è stato espulso"

[command_kick_option_desc_target]
other = "utente da espellere"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "gestire o creare un pannello"

[command_panel_option_desc_role]
other = "gestire il pannello ruoli"

[command_panel_option_role]
other = "ruolo"

[command_panel_option_role_option_create]
other = "crea"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "desc del pannello"

[command_panel_option_role_option_create_option_desc_name]
other = "nome del pannello"

[command_panel_option_role_option_create_option_desc_role]
other = "ruolo che si aggiunge al pannello"

[command_panel_option_role_option_create_option_name]
other = "nome"

[command_panel_option_role_option_create_option_role]
other = "ruolo"

[command_panel_option_role_option_desc_create]
other = "crea pannello ruolo"

[command_unban_desc]
other = "disattiva l'utente selezionato"

[command_unban_message]
other = "{{.Target}} è stato sbannato"

[command_unban_option_desc_target]
other = "utente da sbloccare"

[command_unban_option_target]
other = "target"

[error_0]
other = "Si è verificato un errore {{.Error}}"

[error_TargetIsBot]
other = "Non è possibile selezionare questo bot come obiettivo!"

[error_message]
other = "Si è verificato un errore"
