[command.ban.description]
other = "選択したユーザーをBANします"

[command.ban.message]
other = "{{.Target}}をbanしました"

[command.ban.option.description.reason]
other = "banした理由"

[command.ban.option.description.target]
other = "ユーザーをBANします"

[command.ban.option.reason]
other = "理由"

[command.ban.option.target]
other = "ターゲット"

[command.ban.reason]
one = "理由： {{.Reason}}"
other = "理由： {{.Reason}}"

[command.kick.description]
other = "選択したユーザーをキックします"

[command.kick.message]
other = "{{.Target}}をキックしました"

[command.kick.option.description.target]
other = "キックするユーザー"

[command.kick.option.target]
other = "ターゲット"

[command.panel.description]
other = "manage or create panel"

[command.panel.option.description.role]
other = "manage role panel"

[command.panel.option.role]
other = "role"

[command.panel.option.role.option.crate.option.desc]
other = "description"

[command.panel.option.role.option.create]
other = "create"

[command.panel.option.role.option.create.option.description.desc]
other = "description of panel"

[command.panel.option.role.option.create.option.description.name]
other = "name of panel"

[command.panel.option.role.option.create.option.description.role]
other = "role that add to the panel"

[command.panel.option.role.option.create.option.name]
other = "name"

[command.panel.option.role.option.create.option.role]
other = "role"

[command.panel.option.role.option.description.create]
other = "create role panel"

[command.unban.description]
other = "banを解除するユーザーを選択します"

[command.unban.message]
other = "{{.Target}}のbanを解除しました"

[command.unban.option.description.target]
other = "banを解除したいユーザー"

[command.unban.option.target]
other = "ターゲット"

[error.0]
other = "エラーが発生しました： {{.Error}}"

[error.TargetIsBot]
other = "このボットをターゲットとして選択できません！"

[error.message]
other = "エラーが発生しました"
