[command.ban.description]
other = "ban the selected user"

[command.ban.message]
other = "{{.Target}}をbanしました"

[command.ban.option.reason]
other = "reason"

  [command.ban.option.reason.description]
  other = "reason for ban"

[command.ban.option.target]
other = "target"

  [command.ban.option.target.description]
  other = "user to ban"

[command.ban.reason]
one = "理由： {{.Reason}}"
other = "理由： {{.Reason}}"

[command.kick.description]
other = "kick the selected user"

[command.kick.message]
other = "{{.Target}}をキックしました"

[command.kick.option.target]
other = "target"

  [command.kick.option.target.description]
  other = "user to kick"

[command.unban.description]
other = "pardon the selected user"

[command.unban.message]
other = "{{.Target}}のbanを解除しました"

[command.unban.option.target]
other = "target"

  [command.unban.option.target.description]
  other = "user to unban"

[error.0]
other = "エラーが発生しました： {{.Error}}"

[error.TargetIsBot]
other = "このボットをターゲットとして選択できません！"

[error.message]
other = "エラーが発生しました"
