[command.ban.reason]
one = "理由： {{.Reason}}"
other = "理由： {{.Reason}}"

[command.ban.message]
other = "{{.Target}}をbanしました"

[command.kick.message]
other = "{{.Target}}をキックしました"

[command.unban.message]
other = "{{.Target}}のbanを解除しました"

[error.0]
other = "エラーが発生しました： {{.Error}}"

[error.message]
other = "エラーが発生しました"

[error.TargetIsBot]
other = "このボットをターゲットとして選択できません！"
