[command.ban.description]
other = "選択したユーザーをBANします"

[command.ban.message]
other = "{{.Target}}をbanしました"

[command.ban.option.description.reason]
other = "banした理由"

[command.ban.option.description.target]
other = "ユーザーをBANします"

[command.ban.option.reason]
other = "理由"

[command.ban.option.target]
other = "ターゲット"

[command.ban.reason]
one = "理由： {{.Reason}}"
other = "理由： {{.Reason}}"

[command.kick.description]
other = "選択したユーザーをキックします"

[command.kick.message]
other = "{{.Target}}をキックしました"

[command.kick.option.description.target]
other = "キックするユーザー"

[command.kick.option.target]
other = "ターゲット"

[command.panel.description]
other = "管理またはパネルの作成"

[command.panel.option.description.role]
other = "役割パネルの管理"

[command.panel.option.role]
other = "ロール"

[command.panel.option.role.option.crate.option.desc]
other = "説明"

[command.panel.option.role.option.create]
other = "作成"

[command.panel.option.role.option.create.option.description.desc]
other = "パネルの説明"

[command.panel.option.role.option.create.option.description.name]
other = "パネル名"

[command.panel.option.role.option.create.option.description.role]
other = "パネルに追加するロール"

[command.panel.option.role.option.create.option.name]
other = "名前"

[command.panel.option.role.option.create.option.role]
other = "ロール"

[command.panel.option.role.option.description.create]
other = "役割パネルを作成"

[command.unban.description]
other = "banを解除するユーザーを選択します"

[command.unban.message]
other = "{{.Target}}のbanを解除しました"

[command.unban.option.description.target]
other = "banを解除したいユーザー"

[command.unban.option.target]
other = "ターゲット"

[error.0]
other = "エラーが発生しました： {{.Error}}"

[error.TargetIsBot]
other = "このボットをターゲットとして選択できません！"

[error.message]
other = "エラーが発生しました"
