[address]
other = "address"

[command_ban_desc]
other = "選択したユーザーをBANします"

[command_ban_message]
other = "{{.Target}} はBANされました"

[command_ban_option_desc_reason]
other = "BANの理由"

[command_ban_option_desc_target]
other = "禁止するユーザー"

[command_ban_option_reason]
other = "理由"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "理由: {{.Reason}}"
other = "理由: {{.Reason}}"

[command_kick_desc]
other = "選択したユーザーをキックする"

[command_kick_message]
other = "{{.Target}} がキックされました"

[command_kick_option_desc_target]
other = "キックするユーザー"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "管理またはパネルの作成"

[command_panel_option_desc_role]
other = "役割パネルの管理"

[command_panel_option_minecraft]
other = "minecraft"

[command_panel_option_minecraft_desc]
other = "manage minecraft panel"

[command_panel_option_minecraft_option_create]
other = "create"

[command_panel_option_minecraft_option_create_desc]
other = "create minecraft panel"

[command_panel_option_minecraft_option_create_option_address]
other = "address"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "address of server"

[command_panel_option_minecraft_option_create_option_description]
other = "description"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "description of panel"

[command_panel_option_minecraft_option_create_option_name]
other = "name"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "name of panel"

[command_panel_option_minecraft_option_create_option_port]
other = "port"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "port of server"

[command_panel_option_minecraft_option_create_option_servername]
other = "servername"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "name of server"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "show ip or not"

[command_panel_option_role]
other = "ロール"

[command_panel_option_role_option_create]
other = "作成"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "パネルのdesc"

[command_panel_option_role_option_create_option_desc_name]
other = "パネル名"

[command_panel_option_role_option_create_option_desc_role]
other = "パネルに追加するロール"

[command_panel_option_role_option_create_option_name]
other = "名前"

[command_panel_option_role_option_create_option_role]
other = "ロール"

[command_panel_option_role_option_desc_create]
other = "役割パネルを作成"

[command_tracker]
other = "tracker"

[command_tracker_desc]
other = "manage or create tracker"

[command_tracker_option_minecraft]
other = "minecraft"

[command_tracker_option_minecraft_desc]
other = "manage minecraft server tracker"

[command_tracker_option_minecraft_option_create]
other = "create"

[command_tracker_option_minecraft_option_create_desc]
other = "minecraft server tracker"

[command_tracker_option_minecraft_option_create_option_address]
other = "address"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "address of server"

[command_tracker_option_minecraft_option_create_option_name]
other = "name"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "name of server"

[command_tracker_option_minecraft_option_create_option_port]
other = "port"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "port of server"

[command_tracker_option_minecraft_option_create_option_role]
other = "role"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "role to mention"

[command_unban_desc]
other = "選択した利用者のBANを解除"

[command_unban_message]
other = "{{.Target}} のBANが解除されました"

[command_unban_option_desc_target]
other = "BANを解除するユーザー"

[command_unban_option_target]
other = "ターゲット"

[error]
other = "{{.Error}}"

[error_0]
other = "エラーが発生しました {{.Error}}"

[error_TargetIsBot]
other = "このボットをターゲットとして選択できません！"

[error_failed_to_connect_api]
other = "failed to connect api server error"

[error_failed_to_ping_server]
other = "failed to ping server"

[error_invalid_port_value]
other = "invalid port value"

[error_message]
other = "エラーが発生しました"

[feed_minecraft_webhook_name]
other = "server notifier"

[latency]
other = "latency"

[message_command_modify]
other = "modify"

[panel_minecraft_message_boot]
other = "booted {{.Name}} server"

[panel_minecraft_message_stop]
other = "stopped {{.Name}} server"

[panel_role_message_added]
other = "added"

[panel_role_message_removed]
other = "removed"

[players]
other = "players"

[port]
other = "port"

[version]
other = "version"
