[address]
other = "アドレス"

[command_ban_desc]
other = "選択したユーザーをBANします"

[command_ban_message]
other = "{{.Target}} はBANされました"

[command_ban_option_desc_reason]
other = "banの理由"

[command_ban_option_desc_target]
other = "禁止するユーザー"

[command_ban_option_reason]
other = "理由"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "理由: {{.Reason}}"
other = "理由: {{.Reason}}"

[command_kick_desc]
other = "選択したユーザーをキックする"

[command_kick_message]
other = "{{.Target}} がキックされました"

[command_kick_option_desc_target]
other = "キックするユーザー"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "管理またはパネルの作成"

[command_panel_option_desc_role]
other = "役割パネルの管理"

[command_panel_option_minecraft]
other = "Minecraft"

[command_panel_option_minecraft_desc]
other = "Minecraftパネルを管理"

[command_panel_option_minecraft_option_create]
other = "作成"

[command_panel_option_minecraft_option_create_desc]
other = "Minecraftパネルを作成"

[command_panel_option_minecraft_option_create_option_address]
other = "アドレス"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "サーバーのアドレス"

[command_panel_option_minecraft_option_create_option_description]
other = "説明"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "パネルの説明"

[command_panel_option_minecraft_option_create_option_name]
other = "名前"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "パネル名"

[command_panel_option_minecraft_option_create_option_port]
other = "ポート"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "サーバーのポート"

[command_panel_option_minecraft_option_create_option_servername]
other = "サーバー名"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "サーバー名"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "IPを表示するかどうか"

[command_panel_option_role]
other = "ロール"

[command_panel_option_role_option_create]
other = "作成"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "パネルのdesc"

[command_panel_option_role_option_create_option_desc_name]
other = "パネル名"

[command_panel_option_role_option_create_option_desc_role]
other = "パネルに追加するロール"

[command_panel_option_role_option_create_option_name]
other = "名前"

[command_panel_option_role_option_create_option_role]
other = "ロール"

[command_panel_option_role_option_desc_create]
other = "役割パネルを作成"

[command_tracker]
other = "トラッカー"

[command_tracker_desc]
other = "トラッカーを管理または作成する"

[command_tracker_option_minecraft]
other = "Minecraft"

[command_tracker_option_minecraft_desc]
other = "Minecraftサーバートラッカーを管理する"

[command_tracker_option_minecraft_option_create]
other = "作成"

[command_tracker_option_minecraft_option_create_desc]
other = "Minecraftサーバートラッカー"

[command_tracker_option_minecraft_option_create_option_address]
other = "アドレス"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "サーバーのアドレス"

[command_tracker_option_minecraft_option_create_option_name]
other = "名前"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "サーバー名"

[command_tracker_option_minecraft_option_create_option_port]
other = "ポート"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "サーバーのポート"

[command_tracker_option_minecraft_option_create_option_role]
other = "ロール"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "メンションするロール"

[command_unban_desc]
other = "選択した利用者のBANを解除"

[command_unban_message]
other = "{{.Target}} のBANが解除されました"

[command_unban_option_desc_target]
other = "banを解除するユーザー"

[command_unban_option_target]
other = "ターゲット"

[error]
other = "{{.Error}}"

[error_0]
other = "エラーが発生しました {{.Error}}"

[error_TargetIsBot]
other = "このボットをターゲットとして選択できません！"

[error_failed_to_connect_api]
other = "APIサーバーエラーの接続に失敗しました"

[error_failed_to_ping_server]
other = "Pingサーバーに失敗しました"

[error_invalid_port_value]
other = "不正なポート値"

[error_message]
other = "エラーが発生しました"

[feed_minecraft_webhook_name]
other = "サーバ通知"

[latency]
other = "レイテンシー"

[message_command_modify]
other = "変更"

[panel_minecraft_message_boot]
other = "{{.Name}} サーバーを起動しました"

[panel_minecraft_message_stop]
other = "{{.Name}} サーバーを停止しました"

[panel_role_message_added]
other = "追加"

[panel_role_message_removed]
other = "removed"

[players]
other = "プレイヤー"

[port]
other = "ポート"

[version]
other = "バージョン"
