[command.ban.reason]
one = "理由： {{.Reason}}"
other = "理由： {{.Reason}}"

[command.ban.message]
other = "{{.Target}}をbanしました"

[command.kick.message]
other = "{{.Target}} has been kicked"

[command.unban.message]
other = "{{.Target}}のbanを解除しました"

[error.0]
other = "An error has occurred {{.Error}}"

[error.message]
other = "An error has occurred"

[error.TargetIsBot]
other = "このボットをターゲットとして選択できません！"
