command = { }
command_ban = { }
command_ban_option = { }
command_ban_option_desc = { }
command_kick = { }
command_kick_option = { }
command_kick_option_desc = { }
command_panel = { }
command_panel_option = { }
command_panel_option_desc = { }
command_panel_option_role_option_create_option = { }
command_panel_option_role_option_desc = { }
command_unban = { }
command_unban_option = { }
command_unban_option_desc = { }
error = { }

[command_ban_desc]
other = "選択した利用者をBANする"

[command_ban_message]
other = "{{.Target}} はBANされました"

[command_ban_option_desc_reason]
other = "BANの理由"

[command_ban_option_desc_target]
other = "禁止するユーザー"

[command_ban_option_reason]
other = "理由"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "理由: {{.Reason}}"
other = "理由: {{.Reason}}"

[command_kick_desc]
other = "選択したユーザーをキックする"

[command_kick_message]
other = "{{.Target}} がキックされました"

[command_kick_option_desc_target]
other = "キックするユーザー"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "管理またはパネルの作成"

[command_panel_option_desc_role]
other = "役割パネルの管理"

[command_panel_option_role]
other = "ロール"

[command_panel_option_role_option_create]
other = "作成"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "パネルのdesc"

[command_panel_option_role_option_create_option_desc_name]
other = "パネル名"

[command_panel_option_role_option_create_option_desc_role]
other = "パネルに追加するロール"

[command_panel_option_role_option_create_option_name]
other = "名前"

[command_panel_option_role_option_create_option_role]
other = "ロール"

[command_panel_option_role_option_desc_create]
other = "役割パネルを作成"

[command_unban_desc]
other = "選択した利用者のBANを解除"

[command_unban_message]
other = "{{.Target}} のBANが解除されました"

[command_unban_option_desc_target]
other = "BANを解除するユーザー"

[command_unban_option_target]
other = "target"

[error_0]
other = "エラーが発生しました {{.Error}}"

[error_TargetIsBot]
other = "このボットをターゲットとして選択できません！"

[error_message]
other = "エラーが発生しました"
