[command.ban.reason]
one = "理由： {{.Reason}}"
other = "理由： {{.Reason}}"

[command.ban.message]
other = "{{.Target}}を追放しました"

[error.0]
other = "エラーが発生しました: {{.Error}}"

[error.TargetIsBot]
other = "このボットをターゲットとして選択できません！"
