[command.ban.description]
other = "選択したユーザーをBANします"

[command.ban.option.target]
other = "ターゲット"

[command.ban.option.description.target]
other = "ユーザーをBANします"

[command.ban.option.description.reason]
other = "banした理由"

[command.ban.option.reason]
other = "理由"

[command.ban.message]
other = "{{.Target}}をbanしました"

[command.ban.reason]
one = "理由： {{.Reason}}"
other = "理由： {{.Reason}}"

[command.kick.description]
other = "選択したユーザーをキックします"

[command.kick.option.target]
other = "ターゲット"

[command.kick.option.description.target]
other = "キックするユーザー"

[command.kick.message]
other = "{{.Target}}をキックしました"

[command.unban.description]
other = "banを解除するユーザーを選択します"

[command.unban.option.target]
other = "ターゲット"

[command.unban.option.description.target]
other = "banを解除したいユーザー"

[command.unban.message]
other = "{{.Target}}のbanを解除しました"

[error.0]
other = "エラーが発生しました： {{.Error}}"

[error.TargetIsBot]
other = "このボットをターゲットとして選択できません！"

[error.message]
other = "エラーが発生しました"
