[command.ban.description]
other = "verbannen de geselecteerde gebruiker"

[command.ban.message]
other = "{{.Target}} is verbannen"

[command.ban.option.description.reason]
other = "reden voor verbannen"

[command.ban.option.description.target]
other = "verbannen gebruiker"

[command.ban.option.reason]
other = "reden"

[command.ban.option.target]
other = "target"

[command.ban.reason]
one = "Reden: {{.Reason}}"
other = "Reden: {{.Reason}}"

[command.kick.description]
other = "Kick de geselecteerde gebruiker"

[command.kick.message]
other = "{{.Target}} is eruit gezet"

[command.kick.option.description.target]
other = "uit te zetten gebruiker"

[command.kick.option.target]
other = "target"

[command.panel.description]
other = "manage or create panel"

[command.panel.option.description.role]
other = "manage role panel"

[command.panel.option.role]
other = "role"

[command.panel.option.role.option.crate.option.desc]
other = "description"

[command.panel.option.role.option.create]
other = "create"

[command.panel.option.role.option.create.option.description.desc]
other = "description of panel"

[command.panel.option.role.option.create.option.description.name]
other = "name of panel"

[command.panel.option.role.option.create.option.description.role]
other = "role that add to the panel"

[command.panel.option.role.option.create.option.name]
other = "name"

[command.panel.option.role.option.create.option.role]
other = "role"

[command.panel.option.role.option.description.create]
other = "create role panel"

[command.unban.description]
other = "pardon the selected user"

[command.unban.message]
other = "{{.Target}} is niet meer verbannen"

[command.unban.option.description.target]
other = "gebruiker om te unbannen"

[command.unban.option.target]
other = "target"

[error.0]
other = "Er is een fout opgetreden {{.Error}}"

[error.TargetIsBot]
other = "Kan deze bot niet selecteren als doel!"

[error.message]
other = "Er is een fout opgetreden"
