[address]
other = "address"

[command_ban_desc]
other = "verbannen de geselecteerde gebruiker"

[command_ban_message]
other = "{{.Target}} is verbannen"

[command_ban_option_desc_reason]
other = "reden voor verbannen"

[command_ban_option_desc_target]
other = "verbannen gebruiker"

[command_ban_option_reason]
other = "reden"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Reden: {{.Reason}}"
other = "Reden: {{.Reason}}"

[command_kick_desc]
other = "Kick de geselecteerde gebruiker"

[command_kick_message]
other = "{{.Target}} is eruit gezet"

[command_kick_option_desc_target]
other = "uit te zetten gebruiker"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "beheren of maken van paneel"

[command_panel_option_desc_role]
other = "beheer rolpaneel"

[command_panel_option_minecraft]
other = "minecraft"

[command_panel_option_minecraft_desc]
other = "manage minecraft panel"

[command_panel_option_minecraft_option_create]
other = "create"

[command_panel_option_minecraft_option_create_desc]
other = "create minecraft panel"

[command_panel_option_minecraft_option_create_option_address]
other = "address"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "address of server"

[command_panel_option_minecraft_option_create_option_description]
other = "description"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "description of panel"

[command_panel_option_minecraft_option_create_option_name]
other = "name"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "name of panel"

[command_panel_option_minecraft_option_create_option_port]
other = "port"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "port of server"

[command_panel_option_minecraft_option_create_option_servername]
other = "servername"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "name of server"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "show ip or not"

[command_panel_option_role]
other = "rol"

[command_panel_option_role_option_create]
other = "aanmaken"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "desc van paneel"

[command_panel_option_role_option_create_option_desc_name]
other = "naam van paneel"

[command_panel_option_role_option_create_option_desc_role]
other = "rol die aan het paneel toegevoegd wordt"

[command_panel_option_role_option_create_option_name]
other = "Naam"

[command_panel_option_role_option_create_option_role]
other = "rol"

[command_panel_option_role_option_desc_create]
other = "maak rolpaneel"

[command_tracker]
other = "tracker"

[command_tracker_desc]
other = "manage or create tracker"

[command_tracker_option_minecraft]
other = "minecraft"

[command_tracker_option_minecraft_desc]
other = "manage minecraft server tracker"

[command_tracker_option_minecraft_option_create]
other = "create"

[command_tracker_option_minecraft_option_create_desc]
other = "minecraft server tracker"

[command_tracker_option_minecraft_option_create_option_address]
other = "address"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "address of server"

[command_tracker_option_minecraft_option_create_option_name]
other = "name"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "name of server"

[command_tracker_option_minecraft_option_create_option_port]
other = "port"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "port of server"

[command_tracker_option_minecraft_option_create_option_role]
other = "role"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "role to mention"

[command_unban_desc]
other = "deblokkeer de geselecteerde gebruiker"

[command_unban_message]
other = "{{.Target}} is niet meer verbannen"

[command_unban_option_desc_target]
other = "gebruiker om te unbannen"

[command_unban_option_target]
other = "target"

[error]
other = "{{.Error}}"

[error_0]
other = "Er is een fout opgetreden {{.Error}}"

[error_TargetIsBot]
other = "Kan deze bot niet selecteren als doel!"

[error_failed_to_connect_api]
other = "failed to connect api server error"

[error_failed_to_ping_server]
other = "failed to ping server"

[error_invalid_port_value]
other = "invalid port value"

[error_message]
other = "Er is een fout opgetreden"

[feed_minecraft_webhook_name]
other = "server notifier"

[latency]
other = "latency"

[message_command_modify]
other = "modify"

[panel_minecraft_message_boot]
other = "booted {{.Name}} server"

[panel_minecraft_message_stop]
other = "stopped {{.Name}} server"

[panel_role_message_added]
other = "added"

[panel_role_message_removed]
other = "removed"

[players]
other = "players"

[port]
other = "port"

[version]
other = "version"
