[command.ban.description]
other = "verbannen de geselecteerde gebruiker"

[command.ban.option.target]
other = "target"

[command.ban.option.description.target]
other = "verbannen gebruiker"

[command.ban.option.description.reason]
other = "reden voor verbannen"

[command.ban.option.reason]
other = "reden"

[command.ban.message]
other = "{{.Target}} is verbannen"

[command.ban.reason]
one = "Reden: {{.Reason}}"
other = "Reden: {{.Reason}}"

[command.kick.description]
other = "Kick de geselecteerde gebruiker"

[command.kick.option.target]
other = "target"

[command.kick.option.description.target]
other = "uit te zetten gebruiker"

[command.kick.message]
other = "{{.Target}} is eruit gezet"

[command.unban.description]
other = "pardon the selected user"

[command.unban.option.target]
other = "target"

[command.unban.option.description.target]
other = "gebruiker om te unbannen"

[command.unban.message]
other = "{{.Target}} is niet meer verbannen"

[error.0]
other = "Er is een fout opgetreden {{.Error}}"

[error.TargetIsBot]
other = "Kan deze bot niet selecteren als doel!"

[error.message]
other = "Er is een fout opgetreden"
