command = { }
command_ban = { }
command_ban_option = { }
command_ban_option_desc = { }
command_kick = { }
command_kick_option = { }
command_kick_option_desc = { }
command_panel = { }
command_panel_option = { }
command_panel_option_desc = { }
command_panel_option_role_option_create_option = { }
command_panel_option_role_option_desc = { }
command_unban = { }
command_unban_option = { }
command_unban_option_desc = { }
error = { }

[command_ban_desc]
other = "utesteng den valgte brukeren"

[command_ban_message]
other = "{{.Target}} har blitt utestengt"

[command_ban_option_desc_reason]
other = "årsak til utestengelsen"

[command_ban_option_desc_target]
other = "bruker å utestenge"

[command_ban_option_reason]
other = "grunn"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Årsak: {{.Reason}}"
other = "Årsak: {{.Reason}}"

[command_kick_desc]
other = "spark den valgte brukeren"

[command_kick_message]
other = "{{.Target}} har blitt sparket ut"

[command_kick_option_desc_target]
other = "bruker som skal sparke"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "administrer eller opprett panel"

[command_panel_option_desc_role]
other = "administrere rollepanelet"

[command_panel_option_role]
other = "rolle"

[command_panel_option_role_option_create]
other = "Opprett"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "Beskrivelse av panel"

[command_panel_option_role_option_create_option_desc_name]
other = "navn på panelet"

[command_panel_option_role_option_create_option_desc_role]
other = "rolle som legger til i panelet"

[command_panel_option_role_option_create_option_name]
other = "navn"

[command_panel_option_role_option_create_option_role]
other = "rolle"

[command_panel_option_role_option_desc_create]
other = "opprett rollepanel"

[command_unban_desc]
other = "opphev bannlysningen av valgte bruker"

[command_unban_message]
other = "{{.Target}} har blitt utestengt"

[command_unban_option_desc_target]
other = "bruker som opphever utestengelsen"

[command_unban_option_target]
other = "target"

[error_0]
other = "En feil har oppstått {{.Error}}"

[error_TargetIsBot]
other = "Kan ikke velge denne botten som mål!"

[error_message]
other = "En feil har oppstått"
