[command.ban.description]
other = "utesteng den valgte brukeren"

[command.ban.option.target]
other = "target"

[command.ban.option.description.target]
other = "bruker å utestenge"

[command.ban.option.description.reason]
other = "årsak til utestengelsen"

[command.ban.option.reason]
other = "grunn"

[command.ban.message]
other = "{{.Target}} har blitt utestengt"

[command.ban.reason]
one = "Årsak: {{.Reason}}"
other = "Årsak: {{.Reason}}"

[command.kick.description]
other = "spark den valgte brukeren"

[command.kick.option.target]
other = "target"

[command.kick.option.description.target]
other = "bruker som skal sparke"

[command.kick.message]
other = "{{.Target}} har blitt sparket ut"

[command.unban.description]
other = "pardon the selected user"

[command.unban.option.target]
other = "target"

[command.unban.option.description.target]
other = "bruker som opphever utestengelsen"

[command.unban.message]
other = "{{.Target}} har blitt utestengt"

[error.0]
other = "En feil har oppstått {{.Error}}"

[error.TargetIsBot]
other = "Kan ikke velge denne botten som mål!"

[error.message]
other = "En feil har oppstått"
