[command.ban.description]
other = "utesteng den valgte brukeren"

[command.ban.message]
other = "{{.Target}} har blitt utestengt"

[command.ban.option.description.reason]
other = "årsak til utestengelsen"

[command.ban.option.description.target]
other = "bruker å utestenge"

[command.ban.option.reason]
other = "grunn"

[command.ban.option.target]
other = "target"

[command.ban.reason]
one = "Årsak: {{.Reason}}"
other = "Årsak: {{.Reason}}"

[command.kick.description]
other = "spark den valgte brukeren"

[command.kick.message]
other = "{{.Target}} har blitt sparket ut"

[command.kick.option.description.target]
other = "bruker som skal sparke"

[command.kick.option.target]
other = "target"

[command.panel.description]
other = "administrer eller opprett panel"

[command.panel.option.description.role]
other = "administrere rollepanelet"

[command.panel.option.role]
other = "rolle"

[command.panel.option.role.option.crate.option.desc]
other = "beskrivelse"

[command.panel.option.role.option.create]
other = "Opprett"

[command.panel.option.role.option.create.option.description.desc]
other = "beskrivelse av panel"

[command.panel.option.role.option.create.option.description.name]
other = "navn på panelet"

[command.panel.option.role.option.create.option.description.role]
other = "rolle som legger til i panelet"

[command.panel.option.role.option.create.option.name]
other = "navn"

[command.panel.option.role.option.create.option.role]
other = "rolle"

[command.panel.option.role.option.description.create]
other = "opprett rollepanel"

[command.unban.description]
other = "pardon the selected user"

[command.unban.message]
other = "{{.Target}} har blitt utestengt"

[command.unban.option.description.target]
other = "bruker som opphever utestengelsen"

[command.unban.option.target]
other = "target"

[error.0]
other = "En feil har oppstått {{.Error}}"

[error.TargetIsBot]
other = "Kan ikke velge denne botten som mål!"

[error.message]
other = "En feil har oppstått"
