[command.ban.description]
other = "zbanuj wybranego użytkownika"

[command.ban.message]
other = "{{.Target}} został zbanowany"

[command.ban.option.description.reason]
other = "powód zakazu"

[command.ban.option.description.target]
other = "użytkownik do zbanowania"

[command.ban.option.reason]
other = "powód"

[command.ban.option.target]
other = "target"

[command.ban.reason]
one = "Powód: {{.Reason}}"
other = "Powody: {{.Reason}}"

[command.kick.description]
other = "wyrzuć wybranego użytkownika"

[command.kick.message]
other = "{{.Target}} został wyrzucony"

[command.kick.option.description.target]
other = "użytkownik do wyrzucenia"

[command.kick.option.target]
other = "target"

[command.panel.description]
other = "manage or create panel"

[command.panel.option.description.role]
other = "manage role panel"

[command.panel.option.role]
other = "role"

[command.panel.option.role.option.crate.option.desc]
other = "description"

[command.panel.option.role.option.create]
other = "create"

[command.panel.option.role.option.create.option.description.desc]
other = "description of panel"

[command.panel.option.role.option.create.option.description.name]
other = "name of panel"

[command.panel.option.role.option.create.option.description.role]
other = "role that add to the panel"

[command.panel.option.role.option.create.option.name]
other = "name"

[command.panel.option.role.option.create.option.role]
other = "role"

[command.panel.option.role.option.description.create]
other = "create role panel"

[command.unban.description]
other = "pardon the selected user"

[command.unban.message]
other = "{{.Target}} został odbanowany"

[command.unban.option.description.target]
other = "użytkownik do odblokowania"

[command.unban.option.target]
other = "target"

[error.0]
other = "Wystąpił błąd {{.Error}}"

[error.TargetIsBot]
other = "Nie można wybrać tego bota jako celu!"

[error.message]
other = "Wystąpił błąd"
