[command.ban.description]
other = "zbanuj wybranego użytkownika"

[command.ban.option.target]
other = "target"

[command.ban.option.description.target]
other = "użytkownik do zbanowania"

[command.ban.option.description.reason]
other = "powód zakazu"

[command.ban.option.reason]
other = "powód"

[command.ban.message]
other = "{{.Target}} został zbanowany"

[command.ban.reason]
one = "Powód: {{.Reason}}"
other = "Powody: {{.Reason}}"

[command.kick.description]
other = "wyrzuć wybranego użytkownika"

[command.kick.option.target]
other = "target"

[command.kick.option.description.target]
other = "użytkownik do wyrzucenia"

[command.kick.message]
other = "{{.Target}} został wyrzucony"

[command.unban.description]
other = "pardon the selected user"

[command.unban.option.target]
other = "target"

[command.unban.option.description.target]
other = "użytkownik do odblokowania"

[command.unban.message]
other = "{{.Target}} został odbanowany"

[error.0]
other = "Wystąpił błąd {{.Error}}"

[error.TargetIsBot]
other = "Nie można wybrać tego bota jako celu!"

[error.message]
other = "Wystąpił błąd"
