command = { }
command_ban = { }
command_ban_option = { }
command_ban_option_desc = { }
command_kick = { }
command_kick_option = { }
command_kick_option_desc = { }
command_panel = { }
command_panel_option = { }
command_panel_option_desc = { }
command_panel_option_role_option_create_option = { }
command_panel_option_role_option_desc = { }
command_unban = { }
command_unban_option = { }
command_unban_option_desc = { }
error = { }

[command_ban_desc]
other = "zbanuj wybranego użytkownika"

[command_ban_message]
other = "{{.Target}} został zbanowany"

[command_ban_option_desc_reason]
other = "powód zakazu"

[command_ban_option_desc_target]
other = "użytkownik do zbanowania"

[command_ban_option_reason]
other = "powód"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Powód: {{.Reason}}"
other = "Powody: {{.Reason}}"

[command_kick_desc]
other = "wyrzuć wybranego użytkownika"

[command_kick_message]
other = "{{.Target}} został wyrzucony"

[command_kick_option_desc_target]
other = "użytkownik do wyrzucenia"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "zarządzaj lub utwórz panel"

[command_panel_option_desc_role]
other = "zarządzanie panelem ról"

[command_panel_option_role]
other = "Rola"

[command_panel_option_role_option_create]
other = "utwórz"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "desc panelu"

[command_panel_option_role_option_create_option_desc_name]
other = "nazwa panelu"

[command_panel_option_role_option_create_option_desc_role]
other = "rola, która dodaje do panelu"

[command_panel_option_role_option_create_option_name]
other = "Nazwa"

[command_panel_option_role_option_create_option_role]
other = "Rola"

[command_panel_option_role_option_desc_create]
other = "utwórz panel ról"

[command_unban_desc]
other = "odbanuj wybranego użytkownika"

[command_unban_message]
other = "{{.Target}} został odbanowany"

[command_unban_option_desc_target]
other = "użytkownik do odblokowania"

[command_unban_option_target]
other = "target"

[error_0]
other = "Wystąpił błąd {{.Error}}"

[error_TargetIsBot]
other = "Nie można wybrać tego bota jako celu!"

[error_message]
other = "Wystąpił błąd"
