[address]
other = "address"

[command_ban_desc]
other = "zbanuj wybranego użytkownika"

[command_ban_message]
other = "{{.Target}} został zbanowany"

[command_ban_option_desc_reason]
other = "powód zakazu"

[command_ban_option_desc_target]
other = "użytkownik do zbanowania"

[command_ban_option_reason]
other = "powód"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Powód: {{.Reason}}"
other = "Powody: {{.Reason}}"

[command_kick_desc]
other = "wyrzuć wybranego użytkownika"

[command_kick_message]
other = "{{.Target}} został wyrzucony"

[command_kick_option_desc_target]
other = "użytkownik do wyrzucenia"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "zarządzaj lub utwórz panel"

[command_panel_option_desc_role]
other = "zarządzanie panelem ról"

[command_panel_option_minecraft]
other = "minecraft"

[command_panel_option_minecraft_desc]
other = "manage minecraft panel"

[command_panel_option_minecraft_option_create]
other = "create"

[command_panel_option_minecraft_option_create_desc]
other = "create minecraft panel"

[command_panel_option_minecraft_option_create_option_address]
other = "address"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "address of server"

[command_panel_option_minecraft_option_create_option_description]
other = "description"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "description of panel"

[command_panel_option_minecraft_option_create_option_name]
other = "name"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "name of panel"

[command_panel_option_minecraft_option_create_option_port]
other = "port"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "port of server"

[command_panel_option_minecraft_option_create_option_servername]
other = "servername"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "name of server"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "show ip or not"

[command_panel_option_role]
other = "Rola"

[command_panel_option_role_option_create]
other = "utwórz"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "desc panelu"

[command_panel_option_role_option_create_option_desc_name]
other = "nazwa panelu"

[command_panel_option_role_option_create_option_desc_role]
other = "rola, która dodaje do panelu"

[command_panel_option_role_option_create_option_name]
other = "Nazwa"

[command_panel_option_role_option_create_option_role]
other = "Rola"

[command_panel_option_role_option_desc_create]
other = "utwórz panel ról"

[command_tracker]
other = "tracker"

[command_tracker_desc]
other = "manage or create tracker"

[command_tracker_option_minecraft]
other = "minecraft"

[command_tracker_option_minecraft_desc]
other = "manage minecraft server tracker"

[command_tracker_option_minecraft_option_create]
other = "create"

[command_tracker_option_minecraft_option_create_desc]
other = "minecraft server tracker"

[command_tracker_option_minecraft_option_create_option_address]
other = "address"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "address of server"

[command_tracker_option_minecraft_option_create_option_name]
other = "name"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "name of server"

[command_tracker_option_minecraft_option_create_option_port]
other = "port"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "port of server"

[command_tracker_option_minecraft_option_create_option_role]
other = "role"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "role to mention"

[command_unban_desc]
other = "odbanuj wybranego użytkownika"

[command_unban_message]
other = "{{.Target}} został odbanowany"

[command_unban_option_desc_target]
other = "użytkownik do odblokowania"

[command_unban_option_target]
other = "target"

[error]
other = "{{.Error}}"

[error_0]
other = "Wystąpił błąd {{.Error}}"

[error_TargetIsBot]
other = "Nie można wybrać tego bota jako celu!"

[error_failed_to_connect_api]
other = "failed to connect api server error"

[error_failed_to_ping_server]
other = "failed to ping server"

[error_invalid_port_value]
other = "invalid port value"

[error_message]
other = "Wystąpił błąd"

[feed_minecraft_webhook_name]
other = "server notifier"

[latency]
other = "latency"

[message_command_modify]
other = "modify"

[panel_minecraft_message_boot]
other = "booted {{.Name}} server"

[panel_minecraft_message_stop]
other = "stopped {{.Name}} server"

[panel_role_message_added]
other = "added"

[panel_role_message_removed]
other = "removed"

[players]
other = "players"

[port]
other = "port"

[version]
other = "version"
