[command.ban.description]
other = "banir o usuário selecionado"

[command.ban.message]
other = "{{.Target}} foi banido"

[command.ban.option.description.reason]
other = "motivo do banimento"

[command.ban.option.description.target]
other = "usuário a banir"

[command.ban.option.reason]
other = "Razão"

[command.ban.option.target]
other = "target"

[command.ban.reason]
one = "Motivo: {{.Reason}}"
other = "Motivos: {{.Reason}}"

[command.kick.description]
other = "expulsar o usuário selecionado"

[command.kick.message]
other = "{{.Target}} foi expulso"

[command.kick.option.description.target]
other = "usuário para expulsar"

[command.kick.option.target]
other = "target"

[command.panel.description]
other = "manage or create panel"

[command.panel.option.description.role]
other = "manage role panel"

[command.panel.option.role]
other = "role"

[command.panel.option.role.option.crate.option.desc]
other = "description"

[command.panel.option.role.option.create]
other = "create"

[command.panel.option.role.option.create.option.description.desc]
other = "description of panel"

[command.panel.option.role.option.create.option.description.name]
other = "name of panel"

[command.panel.option.role.option.create.option.description.role]
other = "role that add to the panel"

[command.panel.option.role.option.create.option.name]
other = "name"

[command.panel.option.role.option.create.option.role]
other = "role"

[command.panel.option.role.option.description.create]
other = "create role panel"

[command.unban.description]
other = "pardon the selected user"

[command.unban.message]
other = "{{.Target}} foi desbanido"

[command.unban.option.description.target]
other = "usuário para desbanir"

[command.unban.option.target]
other = "target"

[error.0]
other = "Ocorreu um erro {{.Error}}"

[error.TargetIsBot]
other = "Não é possível selecionar este bot como destino!"

[error.message]
other = "Ocorreu um erro"
