[command.ban.description]
other = "banir o usuário selecionado"

[command.ban.option.target]
other = "target"

[command.ban.option.description.target]
other = "usuário a banir"

[command.ban.option.description.reason]
other = "motivo do banimento"

[command.ban.option.reason]
other = "Razão"

[command.ban.message]
other = "{{.Target}} foi banido"

[command.ban.reason]
one = "Motivo: {{.Reason}}"
other = "Motivos: {{.Reason}}"

[command.kick.description]
other = "expulsar o usuário selecionado"

[command.kick.option.target]
other = "target"

[command.kick.option.description.target]
other = "usuário para expulsar"

[command.kick.message]
other = "{{.Target}} foi expulso"

[command.unban.description]
other = "pardon the selected user"

[command.unban.option.target]
other = "target"

[command.unban.option.description.target]
other = "usuário para desbanir"

[command.unban.message]
other = "{{.Target}} foi desbanido"

[error.0]
other = "Ocorreu um erro {{.Error}}"

[error.TargetIsBot]
other = "Não é possível selecionar este bot como destino!"

[error.message]
other = "Ocorreu um erro"
