command = { }
command_ban = { }
command_ban_option = { }
command_ban_option_desc = { }
command_kick = { }
command_kick_option = { }
command_kick_option_desc = { }
command_panel = { }
command_panel_option = { }
command_panel_option_desc = { }
command_panel_option_role_option_create_option = { }
command_panel_option_role_option_desc = { }
command_unban = { }
command_unban_option = { }
command_unban_option_desc = { }
error = { }

[command_ban_desc]
other = "banir o usuário selecionado"

[command_ban_message]
other = "{{.Target}} foi banido"

[command_ban_option_desc_reason]
other = "motivo do banimento"

[command_ban_option_desc_target]
other = "usuário a banir"

[command_ban_option_reason]
other = "Razão"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Motivo: {{.Reason}}"
other = "Motivos: {{.Reason}}"

[command_kick_desc]
other = "expulsar o usuário selecionado"

[command_kick_message]
other = "{{.Target}} foi expulso"

[command_kick_option_desc_target]
other = "usuário para expulsar"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "gerenciar ou criar painel"

[command_panel_option_desc_role]
other = "gerenciar painel de funções"

[command_panel_option_role]
other = "Função"

[command_panel_option_role_option_create]
other = "criar"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "DESC do painel"

[command_panel_option_role_option_create_option_desc_name]
other = "nome do painel"

[command_panel_option_role_option_create_option_desc_role]
other = "função que adicionar ao painel"

[command_panel_option_role_option_create_option_name]
other = "Nome"

[command_panel_option_role_option_create_option_role]
other = "Função"

[command_panel_option_role_option_desc_create]
other = "criar painel de função"

[command_unban_desc]
other = "desbanir o usuário selecionado"

[command_unban_message]
other = "{{.Target}} foi desbanido"

[command_unban_option_desc_target]
other = "usuário para desbanir"

[command_unban_option_target]
other = "target"

[error_0]
other = "Ocorreu um erro {{.Error}}"

[error_TargetIsBot]
other = "Não é possível selecionar este bot como destino!"

[error_message]
other = "Ocorreu um erro"
