[command.ban.description]
other = "interzice utilizatorul selectat"

[command.ban.option.target]
other = "target"

[command.ban.option.description.target]
other = "utilizator pentru a interzice"

[command.ban.option.description.reason]
other = "motiv pentru interdicție"

[command.ban.option.reason]
other = "motiv"

[command.ban.message]
other = "{{.Target}} a fost banat"

[command.ban.reason]
one = "Motiv: {{.Reason}}"
other = "Motive: {{.Reason}}"

[command.kick.description]
other = "exclude utilizatorul selectat"

[command.kick.option.target]
other = "target"

[command.kick.option.description.target]
other = "utilizator de dat afară"

[command.kick.message]
other = "{{.Target}} a fost dat afară"

[command.unban.description]
other = "pardon the selected user"

[command.unban.option.target]
other = "target"

[command.unban.option.description.target]
other = "utilizator pentru a debloca"

[command.unban.message]
other = "{{.Target}} a fost debanat"

[error.0]
other = "S-a produs o eroare {{.Error}}"

[error.TargetIsBot]
other = "Nu se poate selecta acest bot ca țintă!"

[error.message]
other = "A apărut o eroare"
