command = { }
command_ban = { }
command_ban_option = { }
command_ban_option_desc = { }
command_kick = { }
command_kick_option = { }
command_kick_option_desc = { }
command_panel = { }
command_panel_option = { }
command_panel_option_desc = { }
command_panel_option_role_option_create_option = { }
command_panel_option_role_option_desc = { }
command_unban = { }
command_unban_option = { }
command_unban_option_desc = { }
error = { }

[command_ban_desc]
other = "interzice utilizatorul selectat"

[command_ban_message]
other = "{{.Target}} a fost banat"

[command_ban_option_desc_reason]
other = "motiv pentru interdicție"

[command_ban_option_desc_target]
other = "utilizator pentru a interzice"

[command_ban_option_reason]
other = "motiv"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Motiv: {{.Reason}}"
other = "Motive: {{.Reason}}"

[command_kick_desc]
other = "exclude utilizatorul selectat"

[command_kick_message]
other = "{{.Target}} a fost dat afară"

[command_kick_option_desc_target]
other = "utilizator de dat afară"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "gestionare sau creare panou"

[command_panel_option_desc_role]
other = "gestionează panoul de rol"

[command_panel_option_role]
other = "rol"

[command_panel_option_role_option_create]
other = "crează"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "descoperirea panoului"

[command_panel_option_role_option_create_option_desc_name]
other = "numele panoului"

[command_panel_option_role_option_create_option_desc_role]
other = "rol care adaugă la panou"

[command_panel_option_role_option_create_option_name]
other = "nume"

[command_panel_option_role_option_create_option_role]
other = "rol"

[command_panel_option_role_option_desc_create]
other = "creează panou de rol"

[command_unban_desc]
other = "deblochează utilizatorul selectat"

[command_unban_message]
other = "{{.Target}} a fost debanat"

[command_unban_option_desc_target]
other = "utilizator pentru a debloca"

[command_unban_option_target]
other = "target"

[error_0]
other = "S-a produs o eroare {{.Error}}"

[error_TargetIsBot]
other = "Nu se poate selecta acest bot ca țintă!"

[error_message]
other = "A apărut o eroare"
