[command.ban.description]
other = "interzice utilizatorul selectat"

[command.ban.message]
other = "{{.Target}} a fost banat"

[command.ban.option.description.reason]
other = "motiv pentru interdicție"

[command.ban.option.description.target]
other = "utilizator pentru a interzice"

[command.ban.option.reason]
other = "motiv"

[command.ban.option.target]
other = "target"

[command.ban.reason]
one = "Motiv: {{.Reason}}"
other = "Motive: {{.Reason}}"

[command.kick.description]
other = "exclude utilizatorul selectat"

[command.kick.message]
other = "{{.Target}} a fost dat afară"

[command.kick.option.description.target]
other = "utilizator de dat afară"

[command.kick.option.target]
other = "target"

[command.panel.description]
other = "gestionare sau creare panou"

[command.panel.option.description.role]
other = "gestionează panoul de rol"

[command.panel.option.role]
other = "rol"

[command.panel.option.role.option.crate.option.desc]
other = "descriere"

[command.panel.option.role.option.create]
other = "crează"

[command.panel.option.role.option.create.option.description.desc]
other = "descrierea panoului"

[command.panel.option.role.option.create.option.description.name]
other = "numele panoului"

[command.panel.option.role.option.create.option.description.role]
other = "rol care adaugă la panou"

[command.panel.option.role.option.create.option.name]
other = "nume"

[command.panel.option.role.option.create.option.role]
other = "rol"

[command.panel.option.role.option.description.create]
other = "creează panou de rol"

[command.unban.description]
other = "pardon the selected user"

[command.unban.message]
other = "{{.Target}} a fost debanat"

[command.unban.option.description.target]
other = "utilizator pentru a debloca"

[command.unban.option.target]
other = "target"

[error.0]
other = "S-a produs o eroare {{.Error}}"

[error.TargetIsBot]
other = "Nu se poate selecta acest bot ca țintă!"

[error.message]
other = "A apărut o eroare"
