command = { }
command_ban = { }
command_ban_option = { }
command_ban_option_desc = { }
command_kick = { }
command_kick_option = { }
command_kick_option_desc = { }
command_panel = { }
command_panel_option = { }
command_panel_option_desc = { }
command_panel_option_role_option_create_option = { }
command_panel_option_role_option_desc = { }
command_unban = { }
command_unban_option = { }
command_unban_option_desc = { }
error = { }

[command_ban_desc]
other = "bannlysa den valda användaren"

[command_ban_message]
other = "{{.Target}} har blivit bannlyst"

[command_ban_option_desc_reason]
other = "anledning till bannlysning"

[command_ban_option_desc_target]
other = "användare att bannlysa"

[command_ban_option_reason]
other = "anledning"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Orsak: {{.Reason}}"
other = "Anledningar: {{.Reason}}"

[command_kick_desc]
other = "sparka den valda användaren"

[command_kick_message]
other = "{{.Target}} har blivit sparkad"

[command_kick_option_desc_target]
other = "användare att sparka"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "hantera eller skapa panel"

[command_panel_option_desc_role]
other = "hantera rollpanel"

[command_panel_option_role]
other = "roll"

[command_panel_option_role_option_create]
other = "skapa"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "desc av panelen"

[command_panel_option_role_option_create_option_desc_name]
other = "namn på panel"

[command_panel_option_role_option_create_option_desc_role]
other = "roll som lägger till i panelen"

[command_panel_option_role_option_create_option_name]
other = "namn"

[command_panel_option_role_option_create_option_role]
other = "roll"

[command_panel_option_role_option_desc_create]
other = "skapa rollpanel"

[command_unban_desc]
other = "obannlysa den valda användaren"

[command_unban_message]
other = "{{.Target}} har blivit bannlyst"

[command_unban_option_desc_target]
other = "användare att ta bort bannlysning"

[command_unban_option_target]
other = "target"

[error_0]
other = "Ett fel har inträffat {{.Error}}"

[error_TargetIsBot]
other = "Kan inte välja denna bot som mål!"

[error_message]
other = "Ett fel har uppstått"
