[command.ban.description]
other = "bannlysa den valda användaren"

[command.ban.option.target]
other = "target"

[command.ban.option.description.target]
other = "användare att bannlysa"

[command.ban.option.description.reason]
other = "anledning till bannlysning"

[command.ban.option.reason]
other = "anledning"

[command.ban.message]
other = "{{.Target}} har blivit bannlyst"

[command.ban.reason]
one = "Orsak: {{.Reason}}"
other = "Anledningar: {{.Reason}}"

[command.kick.description]
other = "sparka den valda användaren"

[command.kick.option.target]
other = "target"

[command.kick.option.description.target]
other = "användare att sparka"

[command.kick.message]
other = "{{.Target}} har blivit sparkad"

[command.unban.description]
other = "pardon the selected user"

[command.unban.option.target]
other = "target"

[command.unban.option.description.target]
other = "användare att ta bort bannlysning"

[command.unban.message]
other = "{{.Target}} har blivit bannlyst"

[error.0]
other = "Ett fel har inträffat {{.Error}}"

[error.TargetIsBot]
other = "Kan inte välja denna bot som mål!"

[error.message]
other = "Ett fel har uppstått"
