[command.ban.description]
other = "bannlysa den valda användaren"

[command.ban.message]
other = "{{.Target}} har blivit bannlyst"

[command.ban.option.description.reason]
other = "anledning till bannlysning"

[command.ban.option.description.target]
other = "användare att bannlysa"

[command.ban.option.reason]
other = "anledning"

[command.ban.option.target]
other = "target"

[command.ban.reason]
one = "Orsak: {{.Reason}}"
other = "Anledningar: {{.Reason}}"

[command.kick.description]
other = "sparka den valda användaren"

[command.kick.message]
other = "{{.Target}} har blivit sparkad"

[command.kick.option.description.target]
other = "användare att sparka"

[command.kick.option.target]
other = "target"

[command.panel.description]
other = "hantera eller skapa panel"

[command.panel.option.description.role]
other = "hantera rollpanel"

[command.panel.option.role]
other = "roll"

[command.panel.option.role.option.crate.option.desc]
other = "beskrivning"

[command.panel.option.role.option.create]
other = "skapa"

[command.panel.option.role.option.create.option.description.desc]
other = "beskrivning av panel"

[command.panel.option.role.option.create.option.description.name]
other = "namn på panel"

[command.panel.option.role.option.create.option.description.role]
other = "roll som lägger till i panelen"

[command.panel.option.role.option.create.option.name]
other = "namn"

[command.panel.option.role.option.create.option.role]
other = "roll"

[command.panel.option.role.option.description.create]
other = "skapa rollpanel"

[command.unban.description]
other = "pardon the selected user"

[command.unban.message]
other = "{{.Target}} har blivit bannlyst"

[command.unban.option.description.target]
other = "användare att ta bort bannlysning"

[command.unban.option.target]
other = "target"

[error.0]
other = "Ett fel har inträffat {{.Error}}"

[error.TargetIsBot]
other = "Kan inte välja denna bot som mål!"

[error.message]
other = "Ett fel har uppstått"
