[command.ban.description]
other = "забанити вибраного користувача"

[command.ban.message]
other = "{{.Target}} був забанений"

[command.ban.option.description.reason]
other = "причина для бану"

[command.ban.option.description.target]
other = "користувач для блокування"

[command.ban.option.reason]
other = "причина"

[command.ban.option.target]
other = "target"

[command.ban.reason]
one = "Причина: {{.Reason}}"
other = "Причини: {{.Reason}}"

[command.kick.description]
other = "вилучити вибраного користувача"

[command.kick.message]
other = "{{.Target}} був вигнаний"

[command.kick.option.description.target]
other = "користувача для вилучення"

[command.kick.option.target]
other = "target"

[command.panel.description]
other = "керування або створити панель"

[command.panel.option.description.role]
other = "керувати панеллю ролей"

[command.panel.option.role]
other = "роль"

[command.panel.option.role.option.crate.option.desc]
other = "опис"

[command.panel.option.role.option.create]
other = "створити"

[command.panel.option.role.option.create.option.description.desc]
other = "опис панелі"

[command.panel.option.role.option.create.option.description.name]
other = "назва панелі"

[command.panel.option.role.option.create.option.description.role]
other = "роль, що додає до панелі"

[command.panel.option.role.option.create.option.name]
other = "ім'я"

[command.panel.option.role.option.create.option.role]
other = "роль"

[command.panel.option.role.option.description.create]
other = "створити панель ролі"

[command.unban.description]
other = "pardon the selected user"

[command.unban.message]
other = "{{.Target}} був розблокований"

[command.unban.option.description.target]
other = "користувача для розблокування"

[command.unban.option.target]
other = "target"

[error.0]
other = "Відбулася помилка {{.Error}}"

[error.TargetIsBot]
other = "Не вдається вибрати цього бота як ціль!"

[error.message]
other = "Сталася помилка"
