command = { }
command_ban = { }
command_ban_option = { }
command_ban_option_desc = { }
command_kick = { }
command_kick_option = { }
command_kick_option_desc = { }
command_panel = { }
command_panel_option = { }
command_panel_option_desc = { }
command_panel_option_role_option_create_option = { }
command_panel_option_role_option_desc = { }
command_unban = { }
command_unban_option = { }
command_unban_option_desc = { }
error = { }

[command_ban_desc]
other = "封禁所选用户"

[command_ban_message]
other = "{{.Target}} 已被封禁"

[command_ban_option_desc_reason]
other = "禁止的原因"

[command_ban_option_desc_target]
other = "要禁止的用户"

[command_ban_option_reason]
other = "原因"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "原因： {{.Reason}}"
other = "原因： {{.Reason}}"

[command_kick_desc]
other = "踢出选中的用户"

[command_kick_message]
other = "{{.Target}} 已被踢出"

[command_kick_option_desc_target]
other = "要踢出的用户"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "管理或创建面板"

[command_panel_option_desc_role]
other = "管理角色面板"

[command_panel_option_role]
other = "角色"

[command_panel_option_role_option_create]
other = "创建"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "面板降序排列"

[command_panel_option_role_option_create_option_desc_name]
other = "面板名称"

[command_panel_option_role_option_create_option_desc_role]
other = "添加到面板的角色"

[command_panel_option_role_option_create_option_name]
other = "名称"

[command_panel_option_role_option_create_option_role]
other = "角色"

[command_panel_option_role_option_desc_create]
other = "创建角色面板"

[command_unban_desc]
other = "取消封禁所选用户"

[command_unban_message]
other = "{{.Target}} 已被解除封禁"

[command_unban_option_desc_target]
other = "要解除封禁的用户"

[command_unban_option_target]
other = "target"

[error_0]
other = "发生错误 {{.Error}}"

[error_TargetIsBot]
other = "无法选择此机器人为目标！"

[error_message]
other = "发生错误"
