[command.ban.description]
other = "封禁所选用户"

[command.ban.option.target]
other = "target"

[command.ban.option.description.target]
other = "要禁止的用户"

[command.ban.option.description.reason]
other = "禁止的原因"

[command.ban.option.reason]
other = "原因"

[command.ban.message]
other = "{{.Target}} 已被封禁"

[command.ban.reason]
one = "原因： {{.Reason}}"
other = "原因： {{.Reason}}"

[command.kick.description]
other = "踢出选中的用户"

[command.kick.option.target]
other = "target"

[command.kick.option.description.target]
other = "要踢出的用户"

[command.kick.message]
other = "{{.Target}} 已被踢出"

[command.unban.description]
other = "pardon the selected user"

[command.unban.option.target]
other = "target"

[command.unban.option.description.target]
other = "要解除封禁的用户"

[command.unban.message]
other = "{{.Target}} 已被解除封禁"

[error.0]
other = "发生错误 {{.Error}}"

[error.TargetIsBot]
other = "无法选择此机器人为目标！"

[error.message]
other = "发生错误"
