[address]
other = "Adresa"

[command_ban_desc]
other = "zakázat vybraného uživatele"

[command_ban_message]
other = "{{.Target}} byl zabanován"

[command_ban_option_desc_reason]
other = "důvod zákazu"

[command_ban_option_desc_target]
other = "zabanovat uživatele"

[command_ban_option_reason]
other = "důvod"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Důvod: {{.Reason}}"
other = "Důvody: {{.Reason}}"

[command_kick_desc]
other = "vyhodit vybraného uživatele"

[command_kick_message]
other = "{{.Target}} byl vyhozen"

[command_kick_option_desc_target]
other = "vykopnout uživatele"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "spravovat nebo vytvářet panel"

[command_panel_option_desc_role]
other = "spravovat panel rolí"

[command_panel_option_minecraft]
other = "těžební plošina"

[command_panel_option_minecraft_desc]
other = "Spravovat panel minecraft"

[command_panel_option_minecraft_option_create]
other = "vytvořit"

[command_panel_option_minecraft_option_create_desc]
other = "vytvořit panel minecraft"

[command_panel_option_minecraft_option_create_option_address]
other = "Adresa"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "adresa serveru"

[command_panel_option_minecraft_option_create_option_description]
other = "Popis"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "popis poradní skupiny"

[command_panel_option_minecraft_option_create_option_name]
other = "jméno"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "název dílce"

[command_panel_option_minecraft_option_create_option_port]
other = "přístav"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "port serveru"

[command_panel_option_minecraft_option_create_option_servername]
other = "jméno serveru"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "jméno serveru"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "zobrazit IP nebo ne"

[command_panel_option_role]
other = "role"

[command_panel_option_role_option_create]
other = "vytvořit"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "sesta dílce"

[command_panel_option_role_option_create_option_desc_name]
other = "název dílce"

[command_panel_option_role_option_create_option_desc_role]
other = "role, která přidává do panelu"

[command_panel_option_role_option_create_option_name]
other = "jméno"

[command_panel_option_role_option_create_option_role]
other = "role"

[command_panel_option_role_option_desc_create]
other = "vytvořit panel role"

[command_tracker]
other = "tracker"

[command_tracker_desc]
other = "spravovat nebo vytvářet tracker"

[command_tracker_option_minecraft]
other = "těžební plošina"

[command_tracker_option_minecraft_desc]
other = "spravovat tracker serveru minecraft"

[command_tracker_option_minecraft_option_create]
other = "vytvořit"

[command_tracker_option_minecraft_option_create_desc]
other = "tracker serveru minecraft"

[command_tracker_option_minecraft_option_create_option_address]
other = "Adresa"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "adresa serveru"

[command_tracker_option_minecraft_option_create_option_name]
other = "jméno"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "jméno serveru"

[command_tracker_option_minecraft_option_create_option_port]
other = "přístav"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "port serveru"

[command_tracker_option_minecraft_option_create_option_role]
other = "role"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "role ke zmínění"

[command_unban_desc]
other = "odblokovat vybraného uživatele"

[command_unban_message]
other = "{{.Target}} byl odblokován"

[command_unban_option_desc_target]
other = "odblokovat uživatele"

[command_unban_option_target]
other = "target"

[error]
other = "{{.Error}}"

[error_0]
other = "Došlo k chybě {{.Error}}"

[error_TargetIsBot]
other = "Tohoto bota nelze vybrat jako cíl!"

[error_failed_to_connect_api]
other = "chyba api serveru se nezdařila"

[error_failed_to_ping_server]
other = "pingový server selhal"

[error_invalid_port_value]
other = "neplatná hodnota portu"

[error_message]
other = "Došlo k chybě"

[feed_minecraft_webhook_name]
other = "oznámení serveru"

[latency]
other = "odezva"

[message_command_modify]
other = "upravit"

[panel_minecraft_message_boot]
other = "Spouštěn {{.Name}} server"

[panel_minecraft_message_stop]
other = "zastavil {{.Name}} server"

[panel_role_message_added]
other = "přidáno"

[panel_role_message_removed]
other = "odstraněno"

[players]
other = "hráči"

[port]
other = "přístav"

[version]
other = "verze"

[command_tracker_option_minecraft_option_get]
other = "získej"

[command_tracker_option_minecraft_option_get_desc]
other = "získat trackery minecraft"

[command_tracker_option_minecraft_option_remove]
other = "odstranit"

[command_tracker_option_minecraft_option_remove_desc]
other = "odstranit minecraft trackery"

[channel]
other = "kanál"

[command_tracker_option_minecraft_option_remove_option_name]
other = "jméno"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "název trackeru"

[command_panel_option_minecraft_message]
other = 'To add a server right click or long press on the message and press "Apps" then "modify"'

[command_panel_option_minecraft_placeholder]
other = "Select server"

[command_panel_option_role_message]
other = 'To add a role right click or press and hold on the message and press "Apps" then "modify"'
