[address]
other = "Adresa"

[channel]
other = "kanál"

[client_desktop]
other = "Stolní počítače"

[client_mobile]
other = "Mobil"

[client_web]
other = "Webová"

[command_panel]
other = "panel"

[command_panel_desc]
other = "spravovat nebo vytvářet panel"

[command_panel_option_config]
other = "konfigurace"

[command_panel_option_config_desc]
other = "konfigurovat propruty"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Nastavit vlastní emoji ve vybrané nabídce"

[command_panel_option_config_option_emoji_message]
other = "Zašlete prosím emoji do tohoto kanálu"

[command_panel_option_desc_role]
other = "spravovat panel rolí"

[command_panel_option_minecraft]
other = "těžební plošina"

[command_panel_option_minecraft_desc]
other = "Spravovat panel minecraft"

[command_panel_option_minecraft_message]
other = 'Pro přidání serveru klikněte pravým nebo dlouhým stiskem na zprávě a stiskněte tlačítko "Aplikace" a poté "upravit"'

[command_panel_option_minecraft_option_create]
other = "vytvořit"

[command_panel_option_minecraft_option_create_desc]
other = "vytvořit panel minecraft"

[command_panel_option_minecraft_option_create_option_address]
other = "Adresa"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "adresa serveru"

[command_panel_option_minecraft_option_create_option_description]
other = "Popis"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "popis poradní skupiny"

[command_panel_option_minecraft_option_create_option_name]
other = "jméno"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "název dílce"

[command_panel_option_minecraft_option_create_option_port]
other = "přístav"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "port serveru"

[command_panel_option_minecraft_option_create_option_servername]
other = "jméno serveru"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "jméno serveru"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "zobrazit IP nebo ne"

[command_panel_option_minecraft_placeholder]
other = "Vybrat server"

[command_panel_option_role]
other = "role"

[command_panel_option_role_message]
other = 'Pro přidání role klikněte pravým tlačítkem myši nebo podržte zprávu a stiskněte tlačítko "Aplikace" a poté "upravit"'

[command_panel_option_role_option_create]
other = "vytvořit"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "sesta dílce"

[command_panel_option_role_option_create_option_desc_name]
other = "název dílce"

[command_panel_option_role_option_create_option_desc_role]
other = "role, která přidává do panelu"

[command_panel_option_role_option_create_option_name]
other = "jméno"

[command_panel_option_role_option_create_option_role]
other = "role"

[command_panel_option_role_option_desc_create]
other = "vytvořit panel role"

[command_role]
other = "role"

[command_role_desc]
other = "spravovat roli"

[command_role_option_color]
other = "barva"

[command_role_option_color_desc]
other = "vytvořit barevnou roli"

[command_role_option_color_option_name]
other = "jméno"

[command_role_option_color_option_name_desc]
other = "název role"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "rgb barevný kód"

[command_tracker]
other = "tracker"

[command_tracker_desc]
other = "spravovat nebo vytvářet tracker"

[command_tracker_option_minecraft]
other = "těžební plošina"

[command_tracker_option_minecraft_desc]
other = "spravovat tracker serveru minecraft"

[command_tracker_option_minecraft_option_create]
other = "vytvořit"

[command_tracker_option_minecraft_option_create_desc]
other = "tracker serveru minecraft"

[command_tracker_option_minecraft_option_create_option_address]
other = "Adresa"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "adresa serveru"

[command_tracker_option_minecraft_option_create_option_name]
other = "jméno"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "jméno serveru"

[command_tracker_option_minecraft_option_create_option_port]
other = "přístav"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "port serveru"

[command_tracker_option_minecraft_option_create_option_role]
other = "role"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "role ke zmínění"

[command_tracker_option_minecraft_option_get]
other = "získej"

[command_tracker_option_minecraft_option_get_desc]
other = "získat trackery minecraft"

[command_tracker_option_minecraft_option_remove]
other = "odstranit"

[command_tracker_option_minecraft_option_remove_desc]
other = "odstranit minecraft trackery"

[command_tracker_option_minecraft_option_remove_option_name]
other = "jméno"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "název trackeru"

[error]
other = "{{.Error}}"

[error_0]
other = "Došlo k chybě {{.Error}}"

[error_TargetIsBot]
other = "Tohoto bota nelze vybrat jako cíl!"

[error_bot_does_not_have_permissions]
other = "Nedostatečná oprávnění bota!\rMusí být správcem serveru uděleno oprávnění správce!"

[error_cannot_read_content]
other = "Cant read message content."

[error_cannot_use_roles]
other = "Následující role nelze použít"

[error_failed_to_connect_api]
other = "chyba api serveru se nezdařila"

[error_failed_to_ping_server]
other = "pingový server selhal"

[error_invalid_port_value]
other = "neplatná hodnota portu"

[error_invalid_roles]
other = "Neplatná role"

[error_message]
other = "Došlo k chybě"

[error_unknown_command]
other = "Unkown operation"

[feed_minecraft_webhook_name]
other = "oznámení serveru"

[latency]
other = "odezva"

[message_command_modify]
other = "upravit"

[message_command_select]
other = "vybrat"

[message_command_select_message]
other = "vybráno"

[message_command_user_info]
other = "informace"

[message_command_user_info_color_code]
other = "Kód barvy"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Přidal/a se k"

[message_command_user_info_nick]
other = "Přezdívka"

[message_command_user_info_none]
other = "žádný"

[message_command_user_info_roles]
other = "Role"

[message_command_user_info_status]
other = "Stav"

[message_command_pin]
other = "pin message"

[message_modify_cant_use_this_message_error]
other = "není k dispozici pro tuto zprávu"

[message_modify_role_add_message]
other = "Vyberte roli pro přidání"

[message_modify_role_create_message]
other = "Přetáhni roli pro vytvoření panelu"

[online_status]
other = "Stav"

[panel_minecraft_add_server]
other = "Přidat server"

[panel_minecraft_address]
other = "Adresa"

[panel_minecraft_display_name]
other = "Zobrazované jméno"

[panel_minecraft_message_boot]
other = "spuštěno {{.Name}}"

[panel_minecraft_message_stop]
other = "zastavil {{.Name}}"

[panel_minecraft_my_server]
other = "Můj server"

[panel_minecraft_port]
other = "Přístav"

[panel_role_message_added]
other = "přidáno"

[panel_role_message_removed]
other = "odstraněno"

[players]
other = "hráči"

[port]
other = "přístav"

[version]
other = "verze"
