[address]
other = "adresse"

[channel]
other = "kanal"

[client_desktop]
other = "Skrivebord"

[client_mobile]
other = "Mobil"

[client_web]
other = "Web"

[command_panel]
other = "panel"

[command_panel_desc]
other = "administrer eller opret panel"

[command_panel_option_config]
other = "config"

[command_panel_option_config_desc]
other = "konfigurér proprties"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Indstil brugerdefineret emoji i vælg menu"

[command_panel_option_config_option_emoji_message]
other = "Send venligst emoji i denne kanal"

[command_panel_option_desc_role]
other = "administrer rollepanel"

[command_panel_option_minecraft]
other = "minecraft"

[command_panel_option_minecraft_desc]
other = "administrer minecraft panel"

[command_panel_option_minecraft_message]
other = 'For at tilføje en server højreklik eller langt tryk på beskeden og tryk på "Apps" derefter "ændre"'

[command_panel_option_minecraft_option_create]
other = "opret"

[command_panel_option_minecraft_option_create_desc]
other = "opret minecraft panel"

[command_panel_option_minecraft_option_create_option_address]
other = "adresse"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "adresse på serveren"

[command_panel_option_minecraft_option_create_option_description]
other = "beskrivelse"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "beskrivelse af panelet"

[command_panel_option_minecraft_option_create_option_name]
other = "navn"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "navn på panelet"

[command_panel_option_minecraft_option_create_option_port]
other = "port"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "port på server"

[command_panel_option_minecraft_option_create_option_servername]
other = "servernavn"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "navn på server"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "vis ip eller ej"

[command_panel_option_minecraft_placeholder]
other = "Vælg server"

[command_panel_option_role]
other = "rolle"

[command_panel_option_role_message]
other = 'For at tilføje en rolle højreklik eller tryk og hold på beskeden og tryk på "Apps" og derefter "ændre"'

[command_panel_option_role_option_create]
other = "opret"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "afgrænsning af panelet"

[command_panel_option_role_option_create_option_desc_name]
other = "navn på panelet"

[command_panel_option_role_option_create_option_desc_role]
other = "rolle, der føjer til panelet"

[command_panel_option_role_option_create_option_name]
other = "navn"

[command_panel_option_role_option_create_option_role]
other = "rolle"

[command_panel_option_role_option_desc_create]
other = "opret rollepanel"

[command_role]
other = "rolle"

[command_role_desc]
other = "administrer rolle"

[command_role_option_color]
other = "farve"

[command_role_option_color_desc]
other = "opret farve rolle"

[command_role_option_color_option_name]
other = "navn"

[command_role_option_color_option_name_desc]
other = "navn på rolle"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "rgb farvekode"

[command_tracker]
other = "sporer"

[command_tracker_desc]
other = "administrere eller opret tracker"

[command_tracker_option_minecraft]
other = "minecraft"

[command_tracker_option_minecraft_desc]
other = "administrer minecraft server tracker"

[command_tracker_option_minecraft_option_create]
other = "opret"

[command_tracker_option_minecraft_option_create_desc]
other = "minecraft server tracker"

[command_tracker_option_minecraft_option_create_option_address]
other = "adresse"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "adresse på serveren"

[command_tracker_option_minecraft_option_create_option_name]
other = "navn"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "navn på server"

[command_tracker_option_minecraft_option_create_option_port]
other = "port"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "port på server"

[command_tracker_option_minecraft_option_create_option_role]
other = "rolle"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "rolle at nævne"

[command_tracker_option_minecraft_option_get]
other = "hent"

[command_tracker_option_minecraft_option_get_desc]
other = "hent minecraft trackere"

[command_tracker_option_minecraft_option_remove]
other = "fjern"

[command_tracker_option_minecraft_option_remove_desc]
other = "fjern minecraft trackers"

[command_tracker_option_minecraft_option_remove_option_name]
other = "navn"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "navn på tracker"

[error]
other = "{{.Error}}"

[error_0]
other = "Der opstod en fejl {{.Error}}"

[error_TargetIsBot]
other = "Kan ikke vælge denne bot som mål!"

[error_cannot_use_roles]
other = "Følgende roller kan ikke bruges"

[error_failed_to_connect_api]
other = "fejl i forbindelse med api server"

[error_failed_to_ping_server]
other = "kunne ikke ping af server"

[error_invalid_port_value]
other = "ugyldig portværdi"

[error_invalid_roles]
other = "Ugyldig rolle(r)"

[error_message]
other = "Der opstod en fejl"

[feed_minecraft_webhook_name]
other = "server notifikation"

[latency]
other = "latens"

[message_command_modify]
other = "ændre"

[message_command_select]
other = "vælg"

[message_command_select_message]
other = "valgt"

[message_command_user_info]
other = "info"

[message_command_user_info_color_code]
other = "Farve Kode"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Tilmeldt på"

[message_command_user_info_nick]
other = "Nick"

[message_command_user_info_none]
other = "ingen"

[message_command_user_info_roles]
other = "Roller"

[message_command_user_info_status]
other = "Status"

[message_modify_cant_use_this_message_error]
other = "ikke tilgængelig for denne besked"

[message_modify_role_add_message]
other = "Vælg en rolle at tilføje"

[message_modify_role_create_message]
other = "Coose en rolle at oprette panel"

[online_status]
other = "Status"

[panel_minecraft_add_server]
other = "Tilføj en server"

[panel_minecraft_address]
other = "Adresse"

[panel_minecraft_display_name]
other = "Vis Navn"

[panel_minecraft_message_boot]
other = "startet {{.Name}}"

[panel_minecraft_message_stop]
other = "stoppede {{.Name}}"

[panel_minecraft_my_server]
other = "Min server"

[panel_minecraft_port]
other = "Port"

[panel_role_message_added]
other = "tilføjet"

[panel_role_message_removed]
other = "fjernet"

[players]
other = "spillere"

[port]
other = "port"

[version]
other = "version"
