[address]
other = "adresse"

[channel]
other = "kanal"

[client_desktop]
other = "Desktop"

[client_mobile]
other = "Mobil"

[client_web]
other = "Web"

[command_panel]
other = "panel"

[command_panel_desc]
other = "verwalten oder Panel erstellen"

[command_panel_option_config]
other = "Konfiguration"

[command_panel_option_config_desc]
other = "konfiguriere Proprties"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Eigene Emoji im Auswahlmenü festlegen"

[command_panel_option_config_option_emoji_message]
other = "Bitte sende Emoji in diesem Kanal"

[command_panel_option_desc_role]
other = "verwalte Rollen"

[command_panel_option_minecraft]
other = "minecraft"

[command_panel_option_minecraft_desc]
other = "minecraft-Panel verwalten"

[command_panel_option_minecraft_message]
other = 'Um einen Server hinzuzufügen, klicken Sie mit der rechten Maustaste oder drücken Sie lange auf die Nachricht und drücken Sie "Apps" und dann "ändern"'

[command_panel_option_minecraft_option_create]
other = "erstellen"

[command_panel_option_minecraft_option_create_desc]
other = "erstelle Minecraft-Panel"

[command_panel_option_minecraft_option_create_option_address]
other = "adresse"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "Adresse des Servers"

[command_panel_option_minecraft_option_create_option_description]
other = "beschreibung"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "Beschreibung des Panels"

[command_panel_option_minecraft_option_create_option_name]
other = "name"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "Name des Panels"

[command_panel_option_minecraft_option_create_option_port]
other = "port"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "port des Servers"

[command_panel_option_minecraft_option_create_option_servername]
other = "servername"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "Name des Servers"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "zeige ip oder nicht"

[command_panel_option_minecraft_placeholder]
other = "Server auswählen"

[command_panel_option_role]
other = "rolle"

[command_panel_option_role_message]
other = 'Um eine Rolle hinzuzufügen, klicken Sie mit der rechten Maustaste oder drücken Sie die Nachricht und drücken Sie "Apps" und dann "ändern"'

[command_panel_option_role_option_create]
other = "erstellen"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "desc des Panels"

[command_panel_option_role_option_create_option_desc_name]
other = "Name des Panels"

[command_panel_option_role_option_create_option_desc_role]
other = "Rolle, die dem Panel hinzugefügt wird"

[command_panel_option_role_option_create_option_name]
other = "name"

[command_panel_option_role_option_create_option_role]
other = "rolle"

[command_panel_option_role_option_desc_create]
other = "erstelle Rollen-Panel"

[command_role]
other = "rolle"

[command_role_desc]
other = "Rolle verwalten"

[command_role_option_color]
other = "farben"

[command_role_option_color_desc]
other = "erstelle Farbrolle"

[command_role_option_color_option_name]
other = "name"

[command_role_option_color_option_name_desc]
other = "name der Rolle"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "rgb Farbcode"

[command_tracker]
other = "tracker"

[command_tracker_desc]
other = "verwalten oder Tracker erstellen"

[command_tracker_option_minecraft]
other = "minecraft"

[command_tracker_option_minecraft_desc]
other = "minecraft Server Tracker verwalten"

[command_tracker_option_minecraft_option_create]
other = "erstellen"

[command_tracker_option_minecraft_option_create_desc]
other = "minecraft Server Tracker"

[command_tracker_option_minecraft_option_create_option_address]
other = "adresse"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "Adresse des Servers"

[command_tracker_option_minecraft_option_create_option_name]
other = "name"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "Name des Servers"

[command_tracker_option_minecraft_option_create_option_port]
other = "port"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "port des Servers"

[command_tracker_option_minecraft_option_create_option_role]
other = "rolle"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "zu nennende Rolle"

[command_tracker_option_minecraft_option_get]
other = "holen"

[command_tracker_option_minecraft_option_get_desc]
other = "erhalte Minecraft-Tracker"

[command_tracker_option_minecraft_option_remove]
other = "entfernen"

[command_tracker_option_minecraft_option_remove_desc]
other = "minecraft-Tracker entfernen"

[command_tracker_option_minecraft_option_remove_option_name]
other = "name"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "Name des Trackers"

[error]
other = "{{.Error}}"

[error_0]
other = "Ein Fehler ist aufgetreten {{.Error}}"

[error_TargetIsBot]
other = "Dieser Bot kann nicht als Ziel ausgewählt werden!"

[error_bot_does_not_have_permissions]
other = "Unzureichende Bot-Berechtigungen!\rDer Server-Administrator muss ihm Administratorrechte erteilen, um zu funktionieren!"

[error_cannot_use_roles]
other = "Die folgenden Rollen können nicht verwendet werden"

[error_failed_to_connect_api]
other = "konnte Api-Server nicht verbinden"

[error_failed_to_ping_server]
other = "konnte Server nicht pingen"

[error_invalid_port_value]
other = "ungültiger Port-Wert"

[error_invalid_roles]
other = "Ungültige Rolle(n)"

[error_message]
other = "Ein Fehler ist aufgetreten"

[error_unknown_command]
other = "Unbekannter Vorgang"

[feed_minecraft_webhook_name]
other = "server notifier"

[latency]
other = "latenz"

[message_command_modify]
other = "ändern"

[message_command_select]
other = "wählen"

[message_command_select_message]
other = "ausgewählt"

[message_command_user_info]
other = "info"

[message_command_user_info_color_code]
other = "Farbcode"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Beitreten bei"

[message_command_user_info_nick]
other = "Nick"

[message_command_user_info_none]
other = "keine"

[message_command_user_info_roles]
other = "Rollen"

[message_command_user_info_status]
other = "Status"

[message_modify_cant_use_this_message_error]
other = "nicht verfügbar für diese Nachricht"

[message_modify_role_add_message]
other = "Rolle zum Hinzufügen auswählen"

[message_modify_role_create_message]
other = "Rolle kochen, um Panel zu erstellen"

[online_status]
other = "Status"

[panel_minecraft_add_server]
other = "Server hinzufügen"

[panel_minecraft_address]
other = "Adresse"

[panel_minecraft_display_name]
other = "Anzeigename"

[panel_minecraft_message_boot]
other = "{{.Name}} gebootet"

[panel_minecraft_message_stop]
other = "gestoppt {{.Name}}"

[panel_minecraft_my_server]
other = "Mein Server"

[panel_minecraft_port]
other = "Port"

[panel_role_message_added]
other = "hinzugefügt"

[panel_role_message_removed]
other = "entfernt"

[players]
other = "spieler"

[port]
other = "port"

[version]
other = "version"
