[address]
other = "dirección"

[command_ban_desc]
other = "banear al usuario seleccionado"

[command_ban_message]
other = "{{.Target}} ha sido baneado"

[command_ban_option_desc_reason]
other = "razón para banear"

[command_ban_option_desc_target]
other = "usuario a banear"

[command_ban_option_reason]
other = "razón"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Razón: {{.Reason}}"
other = "Razones: {{.Reason}}"

[command_kick_desc]
other = "expulsar al usuario seleccionado"

[command_kick_message]
other = "{{.Target}} ha sido expulsado"

[command_kick_option_desc_target]
other = "usuario a expulsar"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "administrar o crear panel"

[command_panel_option_desc_role]
other = "administrar panel de roles"

[command_panel_option_minecraft]
other = "minecraft"

[command_panel_option_minecraft_desc]
other = "administrar panel de minecraft"

[command_panel_option_minecraft_option_create]
other = "crear"

[command_panel_option_minecraft_option_create_desc]
other = "crear panel de minecraft"

[command_panel_option_minecraft_option_create_option_address]
other = "dirección"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "dirección del servidor"

[command_panel_option_minecraft_option_create_option_description]
other = "descripción"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "descripción del panel"

[command_panel_option_minecraft_option_create_option_name]
other = "nombre"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "nombre del panel"

[command_panel_option_minecraft_option_create_option_port]
other = "puerto"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "puerto del servidor"

[command_panel_option_minecraft_option_create_option_servername]
other = "nombre del servidor"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "nombre del servidor"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "mostrar ip o no"

[command_panel_option_role]
other = "rol"

[command_panel_option_role_option_create]
other = "crear"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "desc del panel"

[command_panel_option_role_option_create_option_desc_name]
other = "nombre del panel"

[command_panel_option_role_option_create_option_desc_role]
other = "rol que añade al panel"

[command_panel_option_role_option_create_option_name]
other = "nombre"

[command_panel_option_role_option_create_option_role]
other = "rol"

[command_panel_option_role_option_desc_create]
other = "crear panel de roles"

[command_tracker]
other = "rastreador"

[command_tracker_desc]
other = "administrar o crear rastreador"

[command_tracker_option_minecraft]
other = "minecraft"

[command_tracker_option_minecraft_desc]
other = "administrar el rastreador de servidor de minecraft"

[command_tracker_option_minecraft_option_create]
other = "crear"

[command_tracker_option_minecraft_option_create_desc]
other = "rastreador de servidor de minecraft"

[command_tracker_option_minecraft_option_create_option_address]
other = "dirección"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "dirección del servidor"

[command_tracker_option_minecraft_option_create_option_name]
other = "nombre"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "nombre del servidor"

[command_tracker_option_minecraft_option_create_option_port]
other = "puerto"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "puerto del servidor"

[command_tracker_option_minecraft_option_create_option_role]
other = "rol"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "rol a mencionar"

[command_unban_desc]
other = "desbanear al usuario seleccionado"

[command_unban_message]
other = "{{.Target}} ha sido desbaneado"

[command_unban_option_desc_target]
other = "usuario a desbanear"

[command_unban_option_target]
other = "target"

[error]
other = "{{.Error}}"

[error_0]
other = "Ha ocurrido un error {{.Error}}"

[error_TargetIsBot]
other = "¡No se puede seleccionar este bot como objetivo!"

[error_failed_to_connect_api]
other = "error al conectar el servidor api"

[error_failed_to_ping_server]
other = "fallo en el servidor ping"

[error_invalid_port_value]
other = "valor de puerto inválido"

[error_message]
other = "Ha ocurrido un error"

[feed_minecraft_webhook_name]
other = "notificador de servidor"

[latency]
other = "latencia"

[message_command_modify]
other = "modificar"

[panel_minecraft_message_boot]
other = "servidor {{.Name}} iniciado"

[panel_minecraft_message_stop]
other = "ha detenido el servidor {{.Name}}"

[panel_role_message_added]
other = "añadido"

[panel_role_message_removed]
other = "eliminado"

[players]
other = "jugadores"

[port]
other = "puerto"

[version]
other = "versión"

[command_tracker_option_minecraft_option_get]
other = "obtener"

[command_tracker_option_minecraft_option_get_desc]
other = "obtener rastreadores de minecraft"

[command_tracker_option_minecraft_option_remove]
other = "eliminar"

[command_tracker_option_minecraft_option_remove_desc]
other = "eliminar rastreadores de minecraft"

[channel]
other = "canal"

[command_tracker_option_minecraft_option_remove_option_name]
other = "nombre"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "nombre del rastreador"

[command_panel_option_minecraft_message]
other = 'To add a server right click or long press on the message and press "Apps" then "modify"'

[command_panel_option_minecraft_placeholder]
other = "Select server"

[command_panel_option_role_message]
other = 'To add a role right click or press and hold on the message and press "Apps" then "modify"'

[command_role]
other = "role"

[command_role_desc]
other = "manage role"

[command_role_option_color]
other = "color"

[command_role_option_color_desc]
other = "create color role"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "rgb color code"

[command_role_option_color_option_name]
other = "name"

[command_role_option_color_option_name_desc]
other = "name of role"

[message_command_user_info]
other = "info"

[message_command_user_info_none]
other = "none"

[message_command_user_info_nick]
other = "Nick"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_roles]
other = "Roles"

[message_command_user_info_joined_at]
other = "Joined at"

[message_command_user_info_color_code]
other = "Color Code"
