[address]
other = "dirección"

[channel]
other = "canal"

[client_desktop]
other = "Escritorio"

[client_mobile]
other = "Móvil"

[client_web]
other = "Web"

[command_panel]
other = "panel"

[command_panel_desc]
other = "administrar o crear panel"

[command_panel_option_config]
other = "configuración"

[command_panel_option_config_desc]
other = "configurar propiedades"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Establecer emoji personalizado en el menú de selección"

[command_panel_option_config_option_emoji_message]
other = "Por favor, envía emoji en este canal"

[command_panel_option_desc_role]
other = "administrar panel de roles"

[command_panel_option_minecraft]
other = "minecraft"

[command_panel_option_minecraft_desc]
other = "administrar panel de minecraft"

[command_panel_option_minecraft_message]
other = 'Para añadir un servidor haga clic derecho o mantenga presionado el mensaje y pulse "Aplicaciones" y luego "modificar"'

[command_panel_option_minecraft_option_create]
other = "crear"

[command_panel_option_minecraft_option_create_desc]
other = "crear panel de minecraft"

[command_panel_option_minecraft_option_create_option_address]
other = "dirección"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "dirección del servidor"

[command_panel_option_minecraft_option_create_option_description]
other = "descripción"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "descripción del panel"

[command_panel_option_minecraft_option_create_option_name]
other = "nombre"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "nombre del panel"

[command_panel_option_minecraft_option_create_option_port]
other = "puerto"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "puerto del servidor"

[command_panel_option_minecraft_option_create_option_servername]
other = "nombre del servidor"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "nombre del servidor"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "mostrar ip o no"

[command_panel_option_minecraft_placeholder]
other = "Seleccionar servidor"

[command_panel_option_role]
other = "rol"

[command_panel_option_role_message]
other = 'Para añadir un rol haga clic derecho o presione y mantenga pulsado el mensaje y pulse "Aplicaciones" y luego "modificar"'

[command_panel_option_role_option_create]
other = "crear"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "desc del panel"

[command_panel_option_role_option_create_option_desc_name]
other = "nombre del panel"

[command_panel_option_role_option_create_option_desc_role]
other = "rol que añade al panel"

[command_panel_option_role_option_create_option_name]
other = "nombre"

[command_panel_option_role_option_create_option_role]
other = "rol"

[command_panel_option_role_option_desc_create]
other = "crear panel de roles"

[command_role]
other = "rol"

[command_role_desc]
other = "administrar rol"

[command_role_option_color]
other = "color"

[command_role_option_color_desc]
other = "crear rol de color"

[command_role_option_color_option_name]
other = "nombre"

[command_role_option_color_option_name_desc]
other = "nombre del rol"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "código de color rgb"

[command_tracker]
other = "rastreador"

[command_tracker_desc]
other = "administrar o crear rastreador"

[command_tracker_option_minecraft]
other = "minecraft"

[command_tracker_option_minecraft_desc]
other = "administrar el rastreador de servidor de minecraft"

[command_tracker_option_minecraft_option_create]
other = "crear"

[command_tracker_option_minecraft_option_create_desc]
other = "rastreador de servidor de minecraft"

[command_tracker_option_minecraft_option_create_option_address]
other = "dirección"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "dirección del servidor"

[command_tracker_option_minecraft_option_create_option_name]
other = "nombre"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "nombre del servidor"

[command_tracker_option_minecraft_option_create_option_port]
other = "puerto"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "puerto del servidor"

[command_tracker_option_minecraft_option_create_option_role]
other = "rol"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "rol a mencionar"

[command_tracker_option_minecraft_option_get]
other = "obtener"

[command_tracker_option_minecraft_option_get_desc]
other = "obtener rastreadores de minecraft"

[command_tracker_option_minecraft_option_remove]
other = "eliminar"

[command_tracker_option_minecraft_option_remove_desc]
other = "eliminar rastreadores de minecraft"

[command_tracker_option_minecraft_option_remove_option_name]
other = "nombre"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "nombre del rastreador"

[error]
other = "{{.Error}}"

[error_0]
other = "Ha ocurrido un error {{.Error}}"

[error_TargetIsBot]
other = "¡No se puede seleccionar este bot como objetivo!"

[error_cannot_use_roles]
other = "No se pueden utilizar los siguientes roles"

[error_failed_to_connect_api]
other = "error al conectar el servidor api"

[error_failed_to_ping_server]
other = "fallo en el servidor ping"

[error_invalid_port_value]
other = "valor de puerto inválido"

[error_invalid_roles]
other = "Roles no válidos"

[error_message]
other = "Ha ocurrido un error"

[feed_minecraft_webhook_name]
other = "notificador de servidor"

[latency]
other = "latencia"

[message_command_modify]
other = "modificar"

[message_command_select]
other = "seleccionar"

[message_command_select_message]
other = "seleccionado"

[message_command_user_info]
other = "info"

[message_command_user_info_color_code]
other = "Código de color"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Se unió en"

[message_command_user_info_nick]
other = "Apodo"

[message_command_user_info_none]
other = "ninguno"

[message_command_user_info_roles]
other = "Roles"

[message_command_user_info_status]
other = "Estado"

[message_modify_cant_use_this_message_error]
other = "no disponible para ese mensaje"

[message_modify_role_add_message]
other = "Elegir un rol a añadir"

[message_modify_role_create_message]
other = "Oculta un rol para crear el panel"

[online_status]
other = "Estado"

[panel_minecraft_add_server]
other = "Añadir un servidor"

[panel_minecraft_address]
other = "Dirección"

[panel_minecraft_display_name]
other = "Mostrar nombre"

[panel_minecraft_message_boot]
other = "arrancó {{.Name}}"

[panel_minecraft_message_stop]
other = "ha detenido {{.Name}}"

[panel_minecraft_my_server]
other = "Mi servidor"

[panel_minecraft_port]
other = "Puerto"

[panel_role_message_added]
other = "añadido"

[panel_role_message_removed]
other = "eliminado"

[players]
other = "jugadores"

[port]
other = "puerto"

[version]
other = "versión"
