[address]
other = "adresse"

[channel]
other = "canal"

[client_desktop]
other = "Bureau"

[client_mobile]
other = "Téléphone mobile"

[client_web]
other = "Web"

[command_panel]
other = "panneau"

[command_panel_desc]
other = "gérer ou créer un panneau"

[command_panel_option_config]
other = "Configuration"

[command_panel_option_config_desc]
other = "configurer les proprties"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Définir les émojis personnalisés dans le menu de sélection"

[command_panel_option_config_option_emoji_message]
other = "Veuillez envoyer des émojis dans ce canal"

[command_panel_option_desc_role]
other = "gérer le panneau des rôles"

[command_panel_option_minecraft]
other = "minecraft"

[command_panel_option_minecraft_desc]
other = "gérer le panneau minecraft"

[command_panel_option_minecraft_message]
other = 'Pour ajouter un serveur cliquez avec le bouton droit de la souris ou appuyez longuement sur le message et appuyez sur "Apps" puis "modifier"'

[command_panel_option_minecraft_option_create]
other = "créer"

[command_panel_option_minecraft_option_create_desc]
other = "créer un panneau minecraft"

[command_panel_option_minecraft_option_create_option_address]
other = "adresse"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "adresse du serveur"

[command_panel_option_minecraft_option_create_option_description]
other = "Libellé"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "description du panneau"

[command_panel_option_minecraft_option_create_option_name]
other = "Nom"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "nom du panneau"

[command_panel_option_minecraft_option_create_option_port]
other = "port"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "port du serveur"

[command_panel_option_minecraft_option_create_option_servername]
other = "nom du serveur"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "nom du serveur"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "afficher l'IP ou pas"

[command_panel_option_minecraft_placeholder]
other = "Sélectionnez le serveur"

[command_panel_option_role]
other = "Rôle"

[command_panel_option_role_message]
other = 'Pour ajouter un rôle cliquez avec le bouton droit de la souris ou maintenez appuyé sur le message et appuyez sur "Apps" puis "modifier"'

[command_panel_option_role_option_create]
other = "créer"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "desc du panneau"

[command_panel_option_role_option_create_option_desc_name]
other = "nom du panneau"

[command_panel_option_role_option_create_option_desc_role]
other = "rôle qui s'ajoute au panneau"

[command_panel_option_role_option_create_option_name]
other = "Nom"

[command_panel_option_role_option_create_option_role]
other = "Rôle"

[command_panel_option_role_option_desc_create]
other = "créer un panneau de rôle"

[command_role]
other = "Rôle"

[command_role_desc]
other = "gérer le rôle"

[command_role_option_color]
other = "couleur"

[command_role_option_color_desc]
other = "créer un rôle de couleur"

[command_role_option_color_option_name]
other = "Nom"

[command_role_option_color_option_name_desc]
other = "nom du rôle"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "code couleur rgb"

[command_tracker]
other = "tracker"

[command_tracker_desc]
other = "gérer ou créer un tracker"

[command_tracker_option_minecraft]
other = "minecraft"

[command_tracker_option_minecraft_desc]
other = "gérer le tracker de serveur minecraft"

[command_tracker_option_minecraft_option_create]
other = "créer"

[command_tracker_option_minecraft_option_create_desc]
other = "tracker serveur minecraft"

[command_tracker_option_minecraft_option_create_option_address]
other = "adresse"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "adresse du serveur"

[command_tracker_option_minecraft_option_create_option_name]
other = "Nom"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "nom du serveur"

[command_tracker_option_minecraft_option_create_option_port]
other = "port"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "port du serveur"

[command_tracker_option_minecraft_option_create_option_role]
other = "Rôle"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "rôle à mentionner"

[command_tracker_option_minecraft_option_get]
other = "obtenir"

[command_tracker_option_minecraft_option_get_desc]
other = "obtenir des traqueurs de minecraft"

[command_tracker_option_minecraft_option_remove]
other = "Enlever"

[command_tracker_option_minecraft_option_remove_desc]
other = "supprimer les traceurs de minecraft"

[command_tracker_option_minecraft_option_remove_option_name]
other = "Nom"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "nom du tracker"

[error]
other = "{{.Error}}"

[error_0]
other = "Une erreur s'est produite {{.Error}}"

[error_TargetIsBot]
other = "Impossible de sélectionner ce bot comme cible !"

[error_bot_does_not_have_permissions]
other = "Permissions de bot insuffisantes !\rIl doit être donné à l'administrateur par l'administrateur du serveur pour fonctionner !"

[error_cannot_use_roles]
other = "Les rôles suivants ne peuvent pas être utilisés"

[error_failed_to_connect_api]
other = "impossible de se connecter au serveur api"

[error_failed_to_ping_server]
other = "échec du ping du serveur"

[error_invalid_port_value]
other = "valeur de port invalide"

[error_invalid_roles]
other = "Rôle(s) non valide"

[error_message]
other = "Une erreur est survenue"

[error_unknown_command]
other = "Opération inconnue"

[feed_minecraft_webhook_name]
other = "serveur de notification"

[latency]
other = "latence"

[message_command_modify]
other = "modifier"

[message_command_select]
other = "sélectionner"

[message_command_select_message]
other = "slectionns"

[message_command_user_info]
other = "Infos"

[message_command_user_info_color_code]
other = "Code de couleur"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Inscrit le"

[message_command_user_info_nick]
other = "Pseudo"

[message_command_user_info_none]
other = "aucun"

[message_command_user_info_roles]
other = "Rôles"

[message_command_user_info_status]
other = "Statut"

[message_modify_cant_use_this_message_error]
other = "non disponible pour ce message"

[message_modify_role_add_message]
other = "Choisissez un rôle à ajouter"

[message_modify_role_create_message]
other = "Coose un rôle pour créer un panneau"

[online_status]
other = "Statut"

[panel_minecraft_add_server]
other = "Ajouter un serveur"

[panel_minecraft_address]
other = "Adresses"

[panel_minecraft_display_name]
other = "Nom affiché"

[panel_minecraft_message_boot]
other = "a démarré {{.Name}}"

[panel_minecraft_message_stop]
other = "arrêté {{.Name}}"

[panel_minecraft_my_server]
other = "Mon serveur"

[panel_minecraft_port]
other = "Port"

[panel_role_message_added]
other = "Ajouté"

[panel_role_message_removed]
other = "enlevé"

[players]
other = "joueurs"

[port]
other = "port"

[version]
other = "version"
