[address]
other = "adresse"

[command_ban_desc]
other = "bannir l'utilisateur sélectionné"

[command_ban_message]
other = "{{.Target}} a été banni"

[command_ban_option_desc_reason]
other = "raison du bannissement"

[command_ban_option_desc_target]
other = "utilisateur à bannir"

[command_ban_option_reason]
other = "Raison"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Raison : {{.Reason}}"
other = "Raisons : {{.Reason}}"

[command_kick_desc]
other = "expulser l'utilisateur sélectionné"

[command_kick_message]
other = "{{.Target}} a été éjecté"

[command_kick_option_desc_target]
other = "utilisateur à expulser"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "gérer ou créer un panneau"

[command_panel_option_desc_role]
other = "gérer le panneau des rôles"

[command_panel_option_minecraft]
other = "minecraft"

[command_panel_option_minecraft_desc]
other = "gérer le panneau minecraft"

[command_panel_option_minecraft_option_create]
other = "créer"

[command_panel_option_minecraft_option_create_desc]
other = "créer un panneau minecraft"

[command_panel_option_minecraft_option_create_option_address]
other = "adresse"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "adresse du serveur"

[command_panel_option_minecraft_option_create_option_description]
other = "Libellé"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "description du panneau"

[command_panel_option_minecraft_option_create_option_name]
other = "Nom"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "nom du panneau"

[command_panel_option_minecraft_option_create_option_port]
other = "port"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "port du serveur"

[command_panel_option_minecraft_option_create_option_servername]
other = "nom du serveur"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "nom du serveur"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "afficher l'IP ou pas"

[command_panel_option_role]
other = "Rôle"

[command_panel_option_role_option_create]
other = "créer"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "desc du panneau"

[command_panel_option_role_option_create_option_desc_name]
other = "nom du panneau"

[command_panel_option_role_option_create_option_desc_role]
other = "rôle qui s'ajoute au panneau"

[command_panel_option_role_option_create_option_name]
other = "Nom"

[command_panel_option_role_option_create_option_role]
other = "Rôle"

[command_panel_option_role_option_desc_create]
other = "créer un panneau de rôle"

[command_tracker]
other = "tracker"

[command_tracker_desc]
other = "gérer ou créer un tracker"

[command_tracker_option_minecraft]
other = "minecraft"

[command_tracker_option_minecraft_desc]
other = "gérer le tracker de serveur minecraft"

[command_tracker_option_minecraft_option_create]
other = "créer"

[command_tracker_option_minecraft_option_create_desc]
other = "tracker serveur minecraft"

[command_tracker_option_minecraft_option_create_option_address]
other = "adresse"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "adresse du serveur"

[command_tracker_option_minecraft_option_create_option_name]
other = "Nom"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "nom du serveur"

[command_tracker_option_minecraft_option_create_option_port]
other = "port"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "port du serveur"

[command_tracker_option_minecraft_option_create_option_role]
other = "Rôle"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "rôle à mentionner"

[command_unban_desc]
other = "dé-bannir l'utilisateur sélectionné"

[command_unban_message]
other = "{{.Target}} a été débanni"

[command_unban_option_desc_target]
other = "utilisateur à débannir"

[command_unban_option_target]
other = "target"

[error]
other = "{{.Error}}"

[error_0]
other = "Une erreur s'est produite {{.Error}}"

[error_TargetIsBot]
other = "Impossible de sélectionner ce bot comme cible !"

[error_failed_to_connect_api]
other = "impossible de se connecter au serveur api"

[error_failed_to_ping_server]
other = "échec du ping du serveur"

[error_invalid_port_value]
other = "valeur de port invalide"

[error_message]
other = "Une erreur est survenue"

[feed_minecraft_webhook_name]
other = "serveur de notification"

[latency]
other = "latence"

[message_command_modify]
other = "modifier"

[panel_minecraft_message_boot]
other = "a démarré le serveur {{.Name}}"

[panel_minecraft_message_stop]
other = "serveur {{.Name}} arrêté"

[panel_role_message_added]
other = "Ajouté"

[panel_role_message_removed]
other = "enlevé"

[players]
other = "joueurs"

[port]
other = "port"

[version]
other = "version"

[command_tracker_option_minecraft_option_get]
other = "obtenir"

[command_tracker_option_minecraft_option_get_desc]
other = "obtenir des traqueurs de minecraft"

[command_tracker_option_minecraft_option_remove]
other = "Enlever"

[command_tracker_option_minecraft_option_remove_desc]
other = "supprimer les traceurs de minecraft"

[channel]
other = "canal"

[command_tracker_option_minecraft_option_remove_option_name]
other = "Nom"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "nom du tracker"

[command_panel_option_minecraft_message]
other = 'To add a server right click or long press on the message and press "Apps" then "modify"'

[command_panel_option_minecraft_placeholder]
other = "Select server"

[command_panel_option_role_message]
other = 'To add a role right click or press and hold on the message and press "Apps" then "modify"'
