[address]
other = "indirizzo"

[channel]
other = "canale"

[command_ban]
other = "ban"

[command_ban_desc]
other = "bandisce l'utente selezionato"

[command_ban_message]
other = "{{.Target}} è stato bannato"

[command_ban_option_desc_reason]
other = "motivo del divieto"

[command_ban_option_desc_target]
other = "utente da bandire"

[command_ban_option_reason]
other = "motivo"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Motivo: {{.Reason}}"
other = "Motivi: {{.Reason}}"

[command_kick]
other = "espulso"

[command_kick_desc]
other = "espulso l'utente selezionato"

[command_kick_message]
other = "{{.Target}} è stato espulso"

[command_kick_option_desc_target]
other = "utente da espellere"

[command_kick_option_target]
other = "target"

[command_panel]
other = "pannello"

[command_panel_desc]
other = "gestire o creare un pannello"

[command_panel_option_desc_role]
other = "gestire il pannello ruoli"

[command_panel_option_minecraft]
other = "minecraft"

[command_panel_option_minecraft_desc]
other = "gestire pannello minecraft"

[command_panel_option_minecraft_message]
other = 'Per aggiungere un server fare clic con il tasto destro o premere a lungo sul messaggio e premere "Apps" quindi "modifica"'

[command_panel_option_minecraft_option_create]
other = "crea"

[command_panel_option_minecraft_option_create_desc]
other = "crea pannello minecraft"

[command_panel_option_minecraft_option_create_option_address]
other = "indirizzo"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "indirizzo del server"

[command_panel_option_minecraft_option_create_option_description]
other = "descrizione"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "descrizione del pannello"

[command_panel_option_minecraft_option_create_option_name]
other = "nome"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "nome del pannello"

[command_panel_option_minecraft_option_create_option_port]
other = "porta"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "porta del server"

[command_panel_option_minecraft_option_create_option_servername]
other = "servername"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "nome del server"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "mostra ip o no"

[command_panel_option_minecraft_placeholder]
other = "Seleziona server"

[command_panel_option_role]
other = "ruolo"

[command_panel_option_role_message]
other = 'Per aggiungere un ruolo, clicca con il tasto destro o tieni premuto il messaggio e premi "Apps" e poi "modifica"'

[command_panel_option_role_option_create]
other = "crea"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "desc del pannello"

[command_panel_option_role_option_create_option_desc_name]
other = "nome del pannello"

[command_panel_option_role_option_create_option_desc_role]
other = "ruolo che si aggiunge al pannello"

[command_panel_option_role_option_create_option_name]
other = "nome"

[command_panel_option_role_option_create_option_role]
other = "ruolo"

[command_panel_option_role_option_desc_create]
other = "crea pannello ruolo"

[command_role]
other = "ruolo"

[command_role_desc]
other = "gestisci ruolo"

[command_role_option_color]
other = "colore"

[command_role_option_color_desc]
other = "crea ruolo colore"

[command_role_option_color_option_name]
other = "nome"

[command_role_option_color_option_name_desc]
other = "nome del ruolo"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "codice colore rgb"

[command_tracker]
other = "tracker"

[command_tracker_desc]
other = "gestisci o crea tracker"

[command_tracker_option_minecraft]
other = "minecraft"

[command_tracker_option_minecraft_desc]
other = "gestisci server tracker di minecraft"

[command_tracker_option_minecraft_option_create]
other = "crea"

[command_tracker_option_minecraft_option_create_desc]
other = "minecraft server tracker"

[command_tracker_option_minecraft_option_create_option_address]
other = "indirizzo"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "indirizzo del server"

[command_tracker_option_minecraft_option_create_option_name]
other = "nome"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "nome del server"

[command_tracker_option_minecraft_option_create_option_port]
other = "porta"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "porta del server"

[command_tracker_option_minecraft_option_create_option_role]
other = "ruolo"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "ruolo da menzionare"

[command_tracker_option_minecraft_option_get]
other = "ottieni"

[command_tracker_option_minecraft_option_get_desc]
other = "ottieni tracker minecraft"

[command_tracker_option_minecraft_option_remove]
other = "rimuovi"

[command_tracker_option_minecraft_option_remove_desc]
other = "rimuovi minecraft trackers"

[command_tracker_option_minecraft_option_remove_option_name]
other = "nome"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "nome del tracker"

[command_unban]
other = "unban"

[command_unban_desc]
other = "disattiva l'utente selezionato"

[command_unban_message]
other = "{{.Target}} è stato sbannato"

[command_unban_option_desc_target]
other = "utente da sbloccare"

[command_unban_option_target]
other = "target"

[error]
other = "{{.Error}}"

[error_0]
other = "Si è verificato un errore {{.Error}}"

[error_TargetIsBot]
other = "Non è possibile selezionare questo bot come obiettivo!"

[error_failed_to_connect_api]
other = "errore di connessione del server api non riuscito"

[error_failed_to_ping_server]
other = "ping del server non riuscito"

[error_invalid_port_value]
other = "valore porta non valido"

[error_invalid_roles]
other = "Ruoli non validi"

[error_cannot_use_roles]
other = "I seguenti ruoli non possono essere utilizzati"

[error_message]
other = "Si è verificato un errore"

[feed_minecraft_webhook_name]
other = "notificatore server"

[latency]
other = "latenza"

[message_command_modify]
other = "modifica"

[message_command_user_info]
other = "info"

[message_command_user_info_color_code]
other = "Codice Colore"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Iscritto il"

[message_command_user_info_nick]
other = "Nick"

[message_command_user_info_none]
other = "nessuno"

[message_command_user_info_roles]
other = "Ruoli"

[panel_minecraft_message_boot]
other = "avviato {{.Name}}"

[panel_minecraft_message_stop]
other = "fermato {{.Name}}"

[panel_role_message_added]
other = "aggiunto"

[panel_role_message_removed]
other = "rimosso"

[players]
other = "giocatori"

[port]
other = "porta"

[version]
other = "versione"

[message_modify_cant_use_this_message_error]
other = "non disponibile per quel messaggio"

[message_modify_role_add_message]
other = "Scegli un ruolo da aggiungere"

[message_modify_role_create_message]
other = "Scegli un ruolo per creare un pannello"

[message_command_select_message]
other = "selezionato"

[message_command_select]
other = "seleziona"

[command_panel_option_config]
other = "configurazione"

[command_panel_option_config_desc]
other = "configura proprities"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Imposta emoji personalizzate nel menu di selezione"

[command_panel_option_config_option_emoji_message]
other = "Invia emoji in questo canale"

[panel_minecraft_display_name]
other = "Nome Visualizzato"

[panel_minecraft_address]
other = "Indirizzo"

[panel_minecraft_my_server]
other = "Il mio server"

[panel_minecraft_port]
other = "Porta"

[panel_minecraft_add_server]
other = "Aggiungi un server"
