[address]
other = "アドレス"

[channel]
other = "チャンネル"

[command_ban]
other = "ban"

[command_ban_desc]
other = "選択したユーザーをBANします"

[command_ban_message]
other = "{{.Target}} はBANされました"

[command_ban_option_desc_reason]
other = "BANの理由"

[command_ban_option_desc_target]
other = "BANするユーザー"

[command_ban_option_reason]
other = "理由"

[command_ban_option_target]
other = "対象"

[command_ban_reason]
one = "理由: {{.Reason}}"
other = "理由: {{.Reason}}"

[command_kick]
other = "kick"

[command_kick_desc]
other = "選択したユーザーをキックする"

[command_kick_message]
other = "{{.Target}} がキックされました"

[command_kick_option_desc_target]
other = "キックするユーザー"

[command_kick_option_target]
other = "対象"

[command_panel]
other = "panel"

[command_panel_desc]
other = "パネルの管理または作成"

[command_panel_option_desc_role]
other = "役割パネルの管理"

[command_panel_option_minecraft]
other = "マインクラフト"

[command_panel_option_minecraft_desc]
other = "マインクラフトパネルを管理"

[command_panel_option_minecraft_message]
other = 'To add a server right click or long press on the message and press "Apps" then "modify"'

[command_panel_option_minecraft_option_create]
other = "作成"

[command_panel_option_minecraft_option_create_desc]
other = "マインクラフトパネルを作成"

[command_panel_option_minecraft_option_create_option_address]
other = "アドレス"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "サーバーのアドレス"

[command_panel_option_minecraft_option_create_option_description]
other = "説明"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "パネルの説明"

[command_panel_option_minecraft_option_create_option_name]
other = "名前"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "パネル名"

[command_panel_option_minecraft_option_create_option_port]
other = "ポート"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "サーバーのポート"

[command_panel_option_minecraft_option_create_option_servername]
other = "サーバー名"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "サーバー名"

[command_panel_option_minecraft_option_create_option_showip]
other = "ipを表示"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "IPを表示するかどうか"

[command_panel_option_minecraft_placeholder]
other = "Select server"

[command_panel_option_role]
other = "ロール"

[command_panel_option_role_message]
other = 'To add a role right click or press and hold on the message and press "Apps" then "modify"'

[command_panel_option_role_option_create]
other = "作成"

[command_panel_option_role_option_create_option_desc]
other = "説明"

[command_panel_option_role_option_create_option_desc_desc]
other = "パネルの説明"

[command_panel_option_role_option_create_option_desc_name]
other = "パネル名"

[command_panel_option_role_option_create_option_desc_role]
other = "パネルに追加するロール"

[command_panel_option_role_option_create_option_name]
other = "名前"

[command_panel_option_role_option_create_option_role]
other = "ロール"

[command_panel_option_role_option_desc_create]
other = "役割パネルを作成"

[command_role]
other = "role"

[command_role_desc]
other = "manage role"

[command_role_option_color]
other = "color"

[command_role_option_color_desc]
other = "create color role"

[command_role_option_color_option_name]
other = "name"

[command_role_option_color_option_name_desc]
other = "name of role"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "rgb color code"

[command_tracker]
other = "トラッカー"

[command_tracker_desc]
other = "トラッカーを管理または作成する"

[command_tracker_option_minecraft]
other = "マインクラフト"

[command_tracker_option_minecraft_desc]
other = "マインクラフトサーバートラッカーを管理する"

[command_tracker_option_minecraft_option_create]
other = "作成"

[command_tracker_option_minecraft_option_create_desc]
other = "マインクラフトサーバートラッカー"

[command_tracker_option_minecraft_option_create_option_address]
other = "アドレス"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "サーバーのアドレス"

[command_tracker_option_minecraft_option_create_option_name]
other = "名前"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "サーバー名"

[command_tracker_option_minecraft_option_create_option_port]
other = "ポート"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "サーバーのポート"

[command_tracker_option_minecraft_option_create_option_role]
other = "ロール"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "メンションするロール"

[command_tracker_option_minecraft_option_get]
other = "取得"

[command_tracker_option_minecraft_option_get_desc]
other = "マインクラフトのトラッカーを取得します"

[command_tracker_option_minecraft_option_remove]
other = "削除"

[command_tracker_option_minecraft_option_remove_desc]
other = "マインクラフトのトラッカーを削除します"

[command_tracker_option_minecraft_option_remove_option_name]
other = "名前"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "トラッカーの名前"

[command_unban]
other = "unban"

[command_unban_desc]
other = "選択したユーザーのBANを解除"

[command_unban_message]
other = "{{.Target}} のBANを解除しました"

[command_unban_option_desc_target]
other = "BANを解除するユーザー"

[command_unban_option_target]
other = "対象"

[error]
other = "{{.Error}}"

[error_0]
other = "エラーが発生しました： {{.Error}}"

[error_TargetIsBot]
other = "このボットをターゲットとして選択できません！"

[error_failed_to_connect_api]
other = "APIサーバーの接続に失敗しました"

[error_failed_to_ping_server]
other = "サーバーへの接続に失敗しました"

[error_invalid_port_value]
other = "不正なポート値"

[error_message]
other = "エラーが発生しました"

[feed_minecraft_webhook_name]
other = "サーバ通知"

[latency]
other = "レイテンシ"

[message_command_modify]
other = "変更"

[message_command_user_info]
other = "info"

[message_command_user_info_color_code]
other = "Color Code"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Joined at"

[message_command_user_info_nick]
other = "Nick"

[message_command_user_info_none]
other = "none"

[message_command_user_info_roles]
other = "Roles"

[panel_minecraft_message_boot]
other = "{{.Name}} サーバーが起動しました"

[panel_minecraft_message_stop]
other = "{{.Name}} サーバーが停止しました"

[panel_role_message_added]
other = "追加"

[panel_role_message_removed]
other = "剥奪"

[players]
other = "プレイヤー"

[port]
other = "ポート"

[version]
other = "バージョン"

[message_modify_cant_use_this_message_error]
other = "not available for that message"

[message_modify_role_add_message]
other = "Choose a role to add"

[message_modify_role_create_message]
other = "Coose a role to create panel"
