[address]
other = "Adres"

[channel]
other = "kanaal"

[client_desktop]
other = "Startscherm"

[client_mobile]
other = "Mobiel"

[client_web]
other = "Internet"

[command_message]
other = "Bericht"

[command_message_description]
other = "beheren en verzenden van bericht"

[command_message_embed]
other = "ingesloten"

[command_message_embed_color]
other = "kleur"

[command_message_embed_color_description]
other = "rgb code van embedkleur"

[command_message_embed_content]
other = "inhoud"

[command_message_embed_content_description]
other = "inhoud van bericht"

[command_message_embed_description]
other = "verstuur insluitingsbericht met webhook"

[command_message_embed_embed_content]
other = "ingesloten inhoud"

[command_message_embed_embed_content_description]
other = "inhoud van bericht ingesloten"

[command_message_embed_embed_title]
other = "Titel"

[command_message_embed_embed_title_description]
other = "titel van het bericht ingesloten"

[command_message_embed_icon_url]
other = "pictogram url"

[command_message_embed_icon_url_description]
other = "URL van gebruiker avater"

[command_message_embed_username]
other = "gebruikersnaam"

[command_message_embed_username_description]
other = "naam van bericht afzender"

[command_message_webhook]
other = "webhook"

[command_message_webhook_description]
other = "verstuur webhook bericht"

[command_panel]
other = "paneel"

[command_panel_desc]
other = "beheren of maken van paneel"

[command_panel_option_config]
other = "configuratie"

[command_panel_option_config_desc]
other = "proprties configureren"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Aangepaste emoji instellen in selectiemenu"

[command_panel_option_config_option_emoji_message]
other = "Stuur alsjeblieft emoji in dit kanaal"

[command_panel_option_desc_role]
other = "beheer rolpaneel"

[command_panel_option_minecraft]
other = "minecraft"

[command_panel_option_minecraft_desc]
other = "Beheer minecraft paneel"

[command_panel_option_minecraft_message]
other = 'Om een server met de rechtermuisknop toe te voegen of druk lang op het bericht en druk op "Apps" en druk op "wijzigen"'

[command_panel_option_minecraft_option_create]
other = "aanmaken"

[command_panel_option_minecraft_option_create_desc]
other = "Maak minecraft paneel"

[command_panel_option_minecraft_option_create_option_address]
other = "Adres"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "adres van de server"

[command_panel_option_minecraft_option_create_option_description]
other = "beschrijving"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "beschrijving van paneel"

[command_panel_option_minecraft_option_create_option_name]
other = "Naam"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "naam van paneel"

[command_panel_option_minecraft_option_create_option_port]
other = "poort"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "poort van de server"

[command_panel_option_minecraft_option_create_option_servername]
other = "servernaam"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "naam van de server"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "Toon IP of niet"

[command_panel_option_minecraft_placeholder]
other = "Selecteer server"

[command_panel_option_role]
other = "rol"

[command_panel_option_role_message]
other = 'Om een rol toe te voegen klik of druk op het bericht en druk op "Apps" en druk op "Wijzigen"'

[command_panel_option_role_option_create]
other = "aanmaken"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "desc van paneel"

[command_panel_option_role_option_create_option_desc_name]
other = "naam van paneel"

[command_panel_option_role_option_create_option_desc_role]
other = "rol die aan het paneel toegevoegd wordt"

[command_panel_option_role_option_create_option_name]
other = "Naam"

[command_panel_option_role_option_create_option_role]
other = "rol"

[command_panel_option_role_option_desc_create]
other = "maak rolpaneel"

[command_role]
other = "rol"

[command_role_desc]
other = "rol beheren"

[command_role_option_color]
other = "kleur"

[command_role_option_color_desc]
other = "kleurenrol aanmaken"

[command_role_option_color_option_name]
other = "Naam"

[command_role_option_color_option_name_desc]
other = "naam van de rol"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "rgb kleurcode"

[command_tracker]
other = "tracker"

[command_tracker_desc]
other = "tracker beheren of maken"

[command_tracker_option_minecraft]
other = "minecraft"

[command_tracker_option_minecraft_desc]
other = "Beheer minecraft server tracker"

[command_tracker_option_minecraft_option_create]
other = "aanmaken"

[command_tracker_option_minecraft_option_create_desc]
other = "minecraft server tracker"

[command_tracker_option_minecraft_option_create_option_address]
other = "Adres"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "adres van de server"

[command_tracker_option_minecraft_option_create_option_name]
other = "Naam"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "naam van de server"

[command_tracker_option_minecraft_option_create_option_port]
other = "poort"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "poort van de server"

[command_tracker_option_minecraft_option_create_option_role]
other = "rol"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "rol om te vermelden"

[command_tracker_option_minecraft_option_get]
other = "pak"

[command_tracker_option_minecraft_option_get_desc]
other = "krijg minecraft trackers"

[command_tracker_option_minecraft_option_remove]
other = "verwijderen"

[command_tracker_option_minecraft_option_remove_desc]
other = "verwijder minecraft trackers"

[command_tracker_option_minecraft_option_remove_option_name]
other = "Naam"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "naam van de tracker"

[error]
other = "{{.Error}}"

[error_0]
other = "Er is een fout opgetreden {{.Error}}"

[error_TargetIsBot]
other = "Kan deze bot niet selecteren als doel!"

[error_bot_does_not_have_permissions]
other = "Onvoldoende bot machtigingen!\rHet moet een administrator toestemming krijgen van de server admin om te werken!"

[error_cannot_read_content]
other = "Inhoud van berichten niet gelezen"

[error_cannot_use_roles]
other = "De volgende rollen kunnen niet worden gebruikt"

[error_failed_to_connect_api]
other = "Kan geen verbinding maken met de API server fout"

[error_failed_to_ping_server]
other = "Kon server niet pingen"

[error_invalid_port_value]
other = "ongeldige poort waarde"

[error_invalid_roles]
other = "Ongeldige rol(en)"

[error_message]
other = "Er is een fout opgetreden"

[error_unknown_command]
other = "Onbekend gebruik"

[feed_minecraft_webhook_name]
other = "server notificatie"

[latency]
other = "latentie"

[message_command_modify]
other = "wijzigen"

[message_command_pin]
other = "Bericht pinnen"

[message_command_select]
other = "selecteren"

[message_command_select_message]
other = "Geselecteerd"

[message_command_user_info]
other = "info"

[message_command_user_info_color_code]
other = "Kleur Code"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Geregistreerd op"

[message_command_user_info_nick]
other = "Bijnaam"

[message_command_user_info_none]
other = "Geen"

[message_command_user_info_roles]
other = "Rollen"

[message_command_user_info_status]
other = "status"

[message_modify_cant_use_this_message_error]
other = "niet beschikbaar voor dat bericht"

[message_modify_role_add_message]
other = "Kies een toe te voegen rol"

[message_modify_role_create_message]
other = "Maak een rol vrij om een paneel aan te maken"

[online_status]
other = "status"

[panel_minecraft_add_server]
other = "Voeg een server toe"

[panel_minecraft_address]
other = "Adres:"

[panel_minecraft_display_name]
other = "Toon naam"

[panel_minecraft_message_boot]
other = "{{.Name}} is opgestart"

[panel_minecraft_message_stop]
other = "stopte {{.Name}}"

[panel_minecraft_my_server]
other = "Mijn server"

[panel_minecraft_port]
other = "Poort"

[panel_role_message_added]
other = "toegevoegd"

[panel_role_message_removed]
other = "verwijderd"

[players]
other = "spelers"

[port]
other = "poort"

[version]
other = "Versie"

[command_panel_vote]
other = "vote"

[command_panel_vote_desc]
other = "manage and create vote panel"

[command_panel_vote_create]
other = "create"

[command_panel_vote_create_desc]
other = "create vote panel"

[command_panel_vote_create_title]
other = "title"

[command_panel_vote_create_title_desc]
other = "title of vote panel"

[command_panel_vote_create_description]
other = "description"

[command_panel_vote_create_description_desc]
other = "description of vote panel"

[command_panel_vote_create_time]
other = "time limit"

[command_panel_vote_create_time_desc]
other = "time limit of vote panel"

[command_panel_vote_create_time_unit]
other = "time unit"

[command_panel_vote_create_time_unit_desc]
other = "unit of time limit"

[command_panel_vote_create_time_unit_day]
other = "day"

[command_panel_vote_create_time_unit_hour]
other = "hour"

[command_panel_vote_create_time_unit_minute]
other = "minute"

[command_panel_vote_create_min_choice]
other = "min choice"

[command_panel_vote_create_min_choice_desc]
other = "minimun number of choices"

[command_panel_vote_create_max_choice]
other = "max choice"

[command_panel_vote_create_max_choice_desc]
other = "maximum number of choices"

[command_panel_vote_create_show_count]
other = "show count"

[command_panel_vote_create_show_count_desc]
other = "show the values of vote"
