[address]
other = "Adres"

[channel]
other = "kanaal"

[command_ban]
other = "verbannen"

[command_ban_desc]
other = "verbannen de geselecteerde gebruiker"

[command_ban_message]
other = "{{.Target}} is verbannen"

[command_ban_option_desc_reason]
other = "reden voor verbannen"

[command_ban_option_desc_target]
other = "verbannen gebruiker"

[command_ban_option_reason]
other = "reden"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Reden: {{.Reason}}"
other = "Reden: {{.Reason}}"

[command_kick]
other = "uitzetten"

[command_kick_desc]
other = "Kick de geselecteerde gebruiker"

[command_kick_message]
other = "{{.Target}} is eruit gezet"

[command_kick_option_desc_target]
other = "uit te zetten gebruiker"

[command_kick_option_target]
other = "target"

[command_panel]
other = "paneel"

[command_panel_desc]
other = "beheren of maken van paneel"

[command_panel_option_desc_role]
other = "beheer rolpaneel"

[command_panel_option_minecraft]
other = "minecraft"

[command_panel_option_minecraft_desc]
other = "Beheer minecraft paneel"

[command_panel_option_minecraft_message]
other = 'Om een server met de rechtermuisknop toe te voegen of druk lang op het bericht en druk op "Apps" en druk op "wijzigen"'

[command_panel_option_minecraft_option_create]
other = "aanmaken"

[command_panel_option_minecraft_option_create_desc]
other = "Maak minecraft paneel"

[command_panel_option_minecraft_option_create_option_address]
other = "Adres"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "adres van de server"

[command_panel_option_minecraft_option_create_option_description]
other = "beschrijving"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "beschrijving van paneel"

[command_panel_option_minecraft_option_create_option_name]
other = "Naam"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "naam van paneel"

[command_panel_option_minecraft_option_create_option_port]
other = "poort"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "poort van de server"

[command_panel_option_minecraft_option_create_option_servername]
other = "servernaam"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "naam van de server"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "Toon IP of niet"

[command_panel_option_minecraft_placeholder]
other = "Selecteer server"

[command_panel_option_role]
other = "rol"

[command_panel_option_role_message]
other = 'Om een rol toe te voegen klik of druk op het bericht en druk op "Apps" en druk op "Wijzigen"'

[command_panel_option_role_option_create]
other = "aanmaken"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "desc van paneel"

[command_panel_option_role_option_create_option_desc_name]
other = "naam van paneel"

[command_panel_option_role_option_create_option_desc_role]
other = "rol die aan het paneel toegevoegd wordt"

[command_panel_option_role_option_create_option_name]
other = "Naam"

[command_panel_option_role_option_create_option_role]
other = "rol"

[command_panel_option_role_option_desc_create]
other = "maak rolpaneel"

[command_role]
other = "rol"

[command_role_desc]
other = "rol beheren"

[command_role_option_color]
other = "kleur"

[command_role_option_color_desc]
other = "kleurenrol aanmaken"

[command_role_option_color_option_name]
other = "Naam"

[command_role_option_color_option_name_desc]
other = "naam van de rol"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "rgb kleurcode"

[command_tracker]
other = "tracker"

[command_tracker_desc]
other = "tracker beheren of maken"

[command_tracker_option_minecraft]
other = "minecraft"

[command_tracker_option_minecraft_desc]
other = "Beheer minecraft server tracker"

[command_tracker_option_minecraft_option_create]
other = "aanmaken"

[command_tracker_option_minecraft_option_create_desc]
other = "minecraft server tracker"

[command_tracker_option_minecraft_option_create_option_address]
other = "Adres"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "adres van de server"

[command_tracker_option_minecraft_option_create_option_name]
other = "Naam"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "naam van de server"

[command_tracker_option_minecraft_option_create_option_port]
other = "poort"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "poort van de server"

[command_tracker_option_minecraft_option_create_option_role]
other = "rol"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "rol om te vermelden"

[command_tracker_option_minecraft_option_get]
other = "pak"

[command_tracker_option_minecraft_option_get_desc]
other = "krijg minecraft trackers"

[command_tracker_option_minecraft_option_remove]
other = "verwijderen"

[command_tracker_option_minecraft_option_remove_desc]
other = "verwijder minecraft trackers"

[command_tracker_option_minecraft_option_remove_option_name]
other = "Naam"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "naam van de tracker"

[command_unban]
other = "uitsluiten"

[command_unban_desc]
other = "deblokkeer de geselecteerde gebruiker"

[command_unban_message]
other = "{{.Target}} is niet meer verbannen"

[command_unban_option_desc_target]
other = "gebruiker om te unbannen"

[command_unban_option_target]
other = "target"

[error]
other = "{{.Error}}"

[error_0]
other = "Er is een fout opgetreden {{.Error}}"

[error_TargetIsBot]
other = "Kan deze bot niet selecteren als doel!"

[error_failed_to_connect_api]
other = "Kan geen verbinding maken met de API server fout"

[error_failed_to_ping_server]
other = "Kon server niet pingen"

[error_invalid_port_value]
other = "ongeldige poort waarde"

[error_message]
other = "Er is een fout opgetreden"

[feed_minecraft_webhook_name]
other = "server notificatie"

[latency]
other = "latentie"

[message_command_modify]
other = "wijzigen"

[message_command_user_info]
other = "info"

[message_command_user_info_color_code]
other = "Kleur Code"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Geregistreerd op"

[message_command_user_info_nick]
other = "Bijnaam"

[message_command_user_info_none]
other = "Geen"

[message_command_user_info_roles]
other = "Rollen"

[panel_minecraft_message_boot]
other = "booted {{.Name}}"

[panel_minecraft_message_stop]
other = "stopped {{.Name}}"

[panel_role_message_added]
other = "toegevoegd"

[panel_role_message_removed]
other = "verwijderd"

[players]
other = "spelers"

[port]
other = "poort"

[version]
other = "Versie"

[message_modify_cant_use_this_message_error]
other = "niet beschikbaar voor dat bericht"

[message_modify_role_add_message]
other = "Kies een toe te voegen rol"

[message_modify_role_create_message]
other = "Maak een rol vrij om een paneel aan te maken"

[message_command_select_message]
other = "Geselecteerd"

[message_command_select]
other = "selecteren"

[command_panel_option_config]
other = "configuratie"

[command_panel_option_config_desc]
other = "proprties configureren"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Aangepaste emoji instellen in selectiemenu"

[command_panel_option_config_option_emoji_message]
other = "Stuur alsjeblieft emoji in dit kanaal"
