[address]
other = "adresse"

[channel]
other = "kanal"

[command_ban]
other = "forbud"

[command_ban_desc]
other = "utesteng den valgte brukeren"

[command_ban_message]
other = "{{.Target}} har blitt utestengt"

[command_ban_option_desc_reason]
other = "årsak til utestengelsen"

[command_ban_option_desc_target]
other = "bruker å utestenge"

[command_ban_option_reason]
other = "grunn"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Årsak: {{.Reason}}"
other = "Årsak: {{.Reason}}"

[command_kick]
other = "spark"

[command_kick_desc]
other = "spark den valgte brukeren"

[command_kick_message]
other = "{{.Target}} har blitt sparket ut"

[command_kick_option_desc_target]
other = "bruker som skal sparke"

[command_kick_option_target]
other = "target"

[command_panel]
other = "panel"

[command_panel_desc]
other = "administrer eller opprett panel"

[command_panel_option_desc_role]
other = "administrere rollepanelet"

[command_panel_option_minecraft]
other = "minecraft"

[command_panel_option_minecraft_desc]
other = "administrere minecraft panel"

[command_panel_option_minecraft_message]
other = 'For å legge til en server høyre, klikk eller trykk lenge på meldingen og trykk "Apps" og deretter "endre"'

[command_panel_option_minecraft_option_create]
other = "Opprett"

[command_panel_option_minecraft_option_create_desc]
other = "opprett minecraft panel"

[command_panel_option_minecraft_option_create_option_address]
other = "adresse"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "adressen til serveren"

[command_panel_option_minecraft_option_create_option_description]
other = "beskrivelse"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "beskrivelse av panel"

[command_panel_option_minecraft_option_create_option_name]
other = "navn"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "navn på panelet"

[command_panel_option_minecraft_option_create_option_port]
other = "port"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "port av serveren"

[command_panel_option_minecraft_option_create_option_servername]
other = "servernavn"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "navnet på serveren"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "vis ip eller ikke"

[command_panel_option_minecraft_placeholder]
other = "Velg server"

[command_panel_option_role]
other = "rolle"

[command_panel_option_role_message]
other = 'For å legge til en rolle høyre, klikk eller hold i meldingen og trykk "Apps" og deretter "endre"'

[command_panel_option_role_option_create]
other = "Opprett"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "Beskrivelse av panel"

[command_panel_option_role_option_create_option_desc_name]
other = "navn på panelet"

[command_panel_option_role_option_create_option_desc_role]
other = "rolle som legger til i panelet"

[command_panel_option_role_option_create_option_name]
other = "navn"

[command_panel_option_role_option_create_option_role]
other = "rolle"

[command_panel_option_role_option_desc_create]
other = "opprett rollepanel"

[command_role]
other = "rolle"

[command_role_desc]
other = "administrere rolle"

[command_role_option_color]
other = "farge"

[command_role_option_color_desc]
other = "opprett fargerolle"

[command_role_option_color_option_name]
other = "navn"

[command_role_option_color_option_name_desc]
other = "navn på rolle"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "rgb fargekode"

[command_tracker]
other = "sporing"

[command_tracker_desc]
other = "administrere eller opprette tracker"

[command_tracker_option_minecraft]
other = "minecraft"

[command_tracker_option_minecraft_desc]
other = "administrer tracker for minecraft"

[command_tracker_option_minecraft_option_create]
other = "Opprett"

[command_tracker_option_minecraft_option_create_desc]
other = "minecraft server tracker"

[command_tracker_option_minecraft_option_create_option_address]
other = "adresse"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "adressen til serveren"

[command_tracker_option_minecraft_option_create_option_name]
other = "navn"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "navnet på serveren"

[command_tracker_option_minecraft_option_create_option_port]
other = "port"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "port av serveren"

[command_tracker_option_minecraft_option_create_option_role]
other = "rolle"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "rolle for å nevne"

[command_tracker_option_minecraft_option_get]
other = "hent"

[command_tracker_option_minecraft_option_get_desc]
other = "få minecraft sporere"

[command_tracker_option_minecraft_option_remove]
other = "fjern"

[command_tracker_option_minecraft_option_remove_desc]
other = "fjern minecraft sporere"

[command_tracker_option_minecraft_option_remove_option_name]
other = "navn"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "tracker navn"

[command_unban]
other = "avutestengelse"

[command_unban_desc]
other = "opphev bannlysningen av valgte bruker"

[command_unban_message]
other = "{{.Target}} har blitt utestengt"

[command_unban_option_desc_target]
other = "bruker som opphever utestengelsen"

[command_unban_option_target]
other = "target"

[error]
other = "{{.Error}}"

[error_0]
other = "En feil har oppstått {{.Error}}"

[error_TargetIsBot]
other = "Kan ikke velge denne botten som mål!"

[error_failed_to_connect_api]
other = "kunne ikke koble til server feil"

[error_failed_to_ping_server]
other = "kunne ikke ping av server"

[error_invalid_port_value]
other = "ugyldig port-verdi"

[error_message]
other = "En feil har oppstått"

[feed_minecraft_webhook_name]
other = "varsling av tjener"

[latency]
other = "latens"

[message_command_modify]
other = "endre"

[message_command_user_info]
other = "informasjon"

[message_command_user_info_color_code]
other = "Farge Kode"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Ble med"

[message_command_user_info_nick]
other = "Kallenavn"

[message_command_user_info_none]
other = "ingen"

[message_command_user_info_roles]
other = "Roller"

[panel_minecraft_message_boot]
other = "startet {{.Name}}"

[panel_minecraft_message_stop]
other = "stoppet {{.Name}}"

[panel_role_message_added]
other = "lagt til"

[panel_role_message_removed]
other = "fjernet"

[players]
other = "spillere"

[port]
other = "port"

[version]
other = "versjon"

[message_modify_cant_use_this_message_error]
other = "ikke tilgjengelig for den meldingen"

[message_modify_role_add_message]
other = "Velg en rolle å legge til"

[message_modify_role_create_message]
other = "Kos en rolle for å opprette panel"

[message_command_select_message]
other = "valgt"

[message_command_select]
other = "velg"

[command_panel_option_config]
other = "Konfigurasjon"

[command_panel_option_config_desc]
other = "Konfigurer proprties"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Sett egendefinerte emoji i velg meny"

[command_panel_option_config_option_emoji_message]
other = "Vennligst send emoji i denne kanalen"
