[address]
other = "adres"

[command_ban_desc]
other = "zbanuj wybranego użytkownika"

[command_ban_message]
other = "{{.Target}} został zbanowany"

[command_ban_option_desc_reason]
other = "powód zakazu"

[command_ban_option_desc_target]
other = "użytkownik do zbanowania"

[command_ban_option_reason]
other = "powód"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Powód: {{.Reason}}"
other = "Powody: {{.Reason}}"

[command_kick_desc]
other = "wyrzuć wybranego użytkownika"

[command_kick_message]
other = "{{.Target}} został wyrzucony"

[command_kick_option_desc_target]
other = "użytkownik do wyrzucenia"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "zarządzaj lub utwórz panel"

[command_panel_option_desc_role]
other = "zarządzanie panelem ról"

[command_panel_option_minecraft]
other = "rzemiosło"

[command_panel_option_minecraft_desc]
other = "zarządzanie panelem minecraft"

[command_panel_option_minecraft_option_create]
other = "utwórz"

[command_panel_option_minecraft_option_create_desc]
other = "utwórz panel minecraft"

[command_panel_option_minecraft_option_create_option_address]
other = "adres"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "adres serwera"

[command_panel_option_minecraft_option_create_option_description]
other = "opis"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "opis panelu"

[command_panel_option_minecraft_option_create_option_name]
other = "Nazwa"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "nazwa panelu"

[command_panel_option_minecraft_option_create_option_port]
other = "port"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "port serwera"

[command_panel_option_minecraft_option_create_option_servername]
other = "nazwa serwera"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "nazwa serwera"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "pokaż IP lub nie"

[command_panel_option_role]
other = "Rola"

[command_panel_option_role_option_create]
other = "utwórz"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "desc panelu"

[command_panel_option_role_option_create_option_desc_name]
other = "nazwa panelu"

[command_panel_option_role_option_create_option_desc_role]
other = "rola, która dodaje do panelu"

[command_panel_option_role_option_create_option_name]
other = "Nazwa"

[command_panel_option_role_option_create_option_role]
other = "Rola"

[command_panel_option_role_option_desc_create]
other = "utwórz panel ról"

[command_tracker]
other = "tracker"

[command_tracker_desc]
other = "zarządzaj lub utwórz tracker"

[command_tracker_option_minecraft]
other = "rzemiosło"

[command_tracker_option_minecraft_desc]
other = "zarządzanie śledzeniem serwera minecraft"

[command_tracker_option_minecraft_option_create]
other = "utwórz"

[command_tracker_option_minecraft_option_create_desc]
other = "tropiciel serwera minecraft"

[command_tracker_option_minecraft_option_create_option_address]
other = "adres"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "adres serwera"

[command_tracker_option_minecraft_option_create_option_name]
other = "Nazwa"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "nazwa serwera"

[command_tracker_option_minecraft_option_create_option_port]
other = "port"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "port serwera"

[command_tracker_option_minecraft_option_create_option_role]
other = "Rola"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "rola do wzmianki"

[command_unban_desc]
other = "odbanuj wybranego użytkownika"

[command_unban_message]
other = "{{.Target}} został odbanowany"

[command_unban_option_desc_target]
other = "użytkownik do odblokowania"

[command_unban_option_target]
other = "target"

[error]
other = "{{.Error}}"

[error_0]
other = "Wystąpił błąd {{.Error}}"

[error_TargetIsBot]
other = "Nie można wybrać tego bota jako celu!"

[error_failed_to_connect_api]
other = "błąd połączenia z serwerem api"

[error_failed_to_ping_server]
other = "nie udało się wyczyścić serwera"

[error_invalid_port_value]
other = "nieprawidłowa wartość portu"

[error_message]
other = "Wystąpił błąd"

[feed_minecraft_webhook_name]
other = "powiadomienie serwera"

[latency]
other = "opóźnienie"

[message_command_modify]
other = "modyfikacja"

[panel_minecraft_message_boot]
other = "uruchomiono serwer {{.Name}}"

[panel_minecraft_message_stop]
other = "zatrzymano serwer {{.Name}}"

[panel_role_message_added]
other = "dodany"

[panel_role_message_removed]
other = "usunięto"

[players]
other = "gracze"

[port]
other = "port"

[version]
other = "wersja"

[command_tracker_option_minecraft_option_get]
other = "pobierz"

[command_tracker_option_minecraft_option_get_desc]
other = "pobierz tropiciele minecraft"

[command_tracker_option_minecraft_option_remove]
other = "usuń"

[command_tracker_option_minecraft_option_remove_desc]
other = "usuń tropiciele minecraft"

[channel]
other = "kanał"

[command_tracker_option_minecraft_option_remove_option_name]
other = "Nazwa"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "nazwa trackera"

[command_panel_option_minecraft_message]
other = 'To add a server right click or long press on the message and press "Apps" then "modify"'

[command_panel_option_minecraft_placeholder]
other = "Select server"

[command_panel_option_role_message]
other = 'To add a role right click or press and hold on the message and press "Apps" then "modify"'

[command_role]
other = "role"

[command_role_desc]
other = "manage role"

[command_role_option_color]
other = "color"

[command_role_option_color_desc]
other = "create color role"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "rgb color code"

[command_role_option_color_option_name]
other = "name"

[command_role_option_color_option_name_desc]
other = "name of role"

[message_command_user_info]
other = "info"

[message_command_user_info_none]
other = "none"

[message_command_user_info_nick]
other = "Nick"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_roles]
other = "Roles"

[message_command_user_info_joined_at]
other = "Joined at"

[message_command_user_info_color_code]
other = "Color Code"
