[address]
other = "Endereço"

[channel]
other = "Canal"

[command_ban]
other = "banir"

[command_ban_desc]
other = "banir o usuário selecionado"

[command_ban_message]
other = "{{.Target}} foi banido"

[command_ban_option_desc_reason]
other = "motivo do banimento"

[command_ban_option_desc_target]
other = "usuário a banir"

[command_ban_option_reason]
other = "Razão"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Motivo: {{.Reason}}"
other = "Motivos: {{.Reason}}"

[command_kick]
other = "expulsar"

[command_kick_desc]
other = "expulsar o usuário selecionado"

[command_kick_message]
other = "{{.Target}} foi expulso"

[command_kick_option_desc_target]
other = "usuário para expulsar"

[command_kick_option_target]
other = "target"

[command_panel]
other = "painel"

[command_panel_desc]
other = "gerenciar ou criar painel"

[command_panel_option_desc_role]
other = "gerenciar painel de funções"

[command_panel_option_minecraft]
other = "Minecraft"

[command_panel_option_minecraft_desc]
other = "gerenciar painel do minecraft"

[command_panel_option_minecraft_message]
other = 'Para adicionar um servidor clique com o botão direito ou mantenha pressionado na mensagem e pressione "Apps" e "Modificar"'

[command_panel_option_minecraft_option_create]
other = "criar"

[command_panel_option_minecraft_option_create_desc]
other = "criar painel de minecraft"

[command_panel_option_minecraft_option_create_option_address]
other = "Endereço"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "endereço do servidor"

[command_panel_option_minecraft_option_create_option_description]
other = "Descrição"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "descrição do painel"

[command_panel_option_minecraft_option_create_option_name]
other = "Nome"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "nome do painel"

[command_panel_option_minecraft_option_create_option_port]
other = "Porta"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "porta do servidor"

[command_panel_option_minecraft_option_create_option_servername]
other = "nomedoServidor"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "nome do servidor"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "mostrar o IP ou não"

[command_panel_option_minecraft_placeholder]
other = "Selecionar servidor"

[command_panel_option_role]
other = "Função"

[command_panel_option_role_message]
other = 'Para adicionar um papel clique com o botão direito ou pressione e segure na mensagem e pressione "Apps" e "Modificar"'

[command_panel_option_role_option_create]
other = "criar"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "DESC do painel"

[command_panel_option_role_option_create_option_desc_name]
other = "nome do painel"

[command_panel_option_role_option_create_option_desc_role]
other = "função que adicionar ao painel"

[command_panel_option_role_option_create_option_name]
other = "Nome"

[command_panel_option_role_option_create_option_role]
other = "Função"

[command_panel_option_role_option_desc_create]
other = "criar painel de função"

[command_role]
other = "Função"

[command_role_desc]
other = "gerenciar função"

[command_role_option_color]
other = "cor"

[command_role_option_color_desc]
other = "criar função de cor"

[command_role_option_color_option_name]
other = "Nome"

[command_role_option_color_option_name_desc]
other = "nome da função"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "Código de cor RGB"

[command_tracker]
other = "rastreador"

[command_tracker_desc]
other = "gerenciar ou criar rastreador"

[command_tracker_option_minecraft]
other = "Minecraft"

[command_tracker_option_minecraft_desc]
other = "gerenciar rastreador de servidores do minecraft"

[command_tracker_option_minecraft_option_create]
other = "criar"

[command_tracker_option_minecraft_option_create_desc]
other = "minecraft rastreador de servidores"

[command_tracker_option_minecraft_option_create_option_address]
other = "Endereço"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "endereço do servidor"

[command_tracker_option_minecraft_option_create_option_name]
other = "Nome"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "nome do servidor"

[command_tracker_option_minecraft_option_create_option_port]
other = "Porta"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "porta do servidor"

[command_tracker_option_minecraft_option_create_option_role]
other = "Função"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "função para mencionar"

[command_tracker_option_minecraft_option_get]
other = "obtenha"

[command_tracker_option_minecraft_option_get_desc]
other = "obter rastreadores de minecraft"

[command_tracker_option_minecraft_option_remove]
other = "Remover"

[command_tracker_option_minecraft_option_remove_desc]
other = "remover rastreadores de minecraft"

[command_tracker_option_minecraft_option_remove_option_name]
other = "Nome"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "nome do rastreador"

[command_unban]
other = "desbanir"

[command_unban_desc]
other = "desbanir o usuário selecionado"

[command_unban_message]
other = "{{.Target}} foi desbanido"

[command_unban_option_desc_target]
other = "usuário para desbanir"

[command_unban_option_target]
other = "target"

[error]
other = "{{.Error}}"

[error_0]
other = "Ocorreu um erro {{.Error}}"

[error_TargetIsBot]
other = "Não é possível selecionar este bot como destino!"

[error_failed_to_connect_api]
other = "falha ao conectar erro do servidor api"

[error_failed_to_ping_server]
other = "falha ao fazer ping no servidor"

[error_invalid_port_value]
other = "valor de porta inválida"

[error_invalid_roles]
other = "Papéis inválidos"

[error_cannot_use_roles]
other = "Não é possível usar as seguintes funções"

[error_message]
other = "Ocorreu um erro"

[feed_minecraft_webhook_name]
other = "notificador do servidor"

[latency]
other = "latência"

[message_command_modify]
other = "Modificar"

[message_command_user_info]
other = "informações"

[message_command_user_info_color_code]
other = "Código de cor"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Entrou em"

[message_command_user_info_nick]
other = "Apelido"

[message_command_user_info_none]
other = "nenhuma"

[message_command_user_info_roles]
other = "Papéis"

[panel_minecraft_message_boot]
other = "inicializado em {{.Name}}"

[panel_minecraft_message_stop]
other = "parou {{.Name}}"

[panel_role_message_added]
other = "adicionado"

[panel_role_message_removed]
other = "removido"

[players]
other = "Jogadores"

[port]
other = "Porta"

[version]
other = "Versão"

[message_modify_cant_use_this_message_error]
other = "não disponível para essa mensagem"

[message_modify_role_add_message]
other = "Escolha um cargo para adicionar"

[message_modify_role_create_message]
other = "Codir uma função para criar um painel"

[message_command_select_message]
other = "Selecionado"

[message_command_select]
other = "selecionar"

[command_panel_option_config]
other = "configuração"

[command_panel_option_config_desc]
other = "configurar perfis"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Definir emojis personalizados no menu de seleção"

[command_panel_option_config_option_emoji_message]
other = "Por favor, envie emojis neste canal"

[panel_minecraft_display_name]
other = "Nome para exibição"

[panel_minecraft_address]
other = "Endereço"

[panel_minecraft_my_server]
other = "Meu servidor"

[panel_minecraft_port]
other = "Porta"

[panel_minecraft_add_server]
other = "Adicionar um servidor"

[client_desktop]
other = "Computadores"

[client_mobile]
other = "Celular"

[client_web]
other = "Web"

[online_status]
other = "SItuação"

[message_command_user_info_status]
other = "SItuação"
