[address]
other = "Endereço"

[command_ban_desc]
other = "banir o usuário selecionado"

[command_ban_message]
other = "{{.Target}} foi banido"

[command_ban_option_desc_reason]
other = "motivo do banimento"

[command_ban_option_desc_target]
other = "usuário a banir"

[command_ban_option_reason]
other = "Razão"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Motivo: {{.Reason}}"
other = "Motivos: {{.Reason}}"

[command_kick_desc]
other = "expulsar o usuário selecionado"

[command_kick_message]
other = "{{.Target}} foi expulso"

[command_kick_option_desc_target]
other = "usuário para expulsar"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "gerenciar ou criar painel"

[command_panel_option_desc_role]
other = "gerenciar painel de funções"

[command_panel_option_minecraft]
other = "Minecraft"

[command_panel_option_minecraft_desc]
other = "gerenciar painel do minecraft"

[command_panel_option_minecraft_option_create]
other = "criar"

[command_panel_option_minecraft_option_create_desc]
other = "criar painel de minecraft"

[command_panel_option_minecraft_option_create_option_address]
other = "Endereço"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "endereço do servidor"

[command_panel_option_minecraft_option_create_option_description]
other = "Descrição"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "descrição do painel"

[command_panel_option_minecraft_option_create_option_name]
other = "Nome"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "nome do painel"

[command_panel_option_minecraft_option_create_option_port]
other = "Porta"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "porta do servidor"

[command_panel_option_minecraft_option_create_option_servername]
other = "nomedoServidor"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "nome do servidor"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "mostrar o IP ou não"

[command_panel_option_role]
other = "Função"

[command_panel_option_role_option_create]
other = "criar"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "DESC do painel"

[command_panel_option_role_option_create_option_desc_name]
other = "nome do painel"

[command_panel_option_role_option_create_option_desc_role]
other = "função que adicionar ao painel"

[command_panel_option_role_option_create_option_name]
other = "Nome"

[command_panel_option_role_option_create_option_role]
other = "Função"

[command_panel_option_role_option_desc_create]
other = "criar painel de função"

[command_tracker]
other = "rastreador"

[command_tracker_desc]
other = "gerenciar ou criar rastreador"

[command_tracker_option_minecraft]
other = "Minecraft"

[command_tracker_option_minecraft_desc]
other = "gerenciar rastreador de servidores do minecraft"

[command_tracker_option_minecraft_option_create]
other = "criar"

[command_tracker_option_minecraft_option_create_desc]
other = "minecraft rastreador de servidores"

[command_tracker_option_minecraft_option_create_option_address]
other = "Endereço"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "endereço do servidor"

[command_tracker_option_minecraft_option_create_option_name]
other = "Nome"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "nome do servidor"

[command_tracker_option_minecraft_option_create_option_port]
other = "Porta"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "porta do servidor"

[command_tracker_option_minecraft_option_create_option_role]
other = "Função"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "função para mencionar"

[command_unban_desc]
other = "desbanir o usuário selecionado"

[command_unban_message]
other = "{{.Target}} foi desbanido"

[command_unban_option_desc_target]
other = "usuário para desbanir"

[command_unban_option_target]
other = "target"

[error]
other = "{{.Error}}"

[error_0]
other = "Ocorreu um erro {{.Error}}"

[error_TargetIsBot]
other = "Não é possível selecionar este bot como destino!"

[error_failed_to_connect_api]
other = "falha ao conectar erro do servidor api"

[error_failed_to_ping_server]
other = "falha ao fazer ping no servidor"

[error_invalid_port_value]
other = "valor de porta inválida"

[error_message]
other = "Ocorreu um erro"

[feed_minecraft_webhook_name]
other = "notificador do servidor"

[latency]
other = "latência"

[message_command_modify]
other = "Modificar"

[panel_minecraft_message_boot]
other = "servidor {{.Name}} inicializado"

[panel_minecraft_message_stop]
other = "parou {{.Name}} servidor"

[panel_role_message_added]
other = "adicionado"

[panel_role_message_removed]
other = "removido"

[players]
other = "Jogadores"

[port]
other = "Porta"

[version]
other = "Versão"

[command_tracker_option_minecraft_option_get]
other = "obtenha"

[command_tracker_option_minecraft_option_get_desc]
other = "obter rastreadores de minecraft"

[command_tracker_option_minecraft_option_remove]
other = "Remover"

[command_tracker_option_minecraft_option_remove_desc]
other = "remover rastreadores de minecraft"

[channel]
other = "Canal"

[command_tracker_option_minecraft_option_remove_option_name]
other = "Nome"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "nome do rastreador"

[command_panel_option_minecraft_message]
other = 'To add a server right click or long press on the message and press "Apps" then "modify"'

[command_panel_option_minecraft_placeholder]
other = "Select server"

[command_panel_option_role_message]
other = 'To add a role right click or press and hold on the message and press "Apps" then "modify"'
