[address]
other = "адрес"

[channel]
other = "канал"

[command_ban]
other = "бан"

[command_ban_desc]
other = "забанить выбранного пользователя"

[command_ban_message]
other = "{{.Target}} был забанен"

[command_ban_option_desc_reason]
other = "причина бана"

[command_ban_option_desc_target]
other = "забанить пользователя"

[command_ban_option_reason]
other = "причина"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Причина: {{.Reason}}"
other = "Причины: {{.Reason}}"

[command_kick]
other = "кик"

[command_kick_desc]
other = "выгнать выбранного пользователя"

[command_kick_message]
other = "{{.Target}} был кикнут"

[command_kick_option_desc_target]
other = "выгнать пользователя"

[command_kick_option_target]
other = "target"

[command_panel]
other = "панель"

[command_panel_desc]
other = "управление или создание панели"

[command_panel_option_desc_role]
other = "управление панелью ролей"

[command_panel_option_minecraft]
other = "манекфт"

[command_panel_option_minecraft_desc]
other = "управление панелью minecraft"

[command_panel_option_minecraft_message]
other = 'Чтобы добавить сервер щелкните правой кнопкой мыши или удерживайте сообщение и нажмите "Apps" затем "modify"'

[command_panel_option_minecraft_option_create]
other = "создать"

[command_panel_option_minecraft_option_create_desc]
other = "создать панель minecraft"

[command_panel_option_minecraft_option_create_option_address]
other = "адрес"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "адрес сервера"

[command_panel_option_minecraft_option_create_option_description]
other = "описание"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "описание панели"

[command_panel_option_minecraft_option_create_option_name]
other = "имя"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "название панели"

[command_panel_option_minecraft_option_create_option_port]
other = "порт"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "порт сервера"

[command_panel_option_minecraft_option_create_option_servername]
other = "имя сервера"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "имя сервера"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "показать ip или нет"

[command_panel_option_minecraft_placeholder]
other = "Выберите сервер"

[command_panel_option_role]
other = "роль"

[command_panel_option_role_message]
other = 'Чтобы добавить роль, щелкните правой кнопкой мыши или удерживайте сообщение и нажмите "Apps" и "modify"'

[command_panel_option_role_option_create]
other = "создать"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "описание панели"

[command_panel_option_role_option_create_option_desc_name]
other = "название панели"

[command_panel_option_role_option_create_option_desc_role]
other = "роль, добавляемая к панели"

[command_panel_option_role_option_create_option_name]
other = "имя"

[command_panel_option_role_option_create_option_role]
other = "роль"

[command_panel_option_role_option_desc_create]
other = "создать панель ролей"

[command_role]
other = "роль"

[command_role_desc]
other = "управлять ролью"

[command_role_option_color]
other = "цвет"

[command_role_option_color_desc]
other = "создать роль цвета"

[command_role_option_color_option_name]
other = "имя"

[command_role_option_color_option_name_desc]
other = "название роли"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "Код цвета rgb"

[command_tracker]
other = "трекер"

[command_tracker_desc]
other = "управление или создание трекера"

[command_tracker_option_minecraft]
other = "манекфт"

[command_tracker_option_minecraft_desc]
other = "управление трекером серверов minecraft"

[command_tracker_option_minecraft_option_create]
other = "создать"

[command_tracker_option_minecraft_option_create_desc]
other = "трекер серверов minecraft"

[command_tracker_option_minecraft_option_create_option_address]
other = "адрес"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "адрес сервера"

[command_tracker_option_minecraft_option_create_option_name]
other = "имя"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "имя сервера"

[command_tracker_option_minecraft_option_create_option_port]
other = "порт"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "порт сервера"

[command_tracker_option_minecraft_option_create_option_role]
other = "роль"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "упоминание роли"

[command_tracker_option_minecraft_option_get]
other = "получить"

[command_tracker_option_minecraft_option_get_desc]
other = "получить майнекратные трекеры"

[command_tracker_option_minecraft_option_remove]
other = "удалить"

[command_tracker_option_minecraft_option_remove_desc]
other = "удалить minecraft трекеры"

[command_tracker_option_minecraft_option_remove_option_name]
other = "имя"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "название трекера"

[command_unban]
other = "разбанить"

[command_unban_desc]
other = "разбанить выбранного пользователя"

[command_unban_message]
other = "{{.Target}} был разбанен"

[command_unban_option_desc_target]
other = "пользователь для разблокировки"

[command_unban_option_target]
other = "target"

[error]
other = "{{.Error}}"

[error_0]
other = "Произошла ошибка {{.Error}}"

[error_TargetIsBot]
other = "Невозможно выбрать этого бота в качестве цели!"

[error_failed_to_connect_api]
other = "не удалось подключиться к серверу api"

[error_failed_to_ping_server]
other = "не удалось выполнить запрос сервера"

[error_invalid_port_value]
other = "неверное значение порта"

[error_invalid_roles]
other = "Неверная роль(ы)"

[error_cannot_use_roles]
other = "Нельзя использовать следующие роли"

[error_message]
other = "Произошла ошибка"

[feed_minecraft_webhook_name]
other = "извещение сервера"

[latency]
other = "задержка"

[message_command_modify]
other = "изменить"

[message_command_user_info]
other = "инфо"

[message_command_user_info_color_code]
other = "Цветовой код"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Присоединился в"

[message_command_user_info_nick]
other = "Ник"

[message_command_user_info_none]
other = "нет"

[message_command_user_info_roles]
other = "Роли"

[panel_minecraft_message_boot]
other = "загружено {{.Name}}"

[panel_minecraft_message_stop]
other = "остановил {{.Name}}"

[panel_role_message_added]
other = "добавлено"

[panel_role_message_removed]
other = "удалён"

[players]
other = "игроков"

[port]
other = "порт"

[version]
other = "версия"

[message_modify_cant_use_this_message_error]
other = "недоступен для этого сообщения"

[message_modify_role_add_message]
other = "Выберите роль для добавления"

[message_modify_role_create_message]
other = "Выберите роль для создания панели"

[message_command_select_message]
other = "выбрано"

[message_command_select]
other = "выбрать"

[command_panel_option_config]
other = "настройки"

[command_panel_option_config_desc]
other = "настроить proprties"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Установить пользовательские эмодзи в меню выбора"

[command_panel_option_config_option_emoji_message]
other = "Пожалуйста, отправьте эмодзи в этом канале"

[panel_minecraft_display_name]
other = "Показать имя"

[panel_minecraft_address]
other = "Адрес"

[panel_minecraft_my_server]
other = "Мой сервер"

[panel_minecraft_port]
other = "Порт"

[panel_minecraft_add_server]
other = "Добавить сервер"
