[address]
other = "адреса"

[channel]
other = "канал"

[command_ban]
other = "бан"

[command_ban_desc]
other = "забанити вибраного користувача"

[command_ban_message]
other = "{{.Target}} був забанений"

[command_ban_option_desc_reason]
other = "причина для бану"

[command_ban_option_desc_target]
other = "користувач для блокування"

[command_ban_option_reason]
other = "причина"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Причина: {{.Reason}}"
other = "Причини: {{.Reason}}"

[command_kick]
other = "кік"

[command_kick_desc]
other = "вилучити вибраного користувача"

[command_kick_message]
other = "{{.Target}} був вигнаний"

[command_kick_option_desc_target]
other = "користувача для вилучення"

[command_kick_option_target]
other = "target"

[command_panel]
other = "панель"

[command_panel_desc]
other = "керування або створити панель"

[command_panel_option_desc_role]
other = "керувати панеллю ролей"

[command_panel_option_minecraft]
other = "вагонетка"

[command_panel_option_minecraft_desc]
other = "керувати панеллю minecraft"

[command_panel_option_minecraft_message]
other = 'Щоб додати сервер правою кнопкою або тривалим натисканням на повідомлення та натисніть "Додатки" потім "змінити"'

[command_panel_option_minecraft_option_create]
other = "створити"

[command_panel_option_minecraft_option_create_desc]
other = "створити панель minecraft"

[command_panel_option_minecraft_option_create_option_address]
other = "адреса"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "адреса сервера"

[command_panel_option_minecraft_option_create_option_description]
other = "опис"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "опис панелі"

[command_panel_option_minecraft_option_create_option_name]
other = "ім'я"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "назва панелі"

[command_panel_option_minecraft_option_create_option_port]
other = "порт"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "порт сервера"

[command_panel_option_minecraft_option_create_option_servername]
other = "ім'я серверу"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "ім'я сервера"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "показати ip чи ні"

[command_panel_option_minecraft_placeholder]
other = "Виберіть сервер"

[command_panel_option_role]
other = "роль"

[command_panel_option_role_message]
other = 'Щоб додати роль правою кнопкою миші або утримуючи повідомлення і натисніть "Додатки", тоді "змінити"'

[command_panel_option_role_option_create]
other = "створити"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "панель"

[command_panel_option_role_option_create_option_desc_name]
other = "назва панелі"

[command_panel_option_role_option_create_option_desc_role]
other = "роль, що додає до панелі"

[command_panel_option_role_option_create_option_name]
other = "ім'я"

[command_panel_option_role_option_create_option_role]
other = "роль"

[command_panel_option_role_option_desc_create]
other = "створити панель ролі"

[command_role]
other = "роль"

[command_role_desc]
other = "керувати роллю"

[command_role_option_color]
other = "колір"

[command_role_option_color_desc]
other = "створити роль кольору"

[command_role_option_color_option_name]
other = "ім'я"

[command_role_option_color_option_name_desc]
other = "ім'я ролі"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "код кольору rgb"

[command_tracker]
other = "трекер"

[command_tracker_desc]
other = "керування або створити трекер"

[command_tracker_option_minecraft]
other = "вагонетка"

[command_tracker_option_minecraft_desc]
other = "керувати відстежувачем сервера minecraft"

[command_tracker_option_minecraft_option_create]
other = "створити"

[command_tracker_option_minecraft_option_create_desc]
other = "minecraft сервер трекер"

[command_tracker_option_minecraft_option_create_option_address]
other = "адреса"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "адреса сервера"

[command_tracker_option_minecraft_option_create_option_name]
other = "ім'я"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "ім'я сервера"

[command_tracker_option_minecraft_option_create_option_port]
other = "порт"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "порт сервера"

[command_tracker_option_minecraft_option_create_option_role]
other = "роль"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "роль для згадування"

[command_tracker_option_minecraft_option_get]
other = "отримати"

[command_tracker_option_minecraft_option_get_desc]
other = "отримати вагонетку трекери"

[command_tracker_option_minecraft_option_remove]
other = "видалити"

[command_tracker_option_minecraft_option_remove_desc]
other = "видалити трекери minecraft"

[command_tracker_option_minecraft_option_remove_option_name]
other = "ім'я"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "ім'я трекера"

[command_unban]
other = "розблокування"

[command_unban_desc]
other = "розблокувати вибраного користувача"

[command_unban_message]
other = "{{.Target}} був розблокований"

[command_unban_option_desc_target]
other = "користувача для розблокування"

[command_unban_option_target]
other = "target"

[error]
other = "{{.Error}}"

[error_0]
other = "Відбулася помилка {{.Error}}"

[error_TargetIsBot]
other = "Не вдається вибрати цього бота як ціль!"

[error_failed_to_connect_api]
other = "помилка підключення до сервера API"

[error_failed_to_ping_server]
other = "помилка пінгування серверу"

[error_invalid_port_value]
other = "неприпустиме значення порту"

[error_message]
other = "Сталася помилка"

[feed_minecraft_webhook_name]
other = "сповіщення сервера"

[latency]
other = "затримка"

[message_command_modify]
other = "змінити"

[message_command_user_info]
other = "інформація"

[message_command_user_info_color_code]
other = "Код кольору"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Приєднався"

[message_command_user_info_nick]
other = "Псевдонім"

[message_command_user_info_none]
other = "нічого"

[message_command_user_info_roles]
other = "Ролі"

[panel_minecraft_message_boot]
other = "запущено сервер {{.Name}}"

[panel_minecraft_message_stop]
other = "зупинено сервер {{.Name}}"

[panel_role_message_added]
other = "додано"

[panel_role_message_removed]
other = "видалено"

[players]
other = "гравців"

[port]
other = "порт"

[version]
other = "версія"

[message_modify_cant_use_this_message_error]
other = "недоступно для цього повідомлення"

[message_modify_role_add_message]
other = "Виберіть роль для додавання"

[message_modify_role_create_message]
other = "Вибрати роль для створення панелі"

[message_command_select_message]
other = "обрано"

[message_command_select]
other = "вибрати"

[command_panel_option_config]
other = "конфігурація"

[command_panel_option_config_desc]
other = "налаштувати броні"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Встановити користувацькі емодзі в меню"

[command_panel_option_config_option_emoji_message]
other = "Будь ласка, надішліть emoji на цьому каналі"
