[address]
other = "адреса"

[command_ban_desc]
other = "забанити вибраного користувача"

[command_ban_message]
other = "{{.Target}} був забанений"

[command_ban_option_desc_reason]
other = "причина для бану"

[command_ban_option_desc_target]
other = "користувач для блокування"

[command_ban_option_reason]
other = "причина"

[command_ban_option_target]
other = "target"

[command_ban_reason]
one = "Причина: {{.Reason}}"
other = "Причини: {{.Reason}}"

[command_kick_desc]
other = "вилучити вибраного користувача"

[command_kick_message]
other = "{{.Target}} був вигнаний"

[command_kick_option_desc_target]
other = "користувача для вилучення"

[command_kick_option_target]
other = "target"

[command_panel_desc]
other = "керування або створити панель"

[command_panel_option_desc_role]
other = "керувати панеллю ролей"

[command_panel_option_minecraft]
other = "вагонетка"

[command_panel_option_minecraft_desc]
other = "керувати панеллю minecraft"

[command_panel_option_minecraft_option_create]
other = "створити"

[command_panel_option_minecraft_option_create_desc]
other = "створити панель minecraft"

[command_panel_option_minecraft_option_create_option_address]
other = "адреса"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "адреса сервера"

[command_panel_option_minecraft_option_create_option_description]
other = "опис"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "опис панелі"

[command_panel_option_minecraft_option_create_option_name]
other = "ім'я"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "назва панелі"

[command_panel_option_minecraft_option_create_option_port]
other = "порт"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "порт сервера"

[command_panel_option_minecraft_option_create_option_servername]
other = "ім'я серверу"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "ім'я сервера"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "показати ip чи ні"

[command_panel_option_role]
other = "роль"

[command_panel_option_role_option_create]
other = "створити"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "панель"

[command_panel_option_role_option_create_option_desc_name]
other = "назва панелі"

[command_panel_option_role_option_create_option_desc_role]
other = "роль, що додає до панелі"

[command_panel_option_role_option_create_option_name]
other = "ім'я"

[command_panel_option_role_option_create_option_role]
other = "роль"

[command_panel_option_role_option_desc_create]
other = "створити панель ролі"

[command_tracker]
other = "трекер"

[command_tracker_desc]
other = "керування або створити трекер"

[command_tracker_option_minecraft]
other = "вагонетка"

[command_tracker_option_minecraft_desc]
other = "керувати відстежувачем сервера minecraft"

[command_tracker_option_minecraft_option_create]
other = "створити"

[command_tracker_option_minecraft_option_create_desc]
other = "minecraft сервер трекер"

[command_tracker_option_minecraft_option_create_option_address]
other = "адреса"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "адреса сервера"

[command_tracker_option_minecraft_option_create_option_name]
other = "ім'я"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "ім'я сервера"

[command_tracker_option_minecraft_option_create_option_port]
other = "порт"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "порт сервера"

[command_tracker_option_minecraft_option_create_option_role]
other = "роль"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "роль для згадування"

[command_unban_desc]
other = "розблокувати вибраного користувача"

[command_unban_message]
other = "{{.Target}} був розблокований"

[command_unban_option_desc_target]
other = "користувача для розблокування"

[command_unban_option_target]
other = "target"

[error]
other = "{{.Error}}"

[error_0]
other = "Відбулася помилка {{.Error}}"

[error_TargetIsBot]
other = "Не вдається вибрати цього бота як ціль!"

[error_failed_to_connect_api]
other = "помилка підключення до сервера API"

[error_failed_to_ping_server]
other = "помилка пінгування серверу"

[error_invalid_port_value]
other = "неприпустиме значення порту"

[error_message]
other = "Сталася помилка"

[feed_minecraft_webhook_name]
other = "сповіщення сервера"

[latency]
other = "затримка"

[message_command_modify]
other = "змінити"

[panel_minecraft_message_boot]
other = "запущено сервер {{.Name}}"

[panel_minecraft_message_stop]
other = "зупинено сервер {{.Name}}"

[panel_role_message_added]
other = "додано"

[panel_role_message_removed]
other = "видалено"

[players]
other = "гравців"

[port]
other = "порт"

[version]
other = "версія"

[command_tracker_option_minecraft_option_get]
other = "отримати"

[command_tracker_option_minecraft_option_get_desc]
other = "отримати вагонетку трекери"

[command_tracker_option_minecraft_option_remove]
other = "видалити"

[command_tracker_option_minecraft_option_remove_desc]
other = "видалити трекери minecraft"

[channel]
other = "канал"

[command_tracker_option_minecraft_option_remove_option_name]
other = "ім'я"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "ім'я трекера"

[command_panel_option_minecraft_message]
other = 'To add a server right click or long press on the message and press "Apps" then "modify"'

[command_panel_option_minecraft_placeholder]
other = "Select server"

[command_panel_option_role_message]
other = 'To add a role right click or press and hold on the message and press "Apps" then "modify"'
