[address]
other = "адреса"

[channel]
other = "канал"

[client_desktop]
other = "Стільниця"

[client_mobile]
other = "Мобільний"

[client_web]
other = "Веб"

[command_message]
other = "message"

[command_message_description]
other = "manage and send message"

[command_message_embed]
other = "embed"

[command_message_embed_color]
other = "color"

[command_message_embed_color_description]
other = "rgb code of embed color"

[command_message_embed_content]
other = "content"

[command_message_embed_content_description]
other = "content of message"

[command_message_embed_description]
other = "send embed message with webhook"

[command_message_embed_embed_content]
other = "embed content"

[command_message_embed_embed_content_description]
other = "content of message embed"

[command_message_embed_embed_title]
other = "title"

[command_message_embed_embed_title_description]
other = "title of message embed"

[command_message_embed_icon_url]
other = "icon url"

[command_message_embed_icon_url_description]
other = "url of user avater"

[command_message_embed_username]
other = "username"

[command_message_embed_username_description]
other = "name of message sender"

[command_message_webhook]
other = "webhook"

[command_message_webhook_description]
other = "send webhook message"

[command_panel]
other = "панель"

[command_panel_desc]
other = "керування або створити панель"

[command_panel_option_config]
other = "конфігурація"

[command_panel_option_config_desc]
other = "налаштувати броні"

[command_panel_option_config_option_emoji]
other = "emoji"

[command_panel_option_config_option_emoji_desc]
other = "Встановити користувацькі емодзі в меню"

[command_panel_option_config_option_emoji_message]
other = "Будь ласка, надішліть emoji на цьому каналі"

[command_panel_option_desc_role]
other = "керувати панеллю ролей"

[command_panel_option_minecraft]
other = "вагонетка"

[command_panel_option_minecraft_desc]
other = "керувати панеллю minecraft"

[command_panel_option_minecraft_message]
other = 'Щоб додати сервер правою кнопкою або тривалим натисканням на повідомлення та натисніть "Додатки" потім "змінити"'

[command_panel_option_minecraft_option_create]
other = "створити"

[command_panel_option_minecraft_option_create_desc]
other = "створити панель minecraft"

[command_panel_option_minecraft_option_create_option_address]
other = "адреса"

[command_panel_option_minecraft_option_create_option_address_desc]
other = "адреса сервера"

[command_panel_option_minecraft_option_create_option_description]
other = "опис"

[command_panel_option_minecraft_option_create_option_description_desc]
other = "опис панелі"

[command_panel_option_minecraft_option_create_option_name]
other = "ім'я"

[command_panel_option_minecraft_option_create_option_name_desc]
other = "назва панелі"

[command_panel_option_minecraft_option_create_option_port]
other = "порт"

[command_panel_option_minecraft_option_create_option_port_desc]
other = "порт сервера"

[command_panel_option_minecraft_option_create_option_servername]
other = "ім'я серверу"

[command_panel_option_minecraft_option_create_option_servername_desc]
other = "ім'я сервера"

[command_panel_option_minecraft_option_create_option_showip]
other = "showip"

[command_panel_option_minecraft_option_create_option_showip_desc]
other = "показати ip чи ні"

[command_panel_option_minecraft_placeholder]
other = "Виберіть сервер"

[command_panel_option_role]
other = "роль"

[command_panel_option_role_message]
other = 'Щоб додати роль правою кнопкою миші або утримуючи повідомлення і натисніть "Додатки", тоді "змінити"'

[command_panel_option_role_option_create]
other = "створити"

[command_panel_option_role_option_create_option_desc]
other = "desc"

[command_panel_option_role_option_create_option_desc_desc]
other = "панель"

[command_panel_option_role_option_create_option_desc_name]
other = "назва панелі"

[command_panel_option_role_option_create_option_desc_role]
other = "роль, що додає до панелі"

[command_panel_option_role_option_create_option_name]
other = "ім'я"

[command_panel_option_role_option_create_option_role]
other = "роль"

[command_panel_option_role_option_desc_create]
other = "створити панель ролі"

[command_role]
other = "роль"

[command_role_desc]
other = "керувати роллю"

[command_role_option_color]
other = "колір"

[command_role_option_color_desc]
other = "створити роль кольору"

[command_role_option_color_option_name]
other = "ім'я"

[command_role_option_color_option_name_desc]
other = "ім'я ролі"

[command_role_option_color_option_rgb]
other = "rgb"

[command_role_option_color_option_rgb_desc]
other = "код кольору rgb"

[command_tracker]
other = "трекер"

[command_tracker_desc]
other = "керування або створити трекер"

[command_tracker_option_minecraft]
other = "вагонетка"

[command_tracker_option_minecraft_desc]
other = "керувати відстежувачем сервера minecraft"

[command_tracker_option_minecraft_option_create]
other = "створити"

[command_tracker_option_minecraft_option_create_desc]
other = "minecraft сервер трекер"

[command_tracker_option_minecraft_option_create_option_address]
other = "адреса"

[command_tracker_option_minecraft_option_create_option_address_desc]
other = "адреса сервера"

[command_tracker_option_minecraft_option_create_option_name]
other = "ім'я"

[command_tracker_option_minecraft_option_create_option_name_desc]
other = "ім'я сервера"

[command_tracker_option_minecraft_option_create_option_port]
other = "порт"

[command_tracker_option_minecraft_option_create_option_port_desc]
other = "порт сервера"

[command_tracker_option_minecraft_option_create_option_role]
other = "роль"

[command_tracker_option_minecraft_option_create_option_role_desc]
other = "роль для згадування"

[command_tracker_option_minecraft_option_get]
other = "отримати"

[command_tracker_option_minecraft_option_get_desc]
other = "отримати вагонетку трекери"

[command_tracker_option_minecraft_option_remove]
other = "видалити"

[command_tracker_option_minecraft_option_remove_desc]
other = "видалити трекери minecraft"

[command_tracker_option_minecraft_option_remove_option_name]
other = "ім'я"

[command_tracker_option_minecraft_option_remove_option_name_desc]
other = "ім'я трекера"

[error]
other = "{{.Error}}"

[error_0]
other = "Відбулася помилка {{.Error}}"

[error_TargetIsBot]
other = "Не вдається вибрати цього бота як ціль!"

[error_bot_does_not_have_permissions]
other = "Недостатньо прав для бота!\rАдміністратор повинен бути наданий адміністратору на роботу!"

[error_cannot_read_content]
other = "Cant read message content."

[error_cannot_use_roles]
other = "Наступні ролі не можна використовувати"

[error_failed_to_connect_api]
other = "помилка підключення до сервера API"

[error_failed_to_ping_server]
other = "помилка пінгування серверу"

[error_invalid_port_value]
other = "неприпустиме значення порту"

[error_invalid_roles]
other = "Невірна роль(и)"

[error_message]
other = "Сталася помилка"

[error_unknown_command]
other = "Unkown operation"

[feed_minecraft_webhook_name]
other = "сповіщення сервера"

[latency]
other = "затримка"

[message_command_modify]
other = "змінити"

[message_command_pin]
other = "pin message"

[message_command_select]
other = "вибрати"

[message_command_select_message]
other = "обрано"

[message_command_user_info]
other = "інформація"

[message_command_user_info_color_code]
other = "Код кольору"

[message_command_user_info_id]
other = "ID"

[message_command_user_info_joined_at]
other = "Приєднався"

[message_command_user_info_nick]
other = "Псевдонім"

[message_command_user_info_none]
other = "нічого"

[message_command_user_info_roles]
other = "Ролі"

[message_command_user_info_status]
other = "Статус"

[message_modify_cant_use_this_message_error]
other = "недоступно для цього повідомлення"

[message_modify_role_add_message]
other = "Виберіть роль для додавання"

[message_modify_role_create_message]
other = "Вибрати роль для створення панелі"

[online_status]
other = "Статус"

[panel_minecraft_add_server]
other = "Додати сервер"

[panel_minecraft_address]
other = "Адреса"

[panel_minecraft_display_name]
other = "Ім'я для відображення"

[panel_minecraft_message_boot]
other = "стартував {{.Name}}"

[panel_minecraft_message_stop]
other = "зупинено {{.Name}}"

[panel_minecraft_my_server]
other = "Мій сервер"

[panel_minecraft_port]
other = "Порт"

[panel_role_message_added]
other = "додано"

[panel_role_message_removed]
other = "видалено"

[players]
other = "гравців"

[port]
other = "порт"

[version]
other = "версія"
